In [1]:
from functools import cache

from calitp_data_analysis.gcs_pandas import GCSPandas


@cache
def gcs_pandas():
    return GCSPandas()

import pandas as pd
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

In [2]:
# need to get ntd ID of all California agencies
from calitp_data_analysis.sql import query_sql

# query agency information, then filter for a single gtfs feed,
# and then count how often each feed key occurs
ca_agencies = query_sql(
    """
    SELECT distinct ntd_id, agency, city, state, agency_voms
    FROM cal-itp-data-infra.mart_ntd.dim_annual_service_agencies
    WHERE state = 'CA' AND report_year = 2024
    """,
    as_df=True,
)

ca_agencies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209 entries, 0 to 208
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ntd_id       209 non-null    object
 1   agency       209 non-null    object
 2   city         209 non-null    object
 3   state        209 non-null    object
 4   agency_voms  209 non-null    float64
dtypes: float64(1), object(4)
memory usage: 8.3+ KB

In [3]:
rev_veh_inv_link = "gs://calitp-analytics-data/data-analyses/ntd/2024 Revenue Vehicle Inventory_250820.xlsx"

rev_veh = gcs_pandas().read_excel(rev_veh_inv_link)
rev_veh["NTD ID"] = rev_veh["NTD ID"].astype("str")

In [4]:
ca_rev_veh = rev_veh[rev_veh["NTD ID"].isin(ca_agencies["ntd_id"].unique().tolist())]

# List of vehicles for CA agencies from the 2024 Revenue Vehicle Inventory

In [5]:
ca_rev_veh = ca_rev_veh.groupby(
    [
        "NTD ID",
        "Agency Name",
    ]
).agg({
    "Total Fleet Vehicles": "sum",
    "ModeTOS Vehicles Operated in Maximum Service":"max"
}).reset_index()

## difference between VOMs and Rev Vehicle Inv.

In [6]:
diff_voms_ref_veh = ca_rev_veh.merge(
    ca_agencies,
    left_on="NTD ID",
    right_on="ntd_id",
    how="inner",
    indicator=True
)

In [9]:
diff_voms_ref_veh["voms_diff"] = diff_voms_ref_veh["ModeTOS Vehicles Operated in Maximum Service"] - diff_voms_ref_veh["agency_voms"]

In [13]:
diff_voms_ref_veh["rev_veh_voms_diff"] = diff_voms_ref_veh["Total Fleet Vehicles"] - diff_voms_ref_veh["ModeTOS Vehicles Operated in Maximum Service"]

In [16]:
diff_voms_ref_veh.describe()

,Total Fleet Vehicles,ModeTOS Vehicles Operated in Maximum Service,agency_voms,voms_diff,rev_veh_voms_diff
count,209.000000,209.000000,209.000000,209.000000,209.000000
mean,133.033493,54.401914,83.430622,-29.028708,78.631579
std,390.845120,147.942430,244.023419,113.089903,260.334037
min,1.000000,1.000000,1.000000,-1246.000000,-1.000000
25%,10.000000,4.000000,5.000000,-12.000000,4.000000
50%,23.000000,10.000000,15.000000,-4.000000,13.000000
75%,83.000000,29.000000,42.000000,0.000000,47.000000
max,4415.000000,1476.000000,2722.000000,0.000000,2939.000000

In [17]:
diff_voms_ref_veh

,NTD ID,Agency Name,Total Fleet Vehicles,ModeTOS Vehicles Operated in Maximum Service,ntd_id,agency,city,state,agency_voms,_merge,voms_diff,rev_veh_voms_diff
0,90003,San Francisco Bay Area Rapid Transit District,785,566.0,90003,"San Francisco Bay Area Rapid Transit District,...",Oakland,CA,582.0,both,-16.0,219.0
1,90004,Golden Empire Transit District,160,51.0,90004,Golden Empire Transit District,Bakersfield,CA,93.0,both,-42.0,109.0
2,90006,Santa Cruz Metropolitan Transit District,147,58.0,90006,Santa Cruz Metropolitan Transit District,Santa Cruz,CA,97.0,both,-39.0,89.0
3,90008,City of Santa Monica,239,124.0,90008,"City of Santa Monica, dba: Big Blue Bus",Santa Monica,CA,162.0,both,-38.0,115.0
4,90009,San Mateo County Transit District,468,178.0,90009,"San Mateo County Transit District, dba: SamTrans",San Carlos,CA,361.0,both,-183.0,290.0
5,90010,City of Torrance,104,38.0,90010,"City of Torrance, dba: Torrance Transit System",Torrance,CA,74.0,both,-36.0,66.0
6,90012,San Joaquin Regional Transit District,178,74.0,90012,"San Joaquin Regional Transit District, dba: Sa...",Stockton,CA,105.0,both,-31.0,104.0
7,90013,Santa Clara Valley Transportation Authority,818,341.0,90013,"Santa Clara Valley Transportation Authority, d...",San Jose,CA,520.0,both,-179.0,477.0
8,90014,Alameda-Contra Costa Transit District,851,371.0,90014,"Alameda-Contra Costa Transit District, dba: AC...",Oakland,CA,619.0,both,-248.0,480.0
9,90015,City and County of San Francisco,1366,364.0,90015,"City and County of San Francisco, dba: San Fra...",San Francisco,CA,777.0,both,-413.0,1002.0
10,90016,"Golden Gate Bridge, Highway and Transportation...",171,55.0,90016,"Golden Gate Bridge, Highway and Transportation...",San Francisco,CA,73.0,both,-18.0,116.0
11,90017,City of Santa Rosa,47,18.0,90017,"City of Santa Rosa, dba: Santa Rosa CityBus",Santa Rosa,CA,29.0,both,-11.0,29.0
12,90019,Sacramento Regional Transit District,557,193.0,90019,"Sacramento Regional Transit District, dba: Sac...",Sacramento,CA,387.0,both,-194.0,364.0
13,90020,Santa Barbara Metropolitan Transit District,118,71.0,90020,Santa Barbara Metropolitan Transit District,Santa Barbara,CA,71.0,both,0.0,47.0
14,90022,City of Norwalk,48,20.0,90022,"City of Norwalk , dba: Norwalk Transit System",Norwalk,CA,27.0,both,-7.0,28.0
15,90023,Long Beach Transit,242,187.0,90023,Long Beach Transit,Long Beach,CA,196.0,both,-9.0,55.0
16,90024,City of La Mirada,16,5.0,90024,"City of La Mirada , dba: La Mirada Transit",La Mirada,CA,5.0,both,0.0,11.0
17,90026,San Diego Metropolitan Transit System,1292,284.0,90026,San Diego Metropolitan Transit System,San Diego,CA,819.0,both,-535.0,1008.0
18,90027,City of Fresno,190,110.0,90027,"City of Fresno, dba: Fresno Area Express",Fresno,CA,152.0,both,-42.0,80.0
19,90029,Omnitrans,228,116.0,90029,"Omnitrans, dba: OMNI",San Bernardino,CA,167.0,both,-51.0,112.0
20,90030,North County Transit District,236,131.0,90030,North County Transit District,Oceanside,CA,191.0,both,-60.0,105.0
21,90031,Riverside Transit Agency,304,90.0,90031,Riverside Transit Agency,Riverside,CA,225.0,both,-135.0,214.0
22,90035,Gold Coast Transit District,105,49.0,90035,Gold Coast Transit District,Oxnard,CA,74.0,both,-25.0,56.0
23,90036,Orange County Transportation Authority,1529,242.0,90036,Orange County Transportation Authority,Orange,CA,887.0,both,-645.0,1287.0
24,90039,City of Culver City,60,40.0,90039,"City of Culver City, dba: Culver CityBus",Culver City,CA,42.0,both,-2.0,20.0
25,90041,City of Montebello,112,40.0,90041,"City of Montebello, dba: Montebello Bus Lines",Montebello,CA,81.0,both,-41.0,72.0
26,90042,City of Gardena,93,25.0,90042,"City of Gardena, dba: GTrans",Gardena,CA,29.0,both,-4.0,68.0
27,90043,City of Commerce,29,10.0,90043,"City of Commerce, dba: City of Commerce Transit",Commerce,CA,14.0,both,-4.0,19.0
28,90044,City of Arcadia,18,8.0,90044,"City of Arcadia, dba: Arcadia Transit",Arcadia,CA,14.0,both,-6.0,10.0
29,90050,City of Simi Valley,24,9.0,90050,"City of Simi Valley, dba: Simi Valley Transit",Simi Valley,CA,15.0,both,-6.0,15.0
30,90052,City of Corona,20,6.0,90052,City of Corona,Corona,CA,11.0,both,-5.0,14.0
31,90061,Yuba-Sutter Transit Authority,49,12.0,90061,Yuba-Sutter Transit Authority,Marysville,CA,29.0,both,-17.0,37.0
32,90062,Monterey-Salinas Transit,293,48.0,90062,Monterey-Salinas Transit,Monterey,CA,165.0,both,-117.0,245.0
33,90078,Central Contra Costa Transit Authority,194,76.0,90078,"Central Contra Costa Transit Authority, dba: C...",Concord,CA,136.0,both,-60.0,118.0
34,90079,SunLine Transit Agency,175,47.0,90079,"SunLine Transit Agency, dba: SunLine",Thousand Palms,CA,89.0,both,-42.0,128.0
35,90086,City of Riverside,35,21.0,90086,"City of Riverside, dba: Riverside Connect",Riverside,CA,21.0,both,0.0,14.0
36,90087,City of Santa Maria,36,21.0,90087,"City of Santa Maria, dba: Santa Maria Regional...",Santa Maria,CA,25.0,both,-4.0,15.0
37,90088,Napa Valley Transportation Authority,61,21.0,90088,Napa Valley Transportation Authority,Napa,CA,48.0,both,-27.0,40.0
38,90089,County of Sonoma,90,35.0,90089,"County of Sonoma , dba: Sonoma County Transit",Santa Rosa,CA,56.0,both,-21.0,55.0
39,90090,Yolo County Transportation District,83,32.0,90090,Yolo County Transportation District,Woodland,CA,44.0,both,-12.0,51.0
40,90091,City of Visalia,78,26.0,90091,"City of Visalia , dba: Visalia Transit",Visalia,CA,37.0,both,-11.0,52.0
41,90092,"City of Fairfield, California",43,12.0,90092,"City of Fairfield, California, dba: FAST Transit",Fairfield,CA,22.0,both,-10.0,31.0
42,90093,Redding Area Bus Authority,39,13.0,90093,Redding Area Bus Authority,Redding,CA,23.0,both,-10.0,26.0
43,90094,Metropolitan Transportation Commission,829,562.0,90094,"Metropolitan Transportation Commission, dba: MTC",San Francisco,CA,562.0,both,0.0,267.0
44,90095,San Diego Association of Governments,632,395.0,90095,"San Diego Association of Governments, dba: SANDAG",San Diego,CA,395.0,both,0.0,237.0
45,90119,City of Laguna Beach,32,18.0,90119,"City of Laguna Beach, dba: Laguna Beach Transit",Laguna Beach,CA,24.0,both,-6.0,14.0
46,90121,Antelope Valley Transit Authority,159,48.0,90121,Antelope Valley Transit Authority,Lancaster,CA,88.0,both,-40.0,111.0
47,90134,Peninsula Corridor Joint Powers Board,163,72.0,90134,"Peninsula Corridor Joint Powers Board, dba: Ca...",San Carlos,CA,72.0,both,0.0,91.0
48,90142,"University of California, Davis",56,29.0,90142,"University of California, Davis, dba: Unitrans",Davis,CA,29.0,both,0.0,27.0
49,90144,Livermore / Amador Valley Transit Authority,67,49.0,90144,Livermore / Amador Valley Transit Authority,Livermore,CA,49.0,both,0.0,18.0
50,90146,Foothill Transit,357,303.0,90146,Foothill Transit,West Covina,CA,303.0,both,0.0,54.0
51,90147,City of Los Angeles,513,186.0,90147,City of Los Angeles,Los Angeles,CA,389.0,both,-203.0,327.0
52,90148,Victor Valley Transit Authority,590,209.0,90148,Victor Valley Transit Authority,Hesperia,CA,304.0,both,-95.0,381.0
53,90149,City of Lompoc,16,2.0,90149,"City of Lompoc, dba: City of Lompoc Transit",Lompoc,CA,10.0,both,-8.0,14.0
54,90151,Southern California Regional Rail Authority,314,195.0,90151,"Southern California Regional Rail Authority, d...",Los Angeles,CA,195.0,both,0.0,119.0
55,90154,Los Angeles County Metropolitan Transportation...,4415,1476.0,90154,Los Angeles County Metropolitan Transportation...,Los Angeles,CA,2722.0,both,-1246.0,2939.0
56,90155,City of Vacaville,29,11.0,90155,"City of Vacaville, dba: City Coach",Vacaville,CA,14.0,both,-3.0,18.0
57,90156,City of San Luis Obispo,19,18.0,90156,"City of San Luis Obispo, dba: SLO Transit",San Luis Obispo,CA,18.0,both,0.0,1.0
58,90157,Access Services,1732,696.0,90157,Access Services,El Monte,CA,1047.0,both,-351.0,1036.0
59,90159,Western Contra Costa Transit Authority,50,21.0,90159,"Western Contra Costa Transit Authority, dba: W...",Pinole,CA,33.0,both,-12.0,29.0
60,90161,City of Union City,26,14.0,90161,"City of Union City, dba: Union City Transit",Union City,CA,21.0,both,-7.0,12.0
61,90162,The Eastern Contra Costa Transit Authority,116,50.0,90162,"The Eastern Contra Costa Transit Authority, db...",Antioch,CA,97.0,both,-47.0,66.0
62,90163,City of Camarillo,18,16.0,90163,"City of Camarillo, dba: Camarillo Area Transit",Camarillo,CA,18.0,both,-2.0,2.0
63,90164,Ventura County Transportation Commission,51,27.0,90164,Ventura County Transportation Commission,Camarillo,CA,42.0,both,-15.0,24.0
64,90165,City of Thousand Oaks,35,13.0,90165,"City of Thousand Oaks, dba: Thousand Oaks Transit",Thousand Oaks,CA,21.0,both,-8.0,22.0
65,90167,City of Davis,5,3.0,90167,"City of Davis, dba: Davis Community Transit",Davis,CA,3.0,both,0.0,2.0
66,90168,City of Roseville,52,10.0,90168,City of Roseville,Roseville,CA,24.0,both,-14.0,42.0
67,90171,City of Santa Clarita,119,44.0,90171,"City of Santa Clarita, dba: Santa Clarita Transit",Santa Clarita,CA,88.0,both,-44.0,75.0
68,90173,Transit Joint Powers Authority for Merced County,91,28.0,90173,Transit Joint Powers Authority for Merced Coun...,Merced,CA,45.0,both,-17.0,63.0
69,90175,City of Lodi,25,8.0,90175,"City of Lodi, dba: GrapeLine",Lodi,CA,13.0,both,-5.0,17.0
70,90182,Altamont Corridor Express,40,28.0,90182,Altamont Corridor Express,Stockton,CA,28.0,both,0.0,12.0
71,90194,City of Atascadero,4,2.0,90194,City of Atascadero,Atascadero,CA,2.0,both,0.0,2.0
72,90196,County of Placer,80,20.0,90196,"County of Placer, dba: Placer County Transit/TART",Auburn,CA,42.0,both,-22.0,60.0
73,90197,City of Tracy,21,11.0,90197,"City of Tracy, dba: TRACER",Tracy,CA,15.0,both,-4.0,10.0
74,90199,City of Madera,22,14.0,90199,"City of Madera, dba: Madera Metro",Madera,CA,22.0,both,-8.0,8.0
75,90200,Kings County Area Public Transit Agency,96,45.0,90200,Kings County Area Public Transit Agency,Hanford,CA,68.0,both,-23.0,51.0
76,90201,City of Turlock,19,11.0,90201,"City of Turlock, dba: Turlock Transit",Turlock,CA,13.0,both,-2.0,8.0
77,90206,San Luis Obispo Regional Transit Authority,69,23.0,90206,San Luis Obispo Regional Transit Authority,San Luis Obispo,CA,38.0,both,-15.0,46.0
78,90208,Butte County Association of Governments,51,24.0,90208,"Butte County Association of Governments, dba: ...",Chico,CA,37.0,both,-13.0,27.0
79,90211,Anaheim Transportation Network,95,49.0,90211,"Anaheim Transportation Network, dba: Anaheim R...",Anaheim,CA,62.0,both,-13.0,46.0
80,90213,City of Petaluma,24,7.0,90213,"City of Petaluma, dba: Petaluma Transit",Petaluma,CA,11.0,both,-4.0,17.0
81,90214,City of Redondo Beach,20,13.0,90214,"City of Redondo Beach, dba: Beach Cities Transit",Redondo Beach,CA,17.0,both,-4.0,7.0
82,90216,County of Sacramento Municipal Services Agency,19,7.0,90216,County of Sacramento Municipal Services Agency...,Sacramento,CA,12.0,both,-5.0,12.0
83,90217,City of Manteca,10,4.0,90217,"City of Manteca, dba: Manteca Transit",Manteca,CA,6.0,both,-2.0,6.0
84,90218,Riverside County Transportation Commission,45,37.0,90218,Riverside County Transportation Commission,Riverside,CA,37.0,both,0.0,8.0
85,90223,"Paratransit, Inc.",50,12.0,90223,"Paratransit, Inc.",Sacramento,CA,38.0,both,-26.0,38.0
86,90225,San Francisco Bay Area Water Emergency Transpo...,17,11.0,90225,San Francisco Bay Area Water Emergency Transpo...,San Francisco,CA,11.0,both,0.0,6.0
87,90226,Imperial County Transportation Commission,64,20.0,90226,Imperial County Transportation Commission,El Centro,CA,38.0,both,-18.0,44.0
88,90227,City of Moorpark,5,2.0,90227,"City of Moorpark, dba: Moorpark City Transit",Moorpark,CA,2.0,both,0.0,3.0
89,90229,El Dorado County Transit Authority,50,7.0,90229,"El Dorado County Transit Authority, dba: El Do...",Diamond Springs,CA,18.0,both,-11.0,43.0
90,90230,California Vanpool Authority,908,736.0,90230,"California Vanpool Authority, dba: CalVans",Visalia,CA,736.0,both,0.0,172.0
91,90232,Solano County Transit,65,16.0,90232,"Solano County Transit, dba: SolTrans",Vallejo,CA,37.0,both,-21.0,49.0
92,90234,Marin County Transit District,110,50.0,90234,"Marin County Transit District, dba: Marin Transit",San Rafael,CA,72.0,both,-22.0,60.0
93,90238,City of Delano,17,5.0,90238,"City of Delano, dba: Delano Area Rapid Transit",Delano,CA,9.0,both,-4.0,12.0
94,90243,Easy Lift Transportation,28,28.0,90243,Easy Lift Transportation,Goleta,CA,28.0,both,0.0,0.0
95,90246,City of Agoura Hills,23,2.0,90246,City of Agoura Hills,Agoura Hills,CA,2.0,both,0.0,21.0
96,90247,City of Alhambra,21,10.0,90247,"City of Alhambra, dba: Alhambra Community Transit",Alhambra,CA,19.0,both,-9.0,11.0
97,90249,City of Avalon,7,7.0,90249,"City of Avalon, dba: Avalon Transit",Avalon,CA,9.0,both,-2.0,0.0
98,90250,City of Azusa,6,6.0,90250,City of Azusa,Azusa,CA,6.0,both,0.0,0.0
99,90251,City of Baldwin Park,10,6.0,90251,"City of Baldwin Park, dba: Baldwin Park Transit",Baldwin Park,CA,8.0,both,-2.0,4.0
100,90252,City of Bell,23,8.0,90252,City of Bell,Bell,CA,10.0,both,-2.0,15.0
101,90253,City of Bell Gardens,7,3.0,90253,City of Bell Gardens,Bell,CA,6.0,both,-3.0,4.0
102,90254,City of Bellflower,7,2.0,90254,City of Bellflower,Bellflower,CA,4.0,both,-2.0,5.0
103,90255,City of Beverly Hills,5,4.0,90255,"City of Beverly Hills, dba: Beverly Hills Dial...",Beverly Hills,CA,4.0,both,0.0,1.0
104,90256,City of Burbank,32,11.0,90256,City of Burbank,Burbank,CA,17.0,both,-6.0,21.0
105,90257,City of Calabasas,10,6.0,90257,City of Calabasas,Calabasas,CA,8.0,both,-2.0,4.0
106,90258,City of Carson,19,8.0,90258,City of Carson,Carson,CA,19.0,both,-11.0,11.0
107,90259,City of Cerritos,18,10.0,90259,"City of Cerritos, dba: Cerritos Transit Services",Cerritos,CA,16.0,both,-6.0,8.0
108,90260,City of Compton,10,5.0,90260,"City of Compton , dba: Compton Renaissance Tr...",Compton,CA,5.0,both,0.0,5.0
109,90261,City of Covina,5,5.0,90261,City of Covina,Covina,CA,5.0,both,0.0,0.0
110,90262,City of Cudahy,11,5.0,90262,"City of Cudahy, dba: Cudahy Area Rapid Transit",Cudahy,CA,6.0,both,-1.0,6.0
111,90263,City of Downey,15,8.0,90263,City of Downey,Downey,CA,15.0,both,-7.0,7.0
112,90265,City of El Monte,24,5.0,90265,City of El Monte,El Monte,CA,14.0,both,-9.0,19.0
113,90266,City of Glendora,9,7.0,90266,City of Glendora,Glendora,CA,10.0,both,-3.0,2.0
114,90267,City of Huntington Park,27,9.0,90267,City of Huntington Park,Huntington Park,CA,16.0,both,-7.0,18.0
115,90268,City of Inglewood,9,8.0,90268,"City of Inglewood, dba: Inglewood Senior Center",Inglewood,CA,9.0,both,-1.0,1.0
116,90269,Los Angeles County,2,2.0,90269,"Los Angeles County, dba: LA County Public Works",Alhambra,CA,2.0,both,0.0,0.0
117,90270,Los Angeles County,4,1.0,90270,Los Angeles County,Alhambra,CA,1.0,both,0.0,3.0
118,90271,Los Angeles County,22,9.0,90271,Los Angeles County,Alhambra,CA,16.0,both,-7.0,13.0
119,90272,Los Angeles County,4,1.0,90272,Los Angeles County,Alhambra,CA,1.0,both,0.0,3.0
120,90273,Los Angeles County,4,2.0,90273,Los Angeles County,Alhambra,CA,2.0,both,0.0,2.0
121,90274,Los Angeles County,2,2.0,90274,Los Angeles County,Alhambra,CA,2.0,both,0.0,0.0
122,90275,Los Angeles County,1,1.0,90275,Los Angeles County,Alhambra,CA,1.0,both,0.0,0.0
123,90276,Los Angeles County,6,5.0,90276,Los Angeles County,Alhambra,CA,5.0,both,0.0,1.0
124,90277,Los Angeles County,13,10.0,90277,Los Angeles County,Alhambra,CA,10.0,both,0.0,3.0
125,90278,Los Angeles County,3,3.0,90278,Los Angeles County,Alhambra,CA,3.0,both,0.0,0.0
126,90279,Los Angeles County,6,3.0,90279,Los Angeles County,Alhambra,CA,3.0,both,0.0,3.0
127,90281,City of Lynwood,4,4.0,90281,"City of Lynwood, dba: Lynwood Breeze",Lynwood,CA,4.0,both,0.0,0.0
128,90282,City of Malibu,7,2.0,90282,City of Malibu,Malibu,CA,2.0,both,0.0,5.0
129,90283,City of Manhattan Beach,4,3.0,90283,"City of Manhattan Beach , dba: City of Manhatt...",Manhattan Beach,CA,3.0,both,0.0,1.0
130,90284,City of Maywood,7,4.0,90284,City of Maywood,Maywood,CA,5.0,both,-1.0,3.0
131,90285,City of Monrovia,12,4.0,90285,"City of Monrovia, dba: GoMonrovia",Monrovia,CA,4.0,both,0.0,8.0
132,90286,City of Monterey Park,16,8.0,90286,"City of Monterey Park, dba: Spirit Bus",Montery Park,CA,12.0,both,-4.0,8.0
133,90287,Palos Verdes Peninsula Transit Authority,27,21.0,90287,Palos Verdes Peninsula Transit Authority,Rolling Hills,CA,27.0,both,-6.0,6.0
134,90288,City of Pico Rivera,3,2.0,90288,City of Pico Rivera,Pico Rivera,CA,2.0,both,0.0,1.0
135,90289,City of Rosemead,7,4.0,90289,"City of Rosemead, dba: Rosemead Explorer/Dial-...",Rosemead,CA,7.0,both,-3.0,3.0
136,90290,City of Santa Fe Springs,5,2.0,90290,City of Santa Fe Springs,Santa Fe Springs,CA,2.0,both,0.0,3.0
137,90291,City of South Gate,15,9.0,90291,City of South Gate,South Gate,CA,15.0,both,-6.0,6.0
138,90292,City of South Pasadena,5,4.0,90292,City of South Pasadena,South Pasadena,CA,4.0,both,0.0,1.0
139,90293,City of West Covina,11,4.0,90293,City of West Covina,West Covina,CA,8.0,both,-4.0,7.0
140,90294,City of West Hollywood,14,5.0,90294,City of West Hollywood,West Hollywood,CA,9.0,both,-4.0,9.0
141,90295,City of Whittier,16,10.0,90295,City of Whittier,Whittier,CA,10.0,both,0.0,6.0
142,90296,City of Claremont,473,6.0,90296,City of Claremont,Claremont,CA,17.0,both,-11.0,467.0
143,90298,County of Ventura,3,4.0,90298,County of Ventura,Ventura,CA,4.0,both,0.0,-1.0
144,90299,Sonoma-Marin Area Rail Transit District,20,12.0,90299,Sonoma-Marin Area Rail Transit District,Petaluma,CA,14.0,both,-2.0,8.0
145,90300,City of Artesia,7,5.0,90300,City of Artesia,Artesia,CA,6.0,both,-1.0,2.0
146,90301,City of Lakewood,12,12.0,90301,"City of Lakewood , dba: DASH Transit",Lakewood,CA,12.0,both,0.0,0.0
147,90302,San Bernardino County Transportation Authority,97,79.0,90302,San Bernardino County Transportation Authority,San Bernardino,CA,79.0,both,0.0,18.0
148,90303,Santa Barbara County Association of Governments,18,10.0,90303,Santa Barbara County Association of Government...,Santa Barbara,CA,10.0,both,0.0,8.0
149,90306,Stanislaus Regional Transit Authority,142,65.0,90306,Stanislaus Regional Transit Authority,Modesto,CA,108.0,both,-43.0,77.0
150,90310,Tulare County Regional Transit Agency,100,26.0,90310,Tulare County Regional Transit Agency,Visalia,CA,45.0,both,-19.0,74.0
151,90311,Stanislaus Council of Governments,134,100.0,90311,"Stanislaus Council of Governments, dba: Stanis...",Modesto,CA,100.0,both,0.0,34.0
152,90313,City of Clovis,55,27.0,90313,"City of Clovis, dba: Clovis Transit",Clovis,CA,35.0,both,-8.0,28.0
153,90314,Attentive Transportation LLC,1,1.0,90314,Attentive Transportation LLC,Sacramento,CA,1.0,both,0.0,0.0
154,91000,Amador Transit,18,10.0,91000,Amador Transit,Jackson,CA,17.0,both,-7.0,8.0
155,91002,City of Corcoran,6,4.0,91002,"City of Corcoran, dba: Corcoran Area Transit",Corcoran,CA,4.0,both,0.0,2.0
156,91005,Madera County,13,5.0,91005,"Madera County, dba: Madera County Connection",Madera,CA,9.0,both,-4.0,8.0
157,91006,City of Ridgecrest,10,4.0,91006,"City of Ridgecrest, dba: Ridgerunner",Ridgecrest,CA,5.0,both,-1.0,6.0
158,91007,Fresno County Rural Transit Agency,120,51.0,91007,Fresno County Rural Transit Agency,Fresno,CA,65.0,both,-14.0,69.0
159,91008,Modoc Transportation Agency,6,2.0,91008,"Modoc Transportation Agency, dba: Sage Stage",Alturas,CA,3.0,both,-1.0,4.0
160,91009,San Benito County Local Transportation Authority,27,13.0,91009,San Benito County Local Transportation Authori...,Hollister,CA,19.0,both,-6.0,14.0
161,91012,Mountain Area Regional Transit Authority,35,20.0,91012,"Mountain Area Regional Transit Authority, dba:...",Big Bear Lake,CA,32.0,both,-12.0,15.0
162,91014,City of Rio Vista,5,1.0,91014,"City of Rio Vista, dba: Rio Vista Delta Breeze",Rio Vista,CA,2.0,both,-1.0,4.0
163,91018,City of Arcata,8,3.0,91018,"City of Arcata, dba: Arcata & Mad River Transi...",Arcata,CA,3.0,both,0.0,5.0
164,91020,City of Needles,6,1.0,91020,"City of Needles, dba: Needles Area Transit",Needles,CA,1.0,both,0.0,5.0
165,91027,City of Arvin,6,3.0,91027,"City of Arvin, dba: Arvin Transit",Arvin,CA,4.0,both,-1.0,3.0
166,91028,City of Solvang,6,3.0,91028,"City of Solvang, dba: Santa Ynez Valley Transit",Solvang,CA,5.0,both,-2.0,3.0
167,91032,City of Auburn,10,4.0,91032,"City of Auburn, dba: Auburn Transit",Auburn,CA,6.0,both,-2.0,6.0

# Count of routes