* To run a function in a Makefile, go do make rt_sched_pipeline

In [2]:
import dask.dataframe as dd
import pandas as pd
import yaml
from segment_speed_utils import gtfs_schedule_wrangling, helpers
from segment_speed_utils.project_vars import RT_SCHED_GCS, SCHED_GCS, SEGMENT_GCS
from shared_utils import portfolio_utils, rt_dates, rt_utils

In [3]:
# Times
import datetime

from loguru import logger

In [4]:
# Read in the files
dec_trips = pd.read_parquet("gs://calitp-analytics-data/data-analyses/rt_vs_schedule/vp_trip/trip_metrics/trip_2023-12-13.parquet")

In [9]:
dec_trips.sample()

,schedule_gtfs_dataset_key,trip_instance_key,rt_service_min,min_w_atleast2_trip_updates,total_pings,total_min_w_gtfs,total_vp,vp_in_shape,route_id,direction_id,sched_rt_category,sched_time_of_day,service_minutes,rt_time_of_day,time_of_day,pings_per_min,spatial_accuracy_pct,rt_w_gtfs_pct,rt_v_scheduled_time_pct
16053,3f3f36b4c41cc6b5df3eb7f5d8ea6e3c,b9058b92437faff13b1afda4f94a0ed3,85,79,212,85,212,211,28-13172,1,vp_sched,Evening,68.0,Evening,Evening,2.494118,0.995283,1.0,0.25

In [5]:
jan_trips = pd.read_parquet("gs://calitp-analytics-data/data-analyses/rt_vs_schedule/vp_trip/trip_metrics/trip_2024-01-17.parquet")

In [6]:
feb_trips = pd.read_parquet("gs://calitp-analytics-data/data-analyses/rt_vs_schedule/vp_trip/trip_metrics/trip_2024-02-14.parquet")

In [7]:
dec_routes = pd.read_parquet("gs://calitp-analytics-data/data-analyses/rt_vs_schedule/vp_route_dir/route_direction_metrics/route_2024-02-14.parquet")

In [8]:
dec_routes.sample()

,time_period,schedule_gtfs_dataset_key,route_id,direction_id,total_min_w_gtfs,rt_service_min,total_pings,service_minutes,total_vp,vp_in_shape,n_trips,pings_per_min,spatial_accuracy_pct,rt_w_gtfs_pct,rt_v_scheduled_time_pct
1416,all_day,8fa3380c9291d3694494c34b014642d0,1,0,1048,1169,3072,684.0,3072,3019,38,2.627887,0.982747,0.896493,0.709064