# Multi-Agency Ridership Data Standardization and Stop-Level Aggregation Workflow

This notebook processes ridership data from multiple transit agencies to create representative stop-level datasets for weekdays, Saturdays, and Sundays. For each agency, the workflow generally includes:

- Adding day type based on the service date (Weekday, Saturday, Sunday), with holidays normalized or removed as needed.
- Cleaning and renaming columns to ensure consistency across datasets (stop IDs, stop names, and ridership fields).
- Summing boardings and alightings across directions at each stop, and aggregating multiple time periods where applicable.
- Calculating weighted averages when ridership is reported over multiple periods, using the number of service days as weights.
- Setting a ridership basis flag to indicate that values represent reported daily boardings and/or alightings.
- Computing final average ridership per stop, and day type, producing clean, representative stop-level datasets ready for modeling, analysis, or comparison across agencies.

This approach standardizes ridership data across agencies with differing data formats, missing values, and service coverage, enabling consistent cross-agency analysis.

In [1]:
pip install shared_utils

/home/jovyan/data-analyses/.venv/bin/python: No module named pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
# Importing necessary package 
import pandas as pd 
import geopandas as gpd
import numpy as np
import google.auth
import os
import gcsfs
from calitp_data_analysis.sql import get_engine
from calitp_data_analysis import utils
db_engine = get_engine()
credentials, project = google.auth.default()
from pandas.tseries.holiday import USFederalHolidayCalendar
fs = gcsfs.GCSFileSystem()

pd.set_option('display.max_columns', None)

In [3]:
GCS_FILE_PATH  = 'gs://calitp-analytics-data/data-analyses/ahsc_grant/ahsc_riderships'

In [4]:
bart_ridership = pd.read_excel(f"{GCS_FILE_PATH}/bart_ridership.xlsx")
big_blue_bus_ridership = pd.read_excel(f"{GCS_FILE_PATH}/big_blue_bus_ridership.xlsx")
caltrain_ridership = pd.read_excel(f"{GCS_FILE_PATH}/caltrain_ridership.xlsx")
culver_citybus_ridership = pd.read_excel(f"{GCS_FILE_PATH}/culver_citybus_ridership.xlsx")
foothill_transit_ridership = pd.read_excel(f"{GCS_FILE_PATH}/foothill_transit_ridership.xlsx")
fresno_area_express_ridership = pd.read_excel(f"{GCS_FILE_PATH}/fresno_area_express_ridership.xlsx")
gold_coast_transit_ridership = pd.read_excel(f"{GCS_FILE_PATH}/gold_coast_transit_ridership.xlsx")
golden_gate_park_shuttle_ridership = pd.read_excel(f"{GCS_FILE_PATH}/golden_gate_park_shuttle_ridership.xlsx")
golden_gate_transit_ridership = pd.read_excel(f"{GCS_FILE_PATH}/golden_gate_transit_ridership.xlsx")
long_beach_transit_ridership=  pd.read_excel(f"{GCS_FILE_PATH}/long_beach_transit_ridership.xlsx")
octa_ridership = pd.read_excel(f"{GCS_FILE_PATH}/octa_ridership.xlsx")
omni_trans_ridership= pd.read_excel(f"{GCS_FILE_PATH}/omni_trans_ridership.xlsx")
riverside_transit_ridership= pd.read_excel(f"{GCS_FILE_PATH}/riverside_transit_ridership.xlsx")
sacrt_bus_ridership = pd.read_excel(f"{GCS_FILE_PATH}/sacrt_bus_ridership.xlsx")
samtrans_ridership = pd.read_excel(f"{GCS_FILE_PATH}/samtrans_ridership.xlsx")
santa_cruz_metro_ridership = pd.read_excel(f"{GCS_FILE_PATH}/santa_cruz_metro_ridership.xlsx")
sbmtd_ridership = pd.read_excel(f"{GCS_FILE_PATH}/sbmtd_ridership.xlsx")
sdmts_ridership = pd.read_excel(f"{GCS_FILE_PATH}/sdmts_ridership.xlsx")
sunline_transit_ridership = pd.read_excel(f"{GCS_FILE_PATH}/sunline_transit_ridership.xlsx")
burbank_ridership = pd.read_excel(f"{GCS_FILE_PATH}/burbank_ridership.xlsx")

In [5]:
def add_day_type(df, date_col, output_col='day_type'):
    """
    Classify each row as 'Weekday', 'Saturday', or 'Sunday' based on a specified date column.
    This is useful when daily datasets include labels such as 'Holiday' or when no day_type
    column exists. The function converts the date column, identifies the day of week, and
    standardizes the day-type classification accordingly. Either a start_date or end_date
    column can be used for datasets with daily reporting.
    """
    df = df.copy()

    df[date_col] = pd.to_datetime(df[date_col], errors='coerce')

    dow = df[date_col].dt.dayofweek  

    df[output_col] = np.select(
        condlist=[dow.eq(5), dow.eq(6)],
        choicelist=['Saturday', 'Sunday'],
        default='Weekday'
    )

    return df

In [6]:
# Counting number of days without holidays
def count_service_days(row):
    
    if str(row.day_type).lower() == "all":
        return (row.end_date - row.start_date).days + 1

    dates = pd.date_range(row.start_date, row.end_date)

    if row.day_type == "Weekday":
        return sum(d.weekday() < 5 for d in dates)

    elif row.day_type == "Saturday":
        return sum(d.weekday() == 5 for d in dates)

    elif row.day_type == "Sunday":
        return sum(d.weekday() == 6 for d in dates)

In [7]:
# Counting number of days with holidays
def count_service_days_wo_holidays(row):
    dates = pd.date_range(row.start_date, row.end_date)

    if row.day_type == "Weekday":
        return sum((d.weekday() < 5) and (d not in holiday_set) for d in dates)

    elif row.day_type == "Saturday":
        return sum((d.weekday() == 5) and (d not in holiday_set) for d in dates)

    elif row.day_type == "Sunday":
        return sum((d.weekday() == 6) and (d not in holiday_set) for d in dates)

In [8]:
def compute_averages(df, ridership_cols, group_cols):
    """
    Computes average of one or more ridership columns per group in long format.

    Parameters:
    - df: pandas DataFrame
    - ridership_cols: list of columns to average (e.g., ['daily_boardings', 'daily_alightings'])
    - group_cols: list of columns to group by (e.g., ['stop_name', 'day_type'])

    Returns:
    - DataFrame with columns: group_cols + average of each ridership column
    """
    
    if isinstance(ridership_cols, str):
        ridership_cols = [ridership_cols]  # allow single string input
    
    averaged = df.groupby(group_cols)[ridership_cols].mean().reset_index()
    
    # rename each column to indicate it's averaged
    averaged = averaged.rename(columns={col: f"average_{col}" for col in ridership_cols})
    
    return averaged

In [9]:
master_cols = [
    "organization_name",
    "stop_id",
    "stop_name",
    "stop_lat",
    "stop_lon",
    "day_type",
    "average_daily_boardings",
    "average_daily_alightings",
    "start_date",
    "end_date"
]

def standardize_columns(df, master_cols):
    
    # add missing columns
    for col in master_cols:
        if col not in df.columns:
            df[col] = None

    # keep only master columns and order them
    return df[master_cols]

In [10]:
bart_ridership = add_day_type(bart_ridership, date_col='start_date')

bart_ridership = bart_ridership.rename(columns={
    'Station Name': 'stop_name',
    'Stop ID': 'stop_id',
    'Date': 'date'
})

# Grouping columns
group_cols = [
    "date", "stop_id", "stop_name",
    "start_date", "end_date", "day_type"
]

# Sum boardings and alightings, with explicit output names
total_bart_ridership = (
    bart_ridership
    .groupby(group_cols, as_index=False)
    .agg(
        daily_boardings=("Entries", "sum"),
        daily_alightings=("Exits", "sum")
    )
)

# Set the ridership basis flag
total_bart_ridership["daily_ridership_basis"] = "reported_daily"

In [11]:
# Calculate average ridership per day type and stop
total_bart_ridership['daily_boardings'] = pd.to_numeric(total_bart_ridership['daily_boardings'], errors='coerce')
total_bart_ridership['daily_alightings'] = pd.to_numeric(total_bart_ridership['daily_alightings'], errors='coerce')

average_bart_ridership = compute_averages(
    df=total_bart_ridership,
    ridership_cols=["daily_boardings", "daily_alightings"],
    group_cols=["stop_id", "day_type", "stop_name"]
)

average_bart_ridership["organization_name"] = "San Francisco Bay Area Rapid Transit District"

average_bart_ridership[['start_date','end_date']] = [bart_ridership['start_date'].min(), bart_ridership['end_date'].max()]
# Remove last digit from all stop_id
average_bart_ridership['stop_id'] = average_bart_ridership['stop_id'].astype(str).str[:-1]

bart_final = standardize_columns(average_bart_ridership, master_cols)

bart_final.sample(5)

,organization_name,stop_id,stop_name,stop_lat,stop_lon,day_type,average_daily_boardings,average_daily_alightings,start_date,end_date
140,San Francisco Bay Area Rapid Transit District,90830,Antioch,None,None,Weekday,1796.249042,1791.486590,2024-10-01,2025-09-30
20,San Francisco Bay Area Rapid Transit District,90130,Powell Street,None,None,Weekday,11889.865900,10974.448276,2024-10-01,2025-09-30
76,San Francisco Bay Area Rapid Transit District,90340,Walnut Creek,None,None,Sunday,1213.846154,1233.173077,2024-10-01,2025-09-30
108,San Francisco Bay Area Rapid Transit District,90510,Castro Valley,None,None,Saturday,707.673077,705.346154,2024-10-01,2025-09-30
89,San Francisco Bay Area Rapid Transit District,90380,Pittsburg / Bay Point,None,None,Weekday,2093.160920,2212.245211,2024-10-01,2025-09-30

In [12]:
big_blue_bus_ridership.columns = big_blue_bus_ridership.columns.str.lower()
big_blue_bus_ridership['service_day'] = big_blue_bus_ridership['service_day'].str.strip().str.capitalize()


big_blue_bus_ridership = big_blue_bus_ridership.rename(columns={
    'service_day': 'day_type',
    'average_daily_boardings':'average_daily_boardings_period',
    'average_daily_alightings':'average_daily_alightings_period'    
})


# Sum boardings/alightings across directions within same stop & period
total_big_blue_bus_ridership = (
    big_blue_bus_ridership
    .groupby(['day_type',
              'stop_id','stop_name','stop_lat','stop_lon',
              'start_date','end_date'])
    .agg({
        'average_daily_boardings_period':'sum',
        'average_daily_alightings_period':'sum'
    })
    .reset_index()
)

In [13]:
big_blue_bus_ridership['start_date'] = pd.to_datetime(big_blue_bus_ridership['start_date'])
big_blue_bus_ridership['end_date'] = pd.to_datetime(big_blue_bus_ridership['end_date'])

total_big_blue_bus_ridership["n_days"] = total_big_blue_bus_ridership.apply(count_service_days, axis=1)

# Taking weighted average of the ridership across 4 different time periods
averaged_total_big_blue_bus_ridership = (
    total_big_blue_bus_ridership
    .groupby(['day_type', 'stop_name',
              'stop_id','stop_lat','stop_lon'])
    .apply(lambda x: pd.Series({
        'average_daily_boardings': np.average(x['average_daily_boardings_period'], weights=x['n_days']),
        'average_daily_alightings': np.average(x['average_daily_alightings_period'], weights=x['n_days'])
    }))
    .reset_index()
)


# Set the ridership basis flag
averaged_total_big_blue_bus_ridership["daily_ridership_basis"] = "reported_avg_daily"
averaged_total_big_blue_bus_ridership["organization_name"] = "Big Blue Bus"

averaged_total_big_blue_bus_ridership[['start_date','end_date']] = [big_blue_bus_ridership['start_date'].min(), big_blue_bus_ridership['end_date'].max()]

big_blue_bus_ridership_final = standardize_columns(averaged_total_big_blue_bus_ridership, master_cols)
big_blue_bus_ridership_final.sample(5)

/tmp/ipykernel_1171/1528211661.py:11: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: pd.Series({

,organization_name,stop_id,stop_name,stop_lat,stop_lon,day_type,average_daily_boardings,average_daily_alightings,start_date,end_date
2177,Big Blue Bus,2143,SANTA MONICA EB/CORINTH NS,34.046012,-118.449753,Weekday,56.939313,81.146642,2024-08-01,2025-11-30
1579,Big Blue Bus,2829,BLUFF CREEK WB/CAMPUS CENTER NS,33.978003,-118.405744,Weekday,7.365666,1.480008,2024-08-01,2025-11-30
1012,Big Blue Bus,1238,MONTANA EB/15TH FS,34.033090,-118.493976,Sunday,8.845697,9.185682,2024-08-01,2025-11-30
1846,Big Blue Bus,3088,MANCHESTER WB/HINDRY NS,33.960423,-118.372845,Weekday,3.141978,25.371313,2024-08-01,2025-11-30
484,Big Blue Bus,2376,PICO WB/PATRICIA NS,34.045447,-118.418801,Saturday,12.328628,13.218213,2024-08-01,2025-11-30

Caltrain Ridership data when compared with the NTD data was almost half (so it is most likely representing average ons).

In [14]:
caltrain_ridership = caltrain_ridership.rename(columns={
    'Origin Station': 'stop_name',
    'Date Type': 'day_type',
    'Average Ridership':'average_daily_boardings_period',  
})

caltrain_ridership = caltrain_ridership[
    caltrain_ridership["day_type"] != "Holiday"
]

# Getting number of days and using US Federal Holidays
start_date_caltrain = '2023-11-01'
end_date_caltrain = '2025-07-31'

#Getting all the federal holidays between the start and end date
cal = USFederalHolidayCalendar()
holidays = cal.holidays(start=start_date_caltrain, end=end_date_caltrain)

# Setting holidays to calculate the number of weekdays, saturday and sunday without holidays 
holiday_set = set(holidays)

caltrain_ridership["start_date"] = pd.to_datetime(caltrain_ridership["start_date"])
caltrain_ridership["end_date"] = pd.to_datetime(caltrain_ridership["end_date"])

caltrain_ridership["n_days"] = caltrain_ridership.apply(count_service_days_wo_holidays, axis=1)

In [15]:
# Taking weighted average of the ridership across 20 months time periods
averaged_caltrain_ridership = (
    caltrain_ridership
    .groupby(['day_type','stop_name'])
    .apply(lambda x: pd.Series({
        'average_daily_boardings': np.average(x['average_daily_boardings_period'], weights=x['n_days'])
    }))
    .reset_index()
)

# Set the ridership basis flag
averaged_caltrain_ridership["daily_ridership_basis"] = "reported_avg_daily"
averaged_caltrain_ridership["organization_name"] = "Caltrain"

averaged_caltrain_ridership[['start_date','end_date']] = [caltrain_ridership['start_date'].min(), caltrain_ridership['end_date'].max()]

caltrain_ridership_final = standardize_columns(averaged_caltrain_ridership, master_cols)

caltrain_ridership_final.sample(5)

/tmp/ipykernel_1171/3722569284.py:5: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: pd.Series({

,organization_name,stop_id,stop_name,stop_lat,stop_lon,day_type,average_daily_boardings,average_daily_alightings,start_date,end_date
59,Caltrain,None,Tamien,None,None,Sunday,43.960035,None,2023-11-01,2025-07-31
60,Caltrain,None,22nd Street,None,None,Weekday,1016.712073,None,2023-11-01,2025-07-31
15,Caltrain,None,Morgan Hill,None,None,Saturday,0.721309,None,2023-11-01,2025-07-31
17,Caltrain,None,Palo Alto,None,None,Saturday,1220.752048,None,2023-11-01,2025-07-31
62,Caltrain,None,Belmont,None,None,Weekday,543.256104,None,2023-11-01,2025-07-31

In [16]:
culver_citybus_ridership["daily_ridership_basis"] = "reported_avg_daily"



culver_citybus_ridership = culver_citybus_ridership.rename(columns={
    'Stop ID': 'stop_id',
    'Stop Name': 'stop_name',
})

group_cols = [
     "stop_id", "stop_name", "day_type", "daily_ridership_basis"]

# Sum AVG On and AVG Off
sum_culver_citybus_ridership = (culver_citybus_ridership.groupby(
    group_cols, as_index=False).agg(
        average_daily_boardings=("AVG On", "sum"),
        average_daily_alightings=("AVG Off", "sum")
    )
)

sum_culver_citybus_ridership["organization_name"] = "Culver City Bus"

sum_culver_citybus_ridership[['start_date','end_date']] = [culver_citybus_ridership['start_date'].min(), culver_citybus_ridership['end_date'].max()]

culver_citybus_final = standardize_columns(sum_culver_citybus_ridership, master_cols)

culver_citybus_final.sample(5)

,organization_name,stop_id,stop_name,stop_lat,stop_lon,day_type,average_daily_boardings,average_daily_alightings,start_date,end_date
696,Culver City Bus,658,Sepulveda Blvd/Sardis Ave,None,None,Weekday,2.5,8.0,2025-07-14,2025-08-25
804,Culver City Bus,722,Culver Blvd/Vinton Ave,None,None,Weekday,2.0,1.3,2025-07-14,2025-08-25
594,Culver City Bus,621,Sepulveda Blvd/Machado Rd,None,None,Weekday,24.6,5.5,2025-07-14,2025-08-25
61,Culver City Bus,121,Washington Blvd/Corinth Ave,None,None,Sunday,3.8,7.1,2025-07-14,2025-08-25
202,Culver City Bus,169,Washington Blvd/Redwood Ave,None,None,Sunday,7.2,21.7,2025-07-14,2025-08-25

In [17]:
# Add day_type from the date column
foothill_transit_ridership = add_day_type(foothill_transit_ridership, date_col="date")

foothill_transit_ridership = foothill_transit_ridership.rename(columns={
    'stop_code': 'stop_id',
})

# Grouping columns
group_cols = [
    "date", "stop_id", "stop_lat", "stop_lon",
    "start_date", "end_date", "day_type"
]

# Sum boardings and alightings, with explicit output names
total_ridership_foothill = (
    foothill_transit_ridership
    .groupby(group_cols, as_index=False)
    .agg(
        daily_boardings=("boardings", "sum"),
        daily_alightings=("alightings", "sum")
    )
)

# Set the ridership basis flag
total_ridership_foothill["daily_ridership_basis"] = "reported_daily"

# Calculate average ridership per day type and stop
total_ridership_foothill['daily_boardings'] = pd.to_numeric(total_ridership_foothill['daily_boardings'], errors='coerce')
total_ridership_foothill['daily_alightings'] = pd.to_numeric(total_ridership_foothill['daily_alightings'], errors='coerce')

average_foothill_ridership = compute_averages(
    df=total_ridership_foothill,
    ridership_cols=["daily_boardings", "daily_alightings"],
    group_cols=[ "stop_id", 
                "stop_lat", "stop_lon", "day_type"]
)

average_foothill_ridership["organization_name"] = "Foothill Transit"

average_foothill_ridership[['start_date','end_date']] = [foothill_transit_ridership['start_date'].min(), foothill_transit_ridership['end_date'].max()]
foothill_final = standardize_columns(average_foothill_ridership, master_cols)

foothill_final.sample(5)

,organization_name,stop_id,stop_name,stop_lat,stop_lon,day_type,average_daily_boardings,average_daily_alightings,start_date,end_date
483,Foothill Transit,689,None,34.106771,-117.823954,Weekday,27.517241,12.153257,2024-07-01,2025-06-30
4067,Foothill Transit,2979,None,33.991139,-117.941564,Sunday,1.625000,0.166667,2024-07-01,2025-06-30
4792,Foothill Transit,3523,None,34.086575,-118.016759,Sunday,7.211538,1.057692,2024-07-01,2025-06-30
2536,Foothill Transit,1894,None,34.020197,-117.866356,Weekday,3.705179,1.231076,2024-07-01,2025-06-30
430,Foothill Transit,667,None,34.106589,-117.864015,Saturday,12.576923,8.211538,2024-07-01,2025-06-30

In [18]:
# Add day_type from the date column
fresno_area_express_ridership = add_day_type(fresno_area_express_ridership, date_col="Date")

fresno_area_express_ridership["daily_ridership_basis"] = "reported_daily"


fresno_area_express_ridership = fresno_area_express_ridership.rename(columns={
    'StopID': 'stop_id',
    'StopLabel': 'stop_name',
    'ProjectedBoarding': 'daily_boardings',
    'ProjectedAlighting': 'daily_alightings'
})

# Calculate average ridership per day type and stop
fresno_area_express_ridership['daily_boardings'] = pd.to_numeric(fresno_area_express_ridership['daily_boardings'], errors='coerce')
fresno_area_express_ridership['daily_alightings'] = pd.to_numeric(fresno_area_express_ridership['daily_alightings'], errors='coerce')

average_fresno_area_express_ridership = compute_averages(
    df=fresno_area_express_ridership,
    ridership_cols=["daily_boardings", "daily_alightings"],
    group_cols=["stop_id",  "stop_name", "day_type"]
)

average_fresno_area_express_ridership["organization_name"] = "Fresno County"

average_fresno_area_express_ridership[['start_date','end_date']] = [fresno_area_express_ridership['start_date'].min(), fresno_area_express_ridership['end_date'].max()]

fresno_final = standardize_columns(average_fresno_area_express_ridership, master_cols)

fresno_final.sample(5)

,organization_name,stop_id,stop_name,stop_lat,stop_lon,day_type,average_daily_boardings,average_daily_alightings,start_date,end_date
3740,Fresno County,1720,SE HERNDON - BLYTHE,None,None,Weekday,6.284853,1.203505,2024-09-01,2025-08-31
4517,Fresno County,2362,NE FIGARDEN - BARSTOW,None,None,Saturday,1.708351,2.419478,2024-09-01,2025-08-31
4030,Fresno County,1904,NW TULARE - PEACH,None,None,Sunday,10.770343,5.248587,2024-09-01,2025-08-31
3088,Fresno County,1454,SE CEDAR - GARLAND,None,None,Sunday,3.778044,5.456788,2024-09-01,2025-08-31
1057,Fresno County,517,NW SAN PABLO - BELMONT,None,None,Saturday,4.261705,9.690404,2024-09-01,2025-08-31

In [19]:
gold_coast_transit_ridership = gold_coast_transit_ridership.rename(columns={
    'day_of_week': 'day_type',
    'lat': 'stop_lat',
    'lon': 'stop_lon'
})

group_cols = ["day_type", "stop_id", "stop_name",  "stop_lat", "stop_lon", "start_date", "end_date"]

# Sum AVG On 
total_gold_coast_transit_ridership = (gold_coast_transit_ridership.groupby(
    group_cols, as_index=False).agg(
        daily_boardings=("total_on", "sum"),
        daily_alightings=("total_off", "sum"),
    )
)

total_gold_coast_transit_ridership['start_date'] = pd.to_datetime(total_gold_coast_transit_ridership['start_date'])
total_gold_coast_transit_ridership['end_date'] = pd.to_datetime(total_gold_coast_transit_ridership['end_date'])

total_gold_coast_transit_ridership["n_days"] = total_gold_coast_transit_ridership.apply(count_service_days, axis=1)

In [20]:
# Taking weighted average of the ridership across 4 different time periods
averaged_gold_coast_transit_ridership = (
    total_gold_coast_transit_ridership
    .groupby(['day_type', 'stop_name',
              'stop_id','stop_lat','stop_lon'])
    .apply(lambda x: pd.Series({
        'average_daily_boardings': np.average(x['daily_boardings'], weights=x['n_days']),
        'average_daily_alightings': np.average(x['daily_alightings'], weights=x['n_days'])
    }))
    .reset_index()
)

averaged_gold_coast_transit_ridership["organization_name"] = "Gold Coast Transit"

averaged_gold_coast_transit_ridership[['start_date','end_date']] = [gold_coast_transit_ridership['start_date'].min(), gold_coast_transit_ridership['end_date'].max()]
golden_coast_transit_final = standardize_columns(averaged_gold_coast_transit_ridership, master_cols)

golden_coast_transit_final.sample(5)

/tmp/ipykernel_1171/1215055102.py:6: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: pd.Series({

,organization_name,stop_id,stop_name,stop_lat,stop_lon,day_type,average_daily_boardings,average_daily_alightings,start_date,end_date
19,Gold Coast Transit,5THFST1,5th & F,34.197808,-119.184779,Weekday,23.0,6.0,2025-05-01,2025-05-31
72,Gold Coast Transit,CST9TH2,C & 9th,34.192240,-119.181110,Weekday,21.0,38.0,2025-05-01,2025-05-31
627,Gold Coast Transit,VIOLLA2,Violeta & LA Ave,34.284324,-119.148805,Weekday,7.0,9.0,2025-05-01,2025-05-31
408,Gold Coast Transit,SUROCE1,Surfside & Oceanview,34.142699,-119.192046,Weekday,7.0,11.0,2025-05-01,2025-05-31
524,Gold Coast Transit,VNABRO1,Ventura Ave & Brooks,34.338892,-119.293959,Weekday,0.0,0.0,2025-05-01,2025-05-31

In [21]:
# Add day_type from the date column
golden_gate_park_shuttle_ridership = add_day_type(golden_gate_park_shuttle_ridership, date_col="Date")

group_cols = [
    "Date", "day_type", "Stop", "Stop ID", "start_date", "end_date"]

# Sum AVG On 
total_golden_gate_park_shuttle_ridership = (golden_gate_park_shuttle_ridership.groupby(
    group_cols, as_index=False).agg(
        daily_boardings=("Ridership", "sum"),
    )
)

total_golden_gate_park_shuttle_ridership["daily_ridership_basis"] = "reported_daily"

total_golden_gate_park_shuttle_ridership = total_golden_gate_park_shuttle_ridership.rename(columns={
    'Stop': 'stop_name',
    'Date': 'date',
    'Stop ID': 'stop_id'
})

# Calculate average ridership per day type and stop
total_golden_gate_park_shuttle_ridership['daily_boardings'] = pd.to_numeric(total_golden_gate_park_shuttle_ridership['daily_boardings'], errors='coerce')
average_golden_gate_park_shuttle_ridership = compute_averages(
    df=total_golden_gate_park_shuttle_ridership,
    ridership_cols=["daily_boardings"],
    group_cols=["stop_name", "day_type", "stop_id"]
)


average_golden_gate_park_shuttle_ridership["organization_name"] = "Golden Gate Park Shuttle"

average_golden_gate_park_shuttle_ridership[['start_date','end_date']] = [golden_gate_park_shuttle_ridership['start_date'].min(), 
                                                                         golden_gate_park_shuttle_ridership['end_date'].max()]
golden_gate_parkshuttle_final = standardize_columns(average_golden_gate_park_shuttle_ridership, master_cols)

golden_gate_parkshuttle_final.sample(5)

,organization_name,stop_id,stop_name,stop_lat,stop_lon,day_type,average_daily_boardings,average_daily_alightings,start_date,end_date
28,Golden Gate Park Shuttle,7618,Haight/Stanyan,None,None,Sunday,13.942308,None,2024-07-01,2025-06-30
7,Golden Gate Park Shuttle,7611,8th Ave EB,None,None,Sunday,10.980769,None,2024-07-01,2025-06-30
3,Golden Gate Park Shuttle,7608,10th Ave/ De Young WB,None,None,Saturday,9.519231,None,2024-07-01,2025-06-30
27,Golden Gate Park Shuttle,7618,Haight/Stanyan,None,None,Saturday,16.403846,None,2024-07-01,2025-06-30
42,Golden Gate Park Shuttle,7603,Rose Garden WB,None,None,Saturday,11.346154,None,2024-07-01,2025-06-30

In [22]:
# Add day_type from the date column
golden_gate_transit_ridership = add_day_type(golden_gate_transit_ridership, date_col="date")

golden_gate_transit_ridership = golden_gate_transit_ridership.rename(columns={
    'STOP_NUMBER': 'stop_id',
    'STOP_NAME': 'stop_name',
})

# Remove everything in parentheses (including the parentheses) at the end of the string
golden_gate_transit_ridership['stop_name'] = golden_gate_transit_ridership['stop_name'].str.replace(r'\s*\(.*\)$', '', regex=True)

group_cols = [
    "day_type", "stop_id", "stop_name", "end_date", "start_date"]

# Sum AVG On and AVG Off
total_golden_gate_transit_ridership = (golden_gate_transit_ridership.groupby(
    group_cols, as_index=False).agg(
        daily_boardings=("BOARDINGS", "sum"),
        daily_alightings=("ALIGHTINGS", "sum")
    )
)

total_golden_gate_transit_ridership["daily_ridership_basis"] = "reported_daily"

# Calculate average ridership per day type and stop
total_golden_gate_transit_ridership['daily_boardings'] = pd.to_numeric(total_golden_gate_transit_ridership['daily_boardings'], errors='coerce')
total_golden_gate_transit_ridership['daily_alightings'] = pd.to_numeric(total_golden_gate_transit_ridership['daily_alightings'], errors='coerce')

average_golden_gate_transit_ridership = compute_averages(
    df=total_golden_gate_transit_ridership,
    ridership_cols=["daily_boardings", "daily_alightings"],
    group_cols=["stop_id", "stop_name", "day_type"]
)

average_golden_gate_transit_ridership["organization_name"] = "Golden Gate Transit"
average_golden_gate_transit_ridership[['start_date','end_date']] = [golden_gate_transit_ridership['start_date'].min(), 
                                                                         golden_gate_transit_ridership['end_date'].max()]

golden_gate_transit_final = standardize_columns(average_golden_gate_transit_ridership, master_cols)

golden_gate_transit_final.sample(5)

,organization_name,stop_id,stop_name,stop_lat,stop_lon,day_type,average_daily_boardings,average_daily_alightings,start_date,end_date
35,Golden Gate Transit,40032,Van Ness Ave & Union St,None,None,Weekday,49.045455,25.772727,2025-09-01,2025-09-30
256,Golden Gate Transit,40457,Canal St & Novato St,None,None,Sunday,8.750000,0.750000,2025-09-01,2025-09-30
369,Golden Gate Transit,40910,Old Redwood Hwy & George St,None,None,Sunday,0.250000,0.000000,2025-09-01,2025-09-30
139,Golden Gate Transit,40110,Spencer Ave Bus Pad,None,None,Saturday,7.750000,2.500000,2025-09-01,2025-09-30
660,Golden Gate Transit,80015,VTP 580 WB @ Toll Plaza,None,None,Sunday,0.000000,0.000000,2025-09-01,2025-09-30

In [23]:
long_beach_transit_ridership["daily_ridership_basis"] = "reported_avg_daily"

group_cols = [
    "DayType", "StopID", "StopName", "end_date", "start_date", "daily_ridership_basis"]

# Sum AVG On and AVG Off
total_long_beach_transit_ridership = (long_beach_transit_ridership.groupby(
    group_cols, as_index=False).agg(
        average_daily_boardings=("Boardings", "sum"),
        average_daily_alightings=("Alightings", "sum")
    )
)

total_long_beach_transit_ridership = total_long_beach_transit_ridership.rename(columns={
    'StopID': 'stop_id',
    'StopName': 'stop_name',
    'DayType': 'day_type',
})

total_long_beach_transit_ridership["organization_name"] = "Long Beach Transit"

total_long_beach_transit_ridership[['start_date','end_date']] = [long_beach_transit_ridership['start_date'].min(), 
                                                                         long_beach_transit_ridership['end_date'].max()]

long_beach_transit_final = standardize_columns(total_long_beach_transit_ridership, master_cols)

long_beach_transit_final.sample(5)

,organization_name,stop_id,stop_name,stop_lat,stop_lon,day_type,average_daily_boardings,average_daily_alightings,start_date,end_date
4575,Long Beach Transit,1356,Kilroy Airport Way & Redondo SE,None,None,Weekday,1.257745,1.257108,2024-07-01,2025-06-30
4347,Long Beach Transit,1061,Bellflower & Flower NE,None,None,Weekday,5.286874,44.828947,2024-07-01,2025-06-30
2758,Long Beach Transit,1353,Willow & Grand NW,None,None,Sunday,5.985782,2.131693,2024-07-01,2025-06-30
661,Long Beach Transit,834,Orange & San Antonio NE,None,None,Saturday,3.192793,7.976190,2024-07-01,2025-06-30
2359,Long Beach Transit,649,Garfield at Richfield SW,None,None,Sunday,0.000000,0.092157,2024-07-01,2025-06-30

In [24]:
octa_ridership = octa_ridership.rename(columns={
    'Stop ID': 'stop_id',
    'Stop Name': 'stop_name',

})

octa_ridership["stop_name"] = octa_ridership["stop_name"].str.split("-", n=1).str[1]

group_cols = [
    "day_type", "stop_id", "stop_name", "end_date", "start_date"]

# Sum AVG On and AVG Off
octa_ridership_sum = (octa_ridership.groupby(
    group_cols, as_index=False).agg(
        average_daily_boardings=("APC Boarding", "sum"),
        average_daily_alightings=("APC Alighting", "sum")
    )
)

octa_ridership_sum.loc[
    octa_ridership_sum['day_type'].str.strip().str.lower() == "weekday",
    'day_type'
] = "Weekday"

octa_ridership_sum["organization_name"] = "Orange County Transportation Authority"

octa_ridership_sum[['start_date','end_date']] = [octa_ridership['start_date'].min(), 
                                                                         octa_ridership['end_date'].max()]

octa_final = standardize_columns(octa_ridership_sum, master_cols)

octa_final.sample(5)

,organization_name,stop_id,stop_name,stop_lat,stop_lon,day_type,average_daily_boardings,average_daily_alightings,start_date,end_date
3794,Orange County Transportation Authority,6304,FLOWER-MCFADDEN,None,None,Weekday,5,17,2025-02-04,2025-02-04
2644,Orange County Transportation Authority,4394,WHITTIER-EUCLID,None,None,Weekday,4,0,2025-02-04,2025-02-04
2636,Orange County Transportation Authority,4377,LA HABRA-WALNUT,None,None,Weekday,3,13,2025-02-04,2025-02-04
1619,Orange County Transportation Authority,2458,MAGNOLIA-HEALEY,None,None,Weekday,1,0,2025-02-04,2025-02-04
3888,Orange County Transportation Authority,6415,HARBOR-WASHINGTON,None,None,Weekday,12,20,2025-02-04,2025-02-04

In [25]:
omni_trans_ridership= omni_trans_ridership.rename(columns={
    'Stop Name': 'stop_name',
    'avg_boardings': 'average_daily_boardings',
    'avg_alightings': 'average_daily_alightings',
    'Stop Id': 'stop_id'
})

omni_trans_ridership["organization_name"] = "Omnitrans"

omni_trans_ridership_filtered = omni_trans_ridership[['stop_name', 'stop_id',  'average_daily_boardings', 'average_daily_alightings', 'organization_name', 'day_type']]

omni_trans_ridership_filtered['stop_id'] = omni_trans_ridership_filtered['stop_id'].apply(
    lambda x: None if pd.isna(x) else int(x)
)

omni_trans_ridership_filtered[['start_date','end_date']] = [omni_trans_ridership['start_date'].min(), 
                                                                         omni_trans_ridership['end_date'].max()]
omni_final = standardize_columns(omni_trans_ridership_filtered, master_cols)

omni_final.sample(5)

/tmp/ipykernel_1171/3069775595.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  omni_trans_ridership_filtered['stop_id'] = omni_trans_ridership_filtered['stop_id'].apply(
/tmp/ipykernel_1171/3069775595.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  omni_trans_ridership_filtered[['start_date','end_date']] = [omni_trans_ridership['start_date'].min(),
/tmp/ipykernel_1171/3069775595.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  omni_trans_ridership_filtered[['start_date','end_date']] = [omni_trans_ridership['start_date'].min(),
/tmp/ipykernel_1171/392318389.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = None
/tmp/ipykernel_1171/392318389.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = None

,organization_name,stop_id,stop_name,stop_lat,stop_lon,day_type,average_daily_boardings,average_daily_alightings,start_date,end_date
2365,Omnitrans,5119.0,LA CADENA @ N ST,None,None,all,2.295890,1.621918,2023-07-01,2026-06-30
2167,Omnitrans,8758.0,Fontana Metrolink Transit Center,None,None,all,213.967123,207.843836,2023-07-01,2026-06-30
4613,Omnitrans,6318.0,Central @ Phillips,None,None,all,1.126027,1.150685,2023-07-01,2026-06-30
2375,Omnitrans,7717.0,Marygold @ Kempster,None,None,all,3.402740,3.868493,2023-07-01,2026-06-30
2492,Omnitrans,133.0,Riverside @ Foothill,None,None,all,40.073973,42.400000,2023-07-01,2026-06-30

Riverside Transit Ridership report ridership data not ons and offs seperately. Provides comparable data with NTD ridership, hence dividing the ridership by 2 to get average ons before analysis.

In [26]:
riverside_transit_ridership = add_day_type(riverside_transit_ridership, date_col='date')


riverside_transit_ridership['ons'] = (
    riverside_transit_ridership['ridership'] / 2
)


group_cols = [
    "date", "Stop ID", "start_date", 
    "end_date", "day_type"]

# Sum AVG On and AVG Off
total_riverside_transit_ridership = (riverside_transit_ridership.groupby(
    group_cols, as_index=False).agg(
    daily_boardings = ('ons', 'sum'))
)

total_riverside_transit_ridership = total_riverside_transit_ridership.rename(columns={
    'Stop ID': 'stop_id'

})

In [27]:
total_riverside_transit_ridership["daily_ridership_basis"] = "reported_daily"

# Calculate average ridership per day type and stop
total_riverside_transit_ridership['daily_boardings'] = pd.to_numeric(total_riverside_transit_ridership['daily_boardings'], errors='coerce')
average_riverside_transit_ridership = compute_averages(
    df=total_riverside_transit_ridership,
    ridership_cols=["daily_boardings"],
    group_cols=["stop_id", "day_type"]
)

average_riverside_transit_ridership["organization_name"] = "Riverside Transit"

average_riverside_transit_ridership[['start_date','end_date']] = [riverside_transit_ridership['start_date'].min(), 
                                                                         riverside_transit_ridership['end_date'].max()]

riverside_final = standardize_columns(average_riverside_transit_ridership, master_cols)

riverside_final.sample(5)

,organization_name,stop_id,stop_name,stop_lat,stop_lon,day_type,average_daily_boardings,average_daily_alightings,start_date,end_date
4999,Riverside Transit,3163,None,None,None,Weekday,1.161972,None,2025-01-01,2025-10-31
2980,Riverside Transit,2167,None,None,None,Sunday,0.910714,None,2025-01-01,2025-10-31
1102,Riverside Transit,1428,None,None,None,Sunday,0.781250,None,2025-01-01,2025-10-31
5585,Riverside Transit,3472,None,None,None,Saturday,1.655172,None,2025-01-01,2025-10-31
169,Riverside Transit,1071,None,None,None,Saturday,25.513889,None,2025-01-01,2025-10-31

In [28]:
group_cols = [
    "stop_id", "stop_lat", "stop_lon", "stop_name", "day_type"]

# Combining across directions
sacrt_bus_ridership_sum = (sacrt_bus_ridership.groupby(
    group_cols, as_index=False).agg(
        average_daily_boardings=("average_boardings", "sum"),
        average_daily_alightings=("average_alightings", "sum")
    )
)

sacrt_bus_ridership_sum.loc[
    sacrt_bus_ridership_sum['day_type'].str.strip().str.lower() == "weekday",
    'day_type'
] = "Weekday"

# Replace day_type
sacrt_bus_ridership_sum["day_type"] = sacrt_bus_ridership_sum["day_type"].replace("daily", "all")

sacrt_bus_ridership_sum["organization_name"] = "SacRT Bus"

sacrt_bus_ridership_sum[['start_date','end_date']] = [sacrt_bus_ridership['start_date'].min(), 
                                                                         sacrt_bus_ridership['end_date'].max()]

sacrt_bus_final = standardize_columns(sacrt_bus_ridership_sum, master_cols)

sacrt_bus_final.sample(5)

,organization_name,stop_id,stop_name,stop_lat,stop_lon,day_type,average_daily_boardings,average_daily_alightings,start_date,end_date
723,SacRT Bus,1013,GREENHAVEN DR & PARK RANCH WAY (SB),38.497456,-121.523254,Weekday,0,0,2023-09-01,2023-12-31
3008,SacRT Bus,11120,IRON POINT RD & MCADOO DR (WB),38.647964,-121.150467,Weekday,0,1,2023-09-01,2023-12-31
1477,SacRT Bus,1908,BROADWAY & 39TH ST (WB),38.547085,-121.463600,all,23,23,2023-09-01,2023-12-31
427,SacRT Bus,596,DEL PASO BLVD & WINNIPEG ST (SB),38.608800,-121.453815,all,1,4,2023-09-01,2023-12-31
634,SacRT Bus,923,59TH ST & TAHOE WAY (NB),38.548823,-121.436472,Weekday,0,0,2023-09-01,2023-12-31

In [29]:
samtrans_ridership = add_day_type(samtrans_ridership, date_col='APC Date')

samtrans_ridership = samtrans_ridership.rename(columns={
    'Stop ID': 'stop_id',
    'Stop Name': 'stop_name',
    'Lat': 'stop_lat',
    'Lon': 'stop_lon',
    'APC Date': 'date',
    'Ons': 'daily_boardings',
    'Offs': 'daily_alightings',
})

samtrans_ridership["daily_ridership_basis"] = "reported_daily"

# Calculate average ridership per day type and stop
samtrans_ridership['daily_boardings'] = pd.to_numeric(samtrans_ridership['daily_boardings'], errors='coerce')
samtrans_ridership['daily_alightings'] = pd.to_numeric(samtrans_ridership['daily_alightings'], errors='coerce')

average_samtrans_ridership = compute_averages(
    df=samtrans_ridership,
    ridership_cols=["daily_boardings", "daily_alightings"],
    group_cols=["stop_id", "stop_name", "stop_lat", "stop_lon", "day_type"]
)

average_samtrans_ridership["organization_name"] = "Samtrans"

average_samtrans_ridership[['start_date','end_date']] = [samtrans_ridership['start_date'].min(), 
                                                                         samtrans_ridership['end_date'].max()]

samtrans_final = standardize_columns(average_samtrans_ridership, master_cols)

samtrans_final.sample(5)

,organization_name,stop_id,stop_name,stop_lat,stop_lon,day_type,average_daily_boardings,average_daily_alightings,start_date,end_date
4061,Samtrans,363001,Bay Rd & University Ave-Fordam St,37.471837,-122.137023,Sunday,7.4,2.6,2025-08-01,2025-08-31
2037,Samtrans,335504,585 McDonnell Rd-UAL Cargo,37.615859,-122.394355,Saturday,17.6,2.6,2025-08-01,2025-08-31
1485,Samtrans,334021,Armour Ave & Linden Ave,37.661857,-122.406715,Sunday,7.1,0.1,2025-08-01,2025-08-31
2670,Samtrans,341555,N Delaware St & Monte Diablo Ave,37.573062,-122.325592,Saturday,27.0,13.4,2025-08-01,2025-08-31
2151,Samtrans,336027,El Camino Real & Center St-Millbrae,37.608333,-122.398162,Saturday,41.0,43.4,2025-08-01,2025-08-31

In [30]:
group_cols = [
    "Stop ID",  "Stop Name", "day_type", "start_date", 
    "end_date"]

# Sum AVG On and AVG Off
total_sdmts_ridership = (sdmts_ridership.groupby(
    group_cols, as_index=False).agg(
        average_daily_boardings=("Average On", "sum"),
        average_daily_alightings=("Average Off", "sum")
    )
)


total_sdmts_ridership = total_sdmts_ridership.rename(columns={
    'Stop ID': 'stop_id',
    'Stop Name': 'stop_name',
})

total_sdmts_ridership["daily_ridership_basis"] = "reported_avg_daily"

total_sdmts_ridership["organization_name"] = "SDMTS"

total_sdmts_ridership[['start_date','end_date']] = [sdmts_ridership['start_date'].min(), 
                                                                         sdmts_ridership['end_date'].max()]

sdmts_final = standardize_columns(total_sdmts_ridership, master_cols)

sdmts_final.sample(5)

,organization_name,stop_id,stop_name,stop_lat,stop_lon,day_type,average_daily_boardings,average_daily_alightings,start_date,end_date
6453,SDMTS,40364,Broadway & Buena Vista Av,None,None,Saturday,26.163599,13.286172,2024-09-01,2025-01-25
3580,SDMTS,12202,Carmel Mountain Rd & Camino Del Norte,None,None,Sunday,5.028645,1.104914,2024-09-01,2025-01-25
8404,SDMTS,60427,Oro Vista Rd & 1575,None,None,Sunday,14.324633,2.826824,2024-09-01,2025-01-25
7671,SDMTS,50180,Euclid Av & 18th St,None,None,Sunday,15.529529,28.402163,2024-09-01,2025-01-25
5761,SDMTS,30367,Hilltop Dr & L St,None,None,Weekday,13.268613,15.576557,2024-09-01,2025-01-25

In [31]:
santa_cruz_metro_ridership = santa_cruz_metro_ridership.rename(columns={
    'Stop ID': 'stop_id',
    'Stop Name': 'stop_name',
    'Boardings': 'average_daily_boardings',
    'Alightings': 'average_daily_alightings'    
})

santa_cruz_metro_ridership["organization_name"] = "Santa Cruz Metro"

santa_cruz_metro_ridership[['start_date','end_date']] = [santa_cruz_metro_ridership['start_date'].min(), 
                                                                         santa_cruz_metro_ridership['end_date'].max()]

santa_cruz_final = standardize_columns(santa_cruz_metro_ridership, master_cols)

santa_cruz_final.sample(5)

,organization_name,stop_id,stop_name,stop_lat,stop_lon,day_type,average_daily_boardings,average_daily_alightings,start_date,end_date
41,Santa Cruz Metro,1005,Airport Blvd + Holm Rd,None,None,all,10.917808,10.945205,2024-07-01,2025-06-30
642,Santa Cruz Metro,1183,Shady Oaks Dr + Jeanette Way,None,None,all,0.178082,0.356164,2024-07-01,2025-06-30
358,Santa Cruz Metro,1106,Green Valley Rd + Minto Rd,None,None,all,1.778082,5.142466,2024-07-01,2025-06-30
217,Santa Cruz Metro,2725,E Lake + Bridge,None,None,all,2.419178,3.528767,2024-07-01,2025-06-30
447,Santa Cruz Metro,1569,Hwy 9 + Sylvan Ave,None,None,all,1.663014,0.843836,2024-07-01,2025-06-30

In [32]:
sbmtd_ridership = sbmtd_ridership.rename(columns={
    'Stop ID': 'stop_id',
    'Stop Name': 'stop_name',
    'avg_boardings': 'daily_boardings',
    'avg_ridership': 'daily_alightings'    
})


sbmtd_ridership["n_days"] = sbmtd_ridership.apply(count_service_days, axis=1)

# Taking weighted average of the ridership across 12 months
averaged_sbmtd_ridership = (
    sbmtd_ridership
    .groupby(['stop_id', 'stop_name', 'day_type'])
    .apply(lambda x: pd.Series({
        'average_daily_boardings': np.average(x['Ridership by Stop_Boardings'], weights=x['n_days']),
        'average_daily_alightings': np.average(x['Ridership by Stop_Alightings'], weights=x['n_days'])
    }))
    .reset_index()
)



averaged_sbmtd_ridership["organization_name"] = "SBMTD"

averaged_sbmtd_ridership[['start_date','end_date']] = [sbmtd_ridership['start_date'].min(), 
                                                                         sbmtd_ridership['end_date'].max()]

sbmtd_final = standardize_columns(averaged_sbmtd_ridership, master_cols)

sbmtd_final.sample(5)

/tmp/ipykernel_1171/1734702637.py:15: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: pd.Series({

,organization_name,stop_id,stop_name,stop_lat,stop_lon,day_type,average_daily_boardings,average_daily_alightings,start_date,end_date
544,SBMTD,668,Palermo & Portofino,None,None,all,0.000000,2.413699,2024-11-01,2025-10-31
107,SBMTD,123,State & Arrellaga,None,None,all,600.813699,214.802740,2024-11-01,2025-10-31
43,SBMTD,56,State & Broadmoor,None,None,all,581.863014,876.663014,2024-11-01,2025-10-31
363,SBMTD,439,Bath & Pueblo,None,None,all,117.221918,436.756164,2024-11-01,2025-10-31
75,SBMTD,91,Cliff & Oceano,None,None,all,392.660274,490.479452,2024-11-01,2025-10-31

In [33]:
burbank_ridership = burbank_ridership.rename(columns={
    'Organization Name ': 'organization_name',
    'StopName': 'stop_name',
    'Arrive': 'start_date', 
})


burbank_ridership['start_date'] = pd.to_datetime(
    burbank_ridership['start_date'], errors='coerce'
).dt.date

burbank_ridership['end_date'] = burbank_ridership['start_date']
burbank_ridership['end_date'] = pd.to_datetime(burbank_ridership['end_date'], errors='coerce')

burbank_ridership = add_day_type(burbank_ridership, date_col='start_date')

group_cols = [
    "day_type", "stop_name", "end_date", "start_date", "organization_name"]


# Sum AVG On and AVG Off
total_burbank_ridership = (burbank_ridership.groupby(
    group_cols, as_index=False).agg(
        daily_boardings=("Ons", "sum"),
        daily_alightings=("Offs", "sum")
    )
)

# Calculate average ridership per day type and stop
total_burbank_ridership['daily_boardings'] = pd.to_numeric(total_burbank_ridership['daily_boardings'], errors='coerce')
total_burbank_ridership['daily_alightings'] = pd.to_numeric(total_burbank_ridership['daily_alightings'], errors='coerce')

average_burbank_ridership = compute_averages(
    df=total_burbank_ridership,
    ridership_cols=["daily_boardings", "daily_alightings"],
    group_cols=["organization_name", "stop_name", "day_type"]
)

average_burbank_ridership[['start_date','end_date']] = [burbank_ridership['start_date'].min(), 
                                                                         burbank_ridership['end_date'].max()]
burbank_ridership_final = standardize_columns(average_burbank_ridership, master_cols)
burbank_ridership_final.sample(5)

,organization_name,stop_id,stop_name,stop_lat,stop_lon,day_type,average_daily_boardings,average_daily_alightings,start_date,end_date
24,City of Burbank,None,Hollywood & Victory,None,None,Weekday,1.590909,0.863636,2024-05-01,2024-05-31
31,City of Burbank,None,Olive & Joslyn Center,None,None,Weekday,7.000000,1.636364,2024-05-01,2024-05-31
16,City of Burbank,None,Empire & Buena Vista,None,None,Weekday,2.772727,5.000000,2024-05-01,2024-05-31
23,City of Burbank,None,Hollywood & Valhalla,None,None,Weekday,1.000000,0.818182,2024-05-01,2024-05-31
43,City of Burbank,None,Riverside & Pass,None,None,Weekday,13.545455,17.454545,2024-05-01,2024-05-31

In [34]:
all_ridership = pd.concat([
    bart_final,
    big_blue_bus_ridership_final,
    burbank_ridership_final,
    caltrain_ridership_final,
    culver_citybus_final,
    foothill_final,
    fresno_final,
    golden_coast_transit_final,
    golden_gate_parkshuttle_final,
    golden_gate_transit_final,
    long_beach_transit_final,
    octa_final,
    omni_final,
    riverside_final,
    sacrt_bus_final,
    samtrans_final,
    sdmts_final,
    santa_cruz_final,
    sbmtd_final,
], ignore_index=True)

/tmp/ipykernel_1171/2699512867.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  all_ridership = pd.concat([

In [35]:
all_ridership.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55566 entries, 0 to 55565
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   organization_name         55566 non-null  object
 1   stop_id                   55111 non-null  object
 2   stop_name                 44346 non-null  object
 3   stop_lat                  15342 non-null  float64
 4   stop_lon                  15342 non-null  float64
 5   day_type                  55566 non-null  object
 6   average_daily_boardings   55566 non-null  float64
 7   average_daily_alightings  49184 non-null  float64
 8   start_date                55566 non-null  datetime64[ns]
 9   end_date                  55566 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(4), object(4)
memory usage: 4.2+ MB

In [36]:
all_ridership.to_csv(f"{GCS_FILE_PATH}/AHSC_2026/ridership_all.csv", index=False)