# Weekend- Saturday and Sunday Ridership and Stop Data Cleaning, Standardization, and Integration Pipeline

This script prepares and integrates transit ridership data with stop-level data by cleaning inconsistencies, applying agency-specific fixes, and merging datasets using appropriate matching strategies.

**Summary**
- Load & filter data: Ridership data is standardized and filtered to weekend; stop data is aligned with consistent agency names.
- Clean data: Fixes inconsistencies in route_id, stop_id, and stop_code across agencies to improve matching.
- Split by strategy: Agencies are grouped based on how they can be matched (stop_id, stop_code, or stop_name).
- Merge datasets: Each group is merged with stop data, keeping only successful matches.
- Combine results: All matched data is concatenated into a final dataset linking weekend ridership with stops and routes.

In [1]:
pip install shared_utils

Requirement already satisfied: shared_utils in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (5.0.1)
Requirement already satisfied: altair-transform==0.2.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from shared_utils) (0.2.0)
Requirement already satisfied: altair==6.0.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from shared_utils) (6.0.0)
Requirement already satisfied: branca>=0.7.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from shared_utils) (0.8.2)
Requirement already satisfied: calitp-data-analysis in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from shared_utils) (2026.4.0)
Requirement already satisfied: dask-geopandas>=0.5.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from shared_utils) (0.5.0)
Requirement already satisfied: dask<2025.4.0,>=2024.10.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from shared_utils) (2025.3.1)
Requirement already satisfied: folium<0.21.0,>=0.20.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from shared_utils) (0.20.0)
Requirement already satisfied: gcsfs==2024.5.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from shared_utils) (2024.5.0)
Requirement already satisfied: great-tables==0.20.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from shared_utils) (0.20.0)
Requirement already satisfied: gt-extras==0.0.8 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from shared_utils) (0.0.8)
Requirement already satisfied: intake-geopandas>=0.3.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from shared_utils) (0.4.0)
Requirement already satisfied: intake==0.6.4 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from shared_utils) (0.6.4)
Requirement already satisfied: itables==2.7.3 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from shared_utils) (2.7.3)
Requirement already satisfied: loguru<0.7,>=0.6.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from shared_utils) (0.6.0)
Requirement already satisfied: mapclassify<3,>=2.8.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from shared_utils) (2.10.0)
Requirement already satisfied: matplotlib<4.0.0,>=3.10.5 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from shared_utils) (3.10.8)
Requirement already satisfied: movingpandas==0.22.4 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from shared_utils) (0.22.4)
Requirement already satisfied: numba<0.63.0,>=0.62.1 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from shared_utils) (0.62.1)
Requirement already satisfied: numpy<2.0.0,>=1.26.4 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from shared_utils) (1.26.4)
Requirement already satisfied: omegaconf==2.3.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from shared_utils) (2.3.0)
Requirement already satisfied: openpyxl>=3.1.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from shared_utils) (3.1.5)
Requirement already satisfied: polars==1.22.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from shared_utils) (1.22.0)
Requirement already satisfied: python-slugify>=8.0.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from shared_utils) (8.0.4)
Requirement already satisfied: pyyaml>=6.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from shared_utils) (6.0.3)
Requirement already satisfied: quarto-cli==1.6.40 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from shared_utils) (1.6.40)
Requirement already satisfied: quarto==0.1.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from shared_utils) (0.1.0)
Requirement already satisfied: scipy>=1.11.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from shared_utils) (1.17.1)
Requirement already satisfied: seaborn<0.12.0,>=0.11.2 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from shared_utils) (0.11.2)
Requirement already satisfied: stonesoup==1.8 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from shared_utils) (1.8)
Requirement already satisfied: tqdm>=4.66.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from shared_utils) (4.67.3)
Requirement already satisfied: vegafusion==2.0.3 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from shared_utils) (2.0.3)
Requirement already satisfied: vl-convert-python>=1.6.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from shared_utils) (1.9.0.post1)
Requirement already satisfied: xmltodict<0.14,>=0.13.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from shared_utils) (0.13.0)
Requirement already satisfied: jinja2 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from altair==6.0.0->shared_utils) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from altair==6.0.0->shared_utils) (4.26.0)
Requirement already satisfied: narwhals>=1.27.1 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from altair==6.0.0->shared_utils) (2.18.0)
Requirement already satisfied: packaging in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from altair==6.0.0->shared_utils) (26.0)
Requirement already satisfied: typing-extensions>=4.12.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from altair==6.0.0->shared_utils) (4.15.0)
Requirement already satisfied: ply in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from altair-transform==0.2.0->shared_utils) (3.11)
Requirement already satisfied: pandas in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from altair-transform==0.2.0->shared_utils) (2.3.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from gcsfs==2024.5.0->shared_utils) (3.13.3)
Requirement already satisfied: decorator>4.1.2 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from gcsfs==2024.5.0->shared_utils) (5.2.1)
Requirement already satisfied: fsspec==2024.5.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from gcsfs==2024.5.0->shared_utils) (2024.5.0)
Requirement already satisfied: google-auth>=1.2 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from gcsfs==2024.5.0->shared_utils) (2.49.0)
Requirement already satisfied: google-auth-oauthlib in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from gcsfs==2024.5.0->shared_utils) (1.3.0)
Requirement already satisfied: google-cloud-storage in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from gcsfs==2024.5.0->shared_utils) (3.9.0)
Requirement already satisfied: requests in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from gcsfs==2024.5.0->shared_utils) (2.32.5)
Requirement already satisfied: commonmark>=0.9.1 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from great-tables==0.20.0->shared_utils) (0.9.1)
Requirement already satisfied: faicons>=0.2.2 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from great-tables==0.20.0->shared_utils) (0.2.2)
Requirement already satisfied: htmltools>=0.4.1 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from great-tables==0.20.0->shared_utils) (0.6.0)
Requirement already satisfied: importlib-metadata in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from great-tables==0.20.0->shared_utils) (8.7.1)
Requirement already satisfied: Babel>=2.13.1 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from great-tables==0.20.0->shared_utils) (2.18.0)
Requirement already satisfied: importlib-resources in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from great-tables==0.20.0->shared_utils) (6.5.2)
Requirement already satisfied: svg-py>=1.6.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from gt-extras==0.0.8->shared_utils) (1.10.0)
Requirement already satisfied: appdirs in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from intake==0.6.4->shared_utils) (1.4.4)
Requirement already satisfied: entrypoints in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from intake==0.6.4->shared_utils) (0.4)
Requirement already satisfied: geopandas in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from movingpandas==0.22.4->shared_utils) (0.14.4)
Requirement already satisfied: geopy in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from movingpandas==0.22.4->shared_utils) (2.4.1)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from omegaconf==2.3.0->shared_utils) (4.9.3)
Requirement already satisfied: jupyter-core in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from quarto==0.1.0->shared_utils) (5.9.1)
Requirement already satisfied: nbformat in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from quarto==0.1.0->shared_utils) (5.10.4)
Requirement already satisfied: nbclient in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from quarto==0.1.0->shared_utils) (0.10.4)
Requirement already satisfied: ipykernel in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from quarto==0.1.0->shared_utils) (7.2.0)
Requirement already satisfied: jupyter in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from quarto-cli==1.6.40->shared_utils) (1.1.1)
Requirement already satisfied: wheel in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from quarto-cli==1.6.40->shared_utils) (0.46.3)
Requirement already satisfied: ordered-set in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from stonesoup==1.8->shared_utils) (4.1.0)
Requirement already satisfied: plotly>=5.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from stonesoup==1.8->shared_utils) (6.6.0)
Requirement already satisfied: pymap3d in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from stonesoup==1.8->shared_utils) (3.2.0)
Requirement already satisfied: rtree in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from stonesoup==1.8->shared_utils) (1.4.1)
Requirement already satisfied: ruamel.yaml>=0.16.5 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from stonesoup==1.8->shared_utils) (0.19.1)
Requirement already satisfied: utm in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from stonesoup==1.8->shared_utils) (0.8.1)
Requirement already satisfied: arro3-core in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from vegafusion==2.0.3->shared_utils) (0.8.0)
Requirement already satisfied: click>=8.1 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from dask<2025.4.0,>=2024.10.0->shared_utils) (8.3.1)
Requirement already satisfied: cloudpickle>=3.0.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from dask<2025.4.0,>=2024.10.0->shared_utils) (3.1.2)
Requirement already satisfied: partd>=1.4.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from dask<2025.4.0,>=2024.10.0->shared_utils) (1.4.2)
Requirement already satisfied: toolz>=0.10.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from dask<2025.4.0,>=2024.10.0->shared_utils) (1.1.0)
Requirement already satisfied: xyzservices in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from folium<0.21.0,>=0.20.0->shared_utils) (2025.11.0)
Requirement already satisfied: networkx>=3.2 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from mapclassify<3,>=2.8.0->shared_utils) (3.6.1)
Requirement already satisfied: scikit-learn>=1.4 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from mapclassify<3,>=2.8.0->shared_utils) (1.8.0)
Requirement already satisfied: contourpy>=1.0.1 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from matplotlib<4.0.0,>=3.10.5->shared_utils) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from matplotlib<4.0.0,>=3.10.5->shared_utils) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from matplotlib<4.0.0,>=3.10.5->shared_utils) (4.62.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from matplotlib<4.0.0,>=3.10.5->shared_utils) (1.5.0)
Requirement already satisfied: pillow>=8 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from matplotlib<4.0.0,>=3.10.5->shared_utils) (12.1.1)
Requirement already satisfied: pyparsing>=3 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from matplotlib<4.0.0,>=3.10.5->shared_utils) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from matplotlib<4.0.0,>=3.10.5->shared_utils) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.46,>=0.45.0dev0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from numba<0.63.0,>=0.62.1->shared_utils) (0.45.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs==2024.5.0->shared_utils) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs==2024.5.0->shared_utils) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs==2024.5.0->shared_utils) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs==2024.5.0->shared_utils) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs==2024.5.0->shared_utils) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs==2024.5.0->shared_utils) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs==2024.5.0->shared_utils) (1.23.0)
Requirement already satisfied: idna>=2.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from yarl<2.0,>=1.17.0->aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs==2024.5.0->shared_utils) (3.11)
Requirement already satisfied: shapely>=2.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from dask-geopandas>=0.5.0->shared_utils) (2.1.2)
Requirement already satisfied: pyarrow>=14.0.1 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from dask[dataframe]>=2025.1.0->dask-geopandas>=0.5.0->shared_utils) (23.0.1)
Requirement already satisfied: fiona>=1.8.21 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from geopandas->movingpandas==0.22.4->shared_utils) (1.10.1)
Requirement already satisfied: pyproj>=3.3.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from geopandas->movingpandas==0.22.4->shared_utils) (3.7.2)
Requirement already satisfied: certifi in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from fiona>=1.8.21->geopandas->movingpandas==0.22.4->shared_utils) (2026.2.25)
Requirement already satisfied: click-plugins>=1.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from fiona>=1.8.21->geopandas->movingpandas==0.22.4->shared_utils) (1.1.1.2)
Requirement already satisfied: cligj>=0.5 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from fiona>=1.8.21->geopandas->movingpandas==0.22.4->shared_utils) (0.7.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from google-auth>=1.2->gcsfs==2024.5.0->shared_utils) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from google-auth>=1.2->gcsfs==2024.5.0->shared_utils) (46.0.5)
Requirement already satisfied: rsa<5,>=3.1.4 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from google-auth>=1.2->gcsfs==2024.5.0->shared_utils) (4.9.1)
Requirement already satisfied: pyasn1>=0.1.3 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from rsa<5,>=3.1.4->google-auth>=1.2->gcsfs==2024.5.0->shared_utils) (0.6.2)
Requirement already satisfied: cffi>=2.0.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from cryptography>=38.0.3->google-auth>=1.2->gcsfs==2024.5.0->shared_utils) (2.0.0)
Requirement already satisfied: pycparser in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth>=1.2->gcsfs==2024.5.0->shared_utils) (3.0)
Requirement already satisfied: zipp>=3.20 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from importlib-metadata->great-tables==0.20.0->shared_utils) (3.23.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from jinja2->altair==6.0.0->shared_utils) (3.0.3)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from jsonschema>=3.0->altair==6.0.0->shared_utils) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from jsonschema>=3.0->altair==6.0.0->shared_utils) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from jsonschema>=3.0->altair==6.0.0->shared_utils) (0.30.0)
Requirement already satisfied: et-xmlfile in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from openpyxl>=3.1.0->shared_utils) (2.0.0)
Requirement already satisfied: pytz>=2020.1 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from pandas->altair-transform==0.2.0->shared_utils) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from pandas->altair-transform==0.2.0->shared_utils) (2025.3)
Requirement already satisfied: locket in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from partd>=1.4.0->dask<2025.4.0,>=2024.10.0->shared_utils) (1.0.0)
Requirement already satisfied: six>=1.5 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib<4.0.0,>=3.10.5->shared_utils) (1.17.0)
Requirement already satisfied: text-unidecode>=1.3 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from python-slugify>=8.0.0->shared_utils) (1.3)
Requirement already satisfied: joblib>=1.3.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from scikit-learn>=1.4->mapclassify<3,>=2.8.0->shared_utils) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from scikit-learn>=1.4->mapclassify<3,>=2.8.0->shared_utils) (3.6.0)
Requirement already satisfied: ipython<9.0.0,>=8.9.0 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from calitp-data-analysis->shared_utils) (8.38.0)
Requirement already satisfied: pandas-gbq<0.20.0,>=0.19.1 in /home/jovyan/data-analyses/.venv/lib/python3.11/site-packages (from calitp-data-analysis->shared_utils) (0.19.2)

In [2]:
pip install rapidfuzz

Collecting rapidfuzz
  Using cached rapidfuzz-3.14.5-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Using cached rapidfuzz-3.14.5-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
Installing collected packages: rapidfuzz
Successfully installed rapidfuzz-3.14.5
Note: you may need to restart the kernel to use updated packages.

In [3]:
# Importing necessary package 
import pandas as pd 
import geopandas as gpd
import numpy as np
import google.auth
import os
import gcsfs
from calitp_data_analysis.sql import get_engine
from calitp_data_analysis import utils
db_engine = get_engine()
credentials, project = google.auth.default()
from pandas.tseries.holiday import USFederalHolidayCalendar
fs = gcsfs.GCSFileSystem()
from rapidfuzz import process, fuzz

pd.set_option('display.max_columns', None)

In [4]:
# Read in ridership data 
GCS_FILE_PATH  = 'gs://calitp-analytics-data/data-analyses/ahsc_grant/ahsc_riderships/AHSC_2026'

In [5]:
ridership_data_saturday = (
    pd.read_csv(f"{GCS_FILE_PATH}/ridership_all.csv")
    .sort_values(by='stop_name')
    .loc[lambda df: df['day_type'] == "Saturday"]
    .reset_index(drop=True)
)

ridership_data_saturday.info()
ridership_data_saturday.head(2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13051 entries, 0 to 13050
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   organization_name         13051 non-null  object
 1   stop_id                   13021 non-null  object
 2   stop_name                 9357 non-null   object
 3   stop_lat                  3613 non-null   float64
 4   stop_lon                  3613 non-null   float64
 5   day_type                  13051 non-null  object
 6   average_daily_boardings   13051 non-null  float64
 7   average_daily_alightings  10963 non-null  float64
 8   start_date                13051 non-null  object
 9   end_date                  13051 non-null  object
dtypes: float64(4), object(6)
memory usage: 1019.7+ KB

,organization_name,stop_id,stop_name,stop_lat,stop_lon,day_type,average_daily_boardings,average_daily_alightings,start_date,end_date
0,Samtrans,345017,1000 El Camino Real-Menlo College,37.457839,-122.190513,Saturday,9.4,16.2,2025-08-01,2025-08-31
1,Golden Gate Transit,40469,1011 Andersen Dr,NaN,NaN,Saturday,3.5,0.0,2025-09-01,2025-09-30

In [6]:
ridership_data_sunday = (
    pd.read_csv(f"{GCS_FILE_PATH}/ridership_all.csv")
    .sort_values(by='stop_name')
    .loc[lambda df: df['day_type'] == "Sunday"]
    .reset_index(drop=True)
)

ridership_data_sunday.info()
ridership_data_sunday.head(2)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12526 entries, 0 to 12525
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   organization_name         12526 non-null  object
 1   stop_id                   12496 non-null  object
 2   stop_name                 8879 non-null   object
 3   stop_lat                  3528 non-null   float64
 4   stop_lon                  3528 non-null   float64
 5   day_type                  12526 non-null  object
 6   average_daily_boardings   12526 non-null  float64
 7   average_daily_alightings  10443 non-null  float64
 8   start_date                12526 non-null  object
 9   end_date                  12526 non-null  object
dtypes: float64(4), object(6)
memory usage: 978.7+ KB

,organization_name,stop_id,stop_name,stop_lat,stop_lon,day_type,average_daily_boardings,average_daily_alightings,start_date,end_date
0,Samtrans,345017,1000 El Camino Real-Menlo College,37.457839,-122.190513,Sunday,8.8,15.6,2025-08-01,2025-08-31
1,Golden Gate Transit,40469,1011 Andersen Dr,NaN,NaN,Sunday,1.5,0.0,2025-09-01,2025-09-30

In [7]:
agency_mapping = {
    'Gold Coast Schedule': 'Gold Coast Transit',
    'Burbank Schedule': 'City of Burbank',
    'SamTrans Schedule': 'Samtrans',
    'Big Blue Bus Schedule': 'Big Blue Bus',
    'Foothill Schedule': 'Foothill Transit',
    'San Diego Schedule': 'SDMTS',
    'Golden Gate Park Shuttle Schedule': 'Golden Gate Park Shuttle',
    'Fresno Schedule': 'Fresno County',
    'OmniTrans Schedule': 'Omnitrans',
    'Sacramento Schedule': 'SacRT Bus',
    'BART Schedule': 'San Francisco Bay Area Rapid Transit District',
    'Riverside Schedule': 'Riverside Transit',
    'OCTA Schedule': 'Orange County Transportation Authority',
    'Santa Cruz Schedule': 'Santa Cruz Metro',
    'Long Beach Schedule': 'Long Beach Transit',
    'Caltrain Schedule': 'Caltrain',
    'SBMTD Schedule': 'SBMTD',
    'Culver City Schedule': 'Culver City Bus',
    'Golden Gate Transit Schedule': 'Golden Gate Transit'
}

In [8]:
stops_aggregated_saturday = (
    pd.read_csv(f"{GCS_FILE_PATH}/stops_aggregated_saturday.csv")
    .assign(organization_name=lambda df: df['name'].map(agency_mapping))
)

stops_aggregated_sunday = (
    pd.read_csv(f"{GCS_FILE_PATH}/stops_aggregated_sunday.csv")
    .assign(organization_name=lambda df: df['name'].map(agency_mapping))
)

stops_aggregated_saturday.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23157 entries, 0 to 23156
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   feed_key           23157 non-null  object
 1   stop_id            23157 non-null  object
 2   stop_name          23157 non-null  object
 3   n_arrivals         23157 non-null  int64
 4   n_routes           23157 non-null  int64
 5   route_id_list      23157 non-null  object
 6   stop_code          20417 non-null  object
 7   pt_geom            23157 non-null  object
 8   name               23157 non-null  object
 9   organization_name  23157 non-null  object
dtypes: int64(2), object(8)
memory usage: 1.8+ MB

In [9]:
# Upon checking, found that Some stops are unmatched because Big Blue Bus ridership uses negative stop_codes.
# These correspond to valid stop_codes in the stop data (same route and stop_name).
# The mapping below replaces negative ridership stop_codes with the correct stop_codes
# so they can match during the merge.

for ridership_df, stops_df in [
    (ridership_data_saturday, stops_aggregated_saturday),
    (ridership_data_sunday, stops_aggregated_sunday),
]:

    # --- Big Blue Bus stop_id mapping ---
    mask_bb = ridership_df['organization_name'] == 'Big Blue Bus'

    ridership_df.loc[mask_bb, 'stop_id'] = (
        ridership_df.loc[mask_bb, 'stop_id']
        .astype(int)
        .replace({
            -4: 'MNSWSMNF',
            -5: '014MCHNN',
            -6: '014PCONF',
            -7: '014PCOSF',
            -8: '017PRLNN',
            -9: '017PRLSF',
            -13: 'PRL014EF',
            -14: 'PRL014WN',
            -18: 'SMCBUNPL'
        })
        .astype(str)
    )

    #  clean stop_code
    stops_df.loc[
        stops_df['organization_name'] == 'Big Blue Bus',
        'stop_code'
    ] = (
        stops_df.loc[
            stops_df['organization_name'] == 'Big Blue Bus',
            'stop_code'
        ]
        .astype(str)
        .str.strip()
    )

# Upon checking, found that Gold Coast Schedule stop_ids have some issues:
# 1. Some stop_ids contain ':' which prevents correct merge with ridership data
# 2. Two specific stop_ids ('GCTDMAIN1' and 'SAClMAI1') do not match the ridership data stop_ids ('GCTDMAIN' and 'SACLMAI1')
# So we remove colons and update these two stop_ids before merging
for df in [stops_aggregated_saturday, stops_aggregated_sunday]:
    mask = df['name'] == "Gold Coast Schedule"
    
    df.loc[mask, 'stop_id'] = (
        df.loc[mask, 'stop_id']
        .str.replace(':', '', regex=False)
        .replace({
            'GCTDMAIN1': 'GCTDMAIN',
            'SAClMAI1': 'SACLMAI1'
        })
    )


# Upon checking found that Long Beach transit stop_id has leading zeros like 0110, 0220 and so on
agencies = [
    'Long Beach Transit', 'Orange County Transportation Authority'
]

for df in [stops_aggregated_saturday, stops_aggregated_sunday]:
    for agency in agencies:
        mask = df['organization_name'] == agency

        df.loc[mask, 'stop_id'] = (
            df.loc[mask, 'stop_id']
            .astype(str)
            .str.replace(r'^0+', '', regex=True)
        )

In [10]:
master_cols = [
    "organization_name",
    "feed_key",
    "stop_id",
    "stop_name",
    "stop_code",
    "n_arrivals",
    "n_routes",
    "pt_geom",
    "day_type",
    "average_daily_boardings",
    "average_daily_alightings",
    "start_date",
    "end_date"
]

def standardize_columns(df, master_cols):
    
    # add missing columns
    for col in master_cols:
        if col not in df.columns:
            df[col] = None

    # keep only master columns and order them
    return df[master_cols]

### Agencies with Saturday and Sunday Data, Categorized by Match Type: route*stop_id, stop_code, or stop_name

In [11]:
ridership_data_sunday.organization_name.unique()

array(['Samtrans', 'Golden Gate Transit', 'Long Beach Transit', 'SDMTS',
       'Golden Gate Park Shuttle', 'Fresno County',
       'San Francisco Bay Area Rapid Transit District', 'Big Blue Bus',
       'Caltrain', 'Culver City Bus', 'Foothill Transit',
       'Riverside Transit'], dtype=object)

In [12]:
agencies__with_stop_id_match = [
    'Foothill Transit',
    # 'Gold Coast Transit',
    'Golden Gate Transit',
    'Long Beach Transit',
    # 'Orange County Transportation Authority',
    # 'Omnitrans',    
    # 'SacRT Bus',
    'Samtrans',
    'SDMTS',
    'San Francisco Bay Area Rapid Transit District', 
    'Fresno County',
    # 'SBMTD'
]

agencies_with_stop_code_match = [
    'Culver City Bus',
    'Big Blue Bus',
    'Riverside Transit',
    # 'Santa Cruz Metro',
    'Golden Gate Park Shuttle',
]



agencies_with_stop_name_match = [
                          'Caltrain',
                          # 'City of Burbank',
                         ]

In [13]:
# Split Ridership by categories

def split_ridership_by_agency(ridership_df, agency_groups):
    subsets = {}
    for name, agencies in agency_groups.items():
        subsets[name] = ridership_df[ridership_df['organization_name'].isin(agencies)]
    return subsets

agency_groups = {
    'with_stop_id_match': agencies__with_stop_id_match,
    'with_stop_code_match': agencies_with_stop_code_match,
    'with_stop_name_match': agencies_with_stop_name_match
}

ridership_subsets_saturday = split_ridership_by_agency(ridership_data_saturday, agency_groups)
ridership_subsets_sunday = split_ridership_by_agency(ridership_data_sunday, agency_groups)

In [14]:
# Merge without route_id
merge_with_stop_id_match_saturday = (
    pd.merge(
        ridership_subsets_saturday['with_stop_id_match'], 
        stops_aggregated_saturday,
        on=['organization_name', 'stop_id'],
        how='left',
        indicator=True,
        suffixes=('_x','_y')
    )
    .rename(columns={
        'stop_name_y': 'stop_name',
    })
)

# Keep only rows where the merge matched in both DataFrames
merge_with_stop_id_matched_saturday = merge_with_stop_id_match_saturday[merge_with_stop_id_match_saturday['_merge'] == 'both'].copy()

merge_counts_saturday = merge_with_stop_id_matched_saturday['_merge'].value_counts()
print(merge_counts_saturday)

_merge
both          9867
left_only        0
right_only       0
Name: count, dtype: int64

In [15]:
merge_with_stop_id_matched_saturday = standardize_columns(merge_with_stop_id_matched_saturday, master_cols)
merge_with_stop_id_matched_saturday.sample(5)

,organization_name,feed_key,stop_id,stop_name,stop_code,n_arrivals,n_routes,pt_geom,day_type,average_daily_boardings,average_daily_alightings,start_date,end_date
500,Long Beach Transit,cddd375786d835389a7beb9632369907,1009,7th & Junipero SE,1009,49.0,2.0,POINT(-118.163057 33.77529),Saturday,33.532628,27.135804,2024-07-01,2025-06-30
1483,Fresno County,23d1893801eefadf7544a670a3bcd312,184,CHESTNUT - CLINTON,184,23.0,1.0,POINT(-119.736485 36.77247),Saturday,7.218279,7.612833,2024-09-01,2025-08-31
9208,Foothill Transit,661ef844bdaa253e8b950740f76061b1,1936,Live Oak Ave and Mayflower Ave E,1936,56.0,1.0,POINT(-118.009341 34.110342),Saturday,2.608696,0.782609,2024-07-01,2025-06-30
6125,SDMTS,1fff52f9349da228c56eef492df5001b,50010,Plaza Bl & 1900,50010,43.0,2.0,POINT(-117.08633406 32.67649838),Saturday,3.574526,4.914981,2024-09-01,2025-01-25
2562,Samtrans,db97cc02836aa5f0cf647d80160b23ec,341136,El Camino Real & 37th Ave,341136,69.0,2.0,POINT(-122.294383 37.534433),Saturday,31.444444,32.000000,2025-08-01,2025-08-31

In [16]:
# Merge without route_id
merge_with_stop_id_match_sunday = (
    pd.merge(
        ridership_subsets_sunday['with_stop_id_match'], 
        stops_aggregated_sunday,
        on=['organization_name', 'stop_id'],
        how='left',
        indicator=True,
        suffixes=('_x','_y')
    )
    .rename(columns={
        'stop_name_y': 'stop_name',
    })
)

# Keep only rows where the merge matched in both DataFrames
merge_with_stop_id_matched_sunday = merge_with_stop_id_match_sunday[merge_with_stop_id_match_sunday['_merge'] == 'both'].copy()

merge_counts_sunday = merge_with_stop_id_matched_sunday['_merge'].value_counts()
print(merge_counts_sunday)

_merge
both          9360
left_only        0
right_only       0
Name: count, dtype: int64

In [17]:
merge_with_stop_id_matched_sunday = standardize_columns(merge_with_stop_id_matched_sunday, master_cols)
merge_with_stop_id_matched_sunday.sample(5)

,organization_name,feed_key,stop_id,stop_name,stop_code,n_arrivals,n_routes,pt_geom,day_type,average_daily_boardings,average_daily_alightings,start_date,end_date
7692,SDMTS,1fff52f9349da228c56eef492df5001b,10392,West Point Loma Bl & Groton St,10392,32.0,1.0,POINT(-117.22153797 32.75436227),Sunday,5.503775,7.674174,2024-09-01,2025-01-25
68,SDMTS,1fff52f9349da228c56eef492df5001b,50012,18th St & Prospect St,50012,42.0,1.0,POINT(-117.08033738 32.67364475),Sunday,2.279032,18.403400,2024-09-01,2025-01-25
7113,Long Beach Transit,cddd375786d835389a7beb9632369907,1650,South & Paramount NW,1650,23.0,1.0,POINT(-118.16036 33.860266),Sunday,60.531152,15.754363,2024-07-01,2025-06-30
2842,SDMTS,1fff52f9349da228c56eef492df5001b,12701,Genesee Av & Mt Foraker Av,12701,32.0,1.0,POINT(-117.18795247 32.82539114),Sunday,1.475576,0.952356,2024-09-01,2025-01-25
6602,Fresno County,23d1893801eefadf7544a670a3bcd312,372,SW M ST - STANISLAUS,372,22.0,1.0,POINT(-119.792342 36.740778),Sunday,0.300925,3.252086,2024-09-01,2025-08-31

In [18]:
merge_with_stop_code_match_saturday = (
    pd.merge(
        ridership_subsets_saturday['with_stop_code_match'],  
        stops_aggregated_saturday,
        left_on=['organization_name', 'stop_id'],  # ridership stop_id
        right_on=['organization_name', 'stop_code'],  # stops table stop_code
        how='left',
        indicator=True
    )
    .rename(columns={
        'stop_id_y': 'stop_id',
        'stop_name_y': 'stop_name',
    })
)


# Keep only rows where the merge matched in both DataFrames
merge_with_stop_code_matched_saturday = merge_with_stop_code_match_saturday[merge_with_stop_code_match_saturday['_merge'] == 'both'].copy()

# Check merge results
merge_counts_saturday = merge_with_stop_code_matched_saturday['_merge'].value_counts()
print(merge_counts_saturday)

_merge
both          2933
left_only        0
right_only       0
Name: count, dtype: int64

In [19]:
merge_with_stop_code_matched_saturday = standardize_columns(merge_with_stop_code_matched_saturday, master_cols)
merge_with_stop_code_matched_saturday.sample(5)

,organization_name,feed_key,stop_id,stop_name,stop_code,n_arrivals,n_routes,pt_geom,day_type,average_daily_boardings,average_daily_alightings,start_date,end_date
1048,Riverside Transit,6eb2b575bee157dace7a2c7155d3cb25,202,Riverside City College,1079,73.0,3.0,POINT(-117.383553 33.972628),Saturday,5.986111,NaN,2025-01-01,2025-10-31
1858,Riverside Transit,6eb2b575bee157dace7a2c7155d3cb25,822,Ironwood + Dream,2012,9.0,1.0,POINT(-117.256687 33.946689),Saturday,0.895833,NaN,2025-01-01,2025-10-31
2596,Riverside Transit,6eb2b575bee157dace7a2c7155d3cb25,1992,Oakland + Santa Fe,3083,16.0,1.0,POINT(-116.962747 33.754904),Saturday,2.046875,NaN,2025-01-01,2025-10-31
2258,Riverside Transit,6eb2b575bee157dace7a2c7155d3cb25,1382,California Oaks + Jackson,2526,10.0,1.0,POINT(-117.204262 33.571623),Saturday,1.193548,NaN,2025-01-01,2025-10-31
2334,Riverside Transit,6eb2b575bee157dace7a2c7155d3cb25,1484,Pechanga Parkway + Muirfield,2625,10.0,1.0,POINT(-117.119812 33.468495),Saturday,0.840909,NaN,2025-01-01,2025-10-31

In [20]:
merge_with_stop_code_match_sunday = (
    pd.merge(
        ridership_subsets_sunday['with_stop_code_match'],  
        stops_aggregated_sunday,
        left_on=['organization_name', 'stop_id'],  # ridership stop_id
        right_on=['organization_name', 'stop_code'],  # stops table stop_code
        how='left',
        indicator=True
    )
    .rename(columns={
        'stop_id_y': 'stop_id',
        'stop_name_y': 'stop_name',
    })
)


# Keep only rows where the merge matched in both DataFrames
merge_with_stop_code_matched_sunday = merge_with_stop_code_match_sunday[merge_with_stop_code_match_sunday['_merge'] == 'both'].copy()

# Check merge results
merge_counts_sunday = merge_with_stop_code_matched_sunday['_merge'].value_counts()
print(merge_counts_sunday)

_merge
both          2931
left_only        0
right_only       0
Name: count, dtype: int64

In [21]:
merge_with_stop_code_matched_sunday = standardize_columns(merge_with_stop_code_matched_sunday, master_cols)
merge_with_stop_code_matched_sunday.sample(5)

,organization_name,feed_key,stop_id,stop_name,stop_code,n_arrivals,n_routes,pt_geom,day_type,average_daily_boardings,average_daily_alightings,start_date,end_date
2828,Riverside Transit,6eb2b575bee157dace7a2c7155d3cb25,2824,Market + 11th,3503,29.0,2.0,POINT(-117.377326 33.979863),Sunday,2.071429,NaN,2025-01-01,2025-10-31
115,Big Blue Bus,7a3f513c343b16a30c135ed7d332b6d6,908,BUNDY DR & SANTA MONICA BLVD,2459,33.0,1.0,POINT(-118.46354 34.040886),Sunday,17.624870,58.432179,2024-08-01,2025-11-30
2653,Riverside Transit,6eb2b575bee157dace7a2c7155d3cb25,2179,Mission + Wallace,3255,15.0,1.0,POINT(-117.402603 33.994649),Sunday,4.500000,NaN,2025-01-01,2025-10-31
2624,Riverside Transit,6eb2b575bee157dace7a2c7155d3cb25,2056,Menifee + Newport,3137,12.0,1.0,POINT(-117.153924 33.684529),Sunday,1.025000,NaN,2025-01-01,2025-10-31
2771,Riverside Transit,6eb2b575bee157dace7a2c7155d3cb25,2386,Simpson + Winchester,3400,21.0,2.0,POINT(-117.084267 33.707302),Sunday,1.500000,NaN,2025-01-01,2025-10-31

In [22]:
cols_to_keep = [
    'feed_key', 'stop_id',
    'n_arrivals', 'n_routes', 'pt_geom'
]

def fuzzy_match_subset(left_df, right_df, threshold=80):
    results = []

    for org in left_df['organization_name'].unique():
        left_group = left_df[left_df['organization_name'] == org]
        right_group = right_df[right_df['organization_name'] == org]

        if right_group.empty:
            continue

        choices = right_group['stop_name'].tolist()

        for idx, row in left_group.iterrows():
            match, score, match_idx = process.extractOne(
                row['stop_name'],
                choices,
                scorer=fuzz.token_set_ratio
            )

            if score >= threshold:
                matched_row = right_group.iloc[match_idx]
                subset = matched_row[cols_to_keep].to_dict()
                matched_name = matched_row['stop_name']
            else:
                subset = {col: None for col in cols_to_keep}
                matched_name = None

            subset.update({
                'left_index': idx,
                'original_stop_name': row['stop_name'],
                'matched_stop_name': matched_name,
                'score': score
            })

            results.append(subset)

    return pd.DataFrame(results)

In [23]:
matches_df_saturday = fuzzy_match_subset(
    ridership_subsets_saturday['with_stop_name_match'], 
    stops_aggregated_saturday,
    threshold=80
)

In [24]:
matches_df_sunday = fuzzy_match_subset(
    ridership_subsets_sunday['with_stop_name_match'], 
    stops_aggregated_sunday,
    threshold=80
)

In [25]:
merge_with_stop_name_match_saturday = (
    ridership_subsets_saturday['with_stop_name_match']
    .merge(
        matches_df_saturday,
        left_index=True,
        right_on='left_index',
        how='left',
        indicator=True
    )
    .rename(columns={
        'stop_id_y': 'stop_id',
    })
)

# Keep only rows where the merge matched in both DataFrames
merge_with_stop_name_matched_saturday = merge_with_stop_name_match_saturday[merge_with_stop_name_match_saturday['_merge'] == 'both'].copy()

merge_counts_saturday = merge_with_stop_name_matched_saturday['_merge'].value_counts()
print(merge_counts_saturday)

_merge
both          30
left_only      0
right_only     0
Name: count, dtype: int64

In [26]:
merge_with_stop_name_matched_saturday = standardize_columns(merge_with_stop_name_matched_saturday, master_cols)
merge_with_stop_name_matched_saturday.sample(5)

,organization_name,feed_key,stop_id,stop_name,stop_code,n_arrivals,n_routes,pt_geom,day_type,average_daily_boardings,average_daily_alightings,start_date,end_date
23,Caltrain,f189d5677d4a106b98585f3c5d4fd42c,70261,San Jose Diridon,None,33.0,1.0,POINT(-121.903011 37.329239),Saturday,927.841691,NaN,2023-11-01,2025-07-31
0,Caltrain,f189d5677d4a106b98585f3c5d4fd42c,70021,22nd Street,None,33.0,1.0,POINT(-122.39188 37.757599),Saturday,433.679398,NaN,2023-11-01,2025-07-31
19,Caltrain,f189d5677d4a106b98585f3c5d4fd42c,70201,San Antonio,None,33.0,1.0,POINT(-122.107002027 37.407332157),Saturday,337.334310,NaN,2023-11-01,2025-07-31
16,Caltrain,f189d5677d4a106b98585f3c5d4fd42c,70211,Mountain View,None,33.0,1.0,POINT(-122.075956 37.394459),Saturday,907.007547,NaN,2023-11-01,2025-07-31
13,Caltrain,f189d5677d4a106b98585f3c5d4fd42c,70161,Menlo Park,None,33.0,1.0,POINT(-122.182297 37.454856),Saturday,430.511130,NaN,2023-11-01,2025-07-31

In [27]:
merge_with_stop_name_match_sunday = (
    ridership_subsets_sunday['with_stop_name_match']
    .merge(
        matches_df_sunday,
        left_index=True,
        right_on='left_index',
        how='left',
        indicator=True
    )
    .rename(columns={
        'stop_id_y': 'stop_id',
    })
)

# Keep only rows where the merge matched in both DataFrames
merge_with_stop_name_matched_sunday = merge_with_stop_name_match_sunday[merge_with_stop_name_match_sunday['_merge'] == 'both'].copy()

merge_counts_sunday = merge_with_stop_name_matched_sunday['_merge'].value_counts()
print(merge_counts_sunday)

_merge
both          30
left_only      0
right_only     0
Name: count, dtype: int64

In [28]:
merge_with_stop_name_matched_sunday = standardize_columns(merge_with_stop_name_matched_sunday, master_cols)
merge_with_stop_name_matched_sunday.sample(5)

,organization_name,feed_key,stop_id,stop_name,stop_code,n_arrivals,n_routes,pt_geom,day_type,average_daily_boardings,average_daily_alightings,start_date,end_date
11,Caltrain,f189d5677d4a106b98585f3c5d4fd42c,70111,Hillsdale,None,33.0,1.0,POINT(-122.301496637 37.542607659),Sunday,383.080655,NaN,2023-11-01,2025-07-31
3,Caltrain,None,None,Blossom Hill,None,NaN,NaN,None,Sunday,0.000000,NaN,2023-11-01,2025-07-31
19,Caltrain,f189d5677d4a106b98585f3c5d4fd42c,70201,San Antonio,None,33.0,1.0,POINT(-122.107002027 37.407332157),Sunday,267.250227,NaN,2023-11-01,2025-07-31
2,Caltrain,f189d5677d4a106b98585f3c5d4fd42c,70121,Belmont,None,33.0,1.0,POINT(-122.275738 37.52089),Sunday,200.684947,NaN,2023-11-01,2025-07-31
10,Caltrain,f189d5677d4a106b98585f3c5d4fd42c,70101,Hayward Park,None,33.0,1.0,POINT(-122.309338 37.552938),Sunday,108.782698,NaN,2023-11-01,2025-07-31

In [29]:
all_ridership_stop_trips_saturday_data = pd.concat([
    merge_with_stop_id_matched_saturday,
    merge_with_stop_code_matched_saturday,
    merge_with_stop_name_matched_saturday    
], ignore_index=True)

In [30]:
all_ridership_stop_trips_sunday_data = pd.concat([
    merge_with_stop_id_matched_sunday,
    merge_with_stop_code_matched_sunday,
    merge_with_stop_name_matched_sunday    
], ignore_index=True)

In [31]:
all_ridership_stop_trips_saturday_data.to_csv(f"{GCS_FILE_PATH}/ridership_trips_routes_saturday.csv", index=False)
all_ridership_stop_trips_sunday_data.to_csv(f"{GCS_FILE_PATH}/ridership_trips_routes_saturday.csv", index=False)