## Exercise 7 - Testing Tableau

In [1]:
import geopandas as gpd
import intake
import pandas as pd


import calitp
from calitp.tables import tbl
from calitp import query_sql
from siuba import *

import shapely
from shapely.geometry import Polygon, LineString, Point
from shapely import wkt
from shapely.geometry import Point, Polygon
from shapely.wkt import loads

import shared_utils 
import os
from calitp.tables import tbl

os.environ["CALITP_BQ_MAX_BYTES"] = str(50_000_000_000)

WGS84 = "EPSG:4326"
CA_StatePlane = "EPSG:2229"  # units are in feet
CA_NAD83Albers = "EPSG:3310"  # units are in meters

SQ_MI_PER_SQ_M = 3.86 * 10 ** -7
FEET_PER_MI = 5_280
SQ_FT_PER_SQ_MI = 2.788 * 10 ** 7

/opt/conda/lib/python3.9/site-packages/geopandas/_compat.py:111: UserWarning: The Shapely GEOS version (3.10.2-CAPI-1.16.0) is incompatible with the GEOS version PyGEOS was compiled with (3.10.1-CAPI-1.16.0). Conversions between both will be slow.
  warnings.warn(
E0329 15:18:55.143816796     956 fork_posix.cc:70]           Fork support is only compatible with the epoll1 and poll polling strategies

In [41]:
#vars(shared_utils)

## A few Bay Area agencies
[Agencies.yml](https://github.com/cal-itp/data-infra/blob/main/airflow/data/agencies.yml)
* AC Transit: 4
* BART: 279
* SF Muni: 282 
* Samtrans: 290
*  Santa Clara Valley Transportation Authority: 294

In [3]:
#choosing a different set of ITP IDS
ITP_ID = [4,279,282,290,294]

In [4]:
bay_area = (
    tbl.views.gtfs_schedule_dim_stops()
    >> select(_.itp_id == _.calitp_itp_id, _.stop_id, 
             _.stop_lat, _.stop_lon, _.stop_name)
    >> arrange(_.itp_id, _.stop_id, 
               _.stop_lat, _.stop_lon)
    >> collect()
    >> filter(_.itp_id.isin(ITP_ID))
    >> distinct()
)

/opt/conda/lib/python3.9/site-packages/siuba/sql/utils.py:52: SAWarning: Dialect bigquery:bigquery will not make use of SQL compilation caching as it does not set the 'supports_statement_cache' attribute to ``True``.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Dialect maintainers should seek to set this attribute to True after appropriate development and testing for SQLAlchemy 1.4 caching support.   Alternatively, this attribute may be set to False which will disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)

In [5]:
bay_area.head(2)

   itp_id stop_id   stop_lat    stop_lon                             stop_name
0       4      10  37.742485 -122.250108  Aughinbaugh Way & Robert Davey Jr Dr
1       4     100  37.759356 -122.251237                          2217 Otis Dr

In [6]:
f'A total of {len(bay_area)} rows'

'A total of 25283 rows'

In [7]:
bay_area2 = bay_area.drop_duplicates(subset=['stop_id','itp_id'])

In [8]:
f'only {len(bay_area2)} rows after dropping duplicates'

'only 25026 rows after dropping duplicates'

In [9]:
#creating point geometry from longtitude &  latitude 
bay_area2 = shared_utils.geography_utils.create_point_geometry(bay_area2, 
                                                               'stop_lon', 'stop_lat')

In [10]:
bay_area2.head(2)

,itp_id,stop_id,stop_lat,stop_lon,stop_name,geometry
0,4,10,37.742485,-122.250108,Aughinbaugh Way & Robert Davey Jr Dr,POINT (-122.25011 37.74249)
1,4,100,37.759356,-122.251237,2217 Otis Dr,POINT (-122.25124 37.75936)

In [11]:
def make_routes_shapefile(ITP_ID_LIST=[], CRS="EPSG:4326", alternate_df=None):
    """
    Parameters:
    ITP_ID_LIST: list. List of ITP IDs found in agencies.yml
    CRS: str. Default is WGS84, but able to re-project to another CRS.
    Returns a geopandas.GeoDataFrame, where each line is the operator-route-line geometry.
    """

    all_routes = gpd.GeoDataFrame()

    for itp_id in ITP_ID_LIST:
        if alternate_df is None:
            shapes = (
                tbl.gtfs_schedule.shapes()
                >> filter(_.calitp_itp_id == int(itp_id))
                >> collect()
            )

        elif alternate_df is not None:
            shapes = alternate_df.copy()

            # With historical gtfs_schedule_type2.shapes table, there is a valid shape_id
            if shapes.shape_id.isnull().sum() == 0:
                pass
            else:
                # shape_id is None, which will throw up an error later on when there's groupby
                # So, create shape_id and fill it in with route_id info, but only if it's missing
                # To flag these, shape_id as a column wouldn't even exist.
                if "shape_id" not in shapes.columns:
                    shapes = shapes.assign(
                        shape_id=shapes.route_id,
                    )
                else:
                    # This handles operators where most of their shape_ids are valid
                    # Let's just drop missing ones.
                    shapes = shapes[shapes.shape_id.notna()].reset_index(drop=True)

        # Make a gdf
        shapes = gpd.GeoDataFrame(
            shapes,
            geometry=gpd.points_from_xy(shapes.shape_pt_lon, shapes.shape_pt_lat),
            crs=WGS84,
        )

        # Count the number of stops for a given shape_id
        # Must be > 1 (need at least 2 points to make a line)
        shapes = shapes.assign(
            num_stops=(
                shapes.groupby("shape_id")["shape_pt_sequence"].transform("count")
            )
        )

        # Drop the shape_ids that can't make a line
        shapes = shapes[shapes.num_stops > 1].reset_index(drop=True)

        # Now, combine all the stops by stop sequence, and create linestring
        for route in shapes.shape_id.unique():
            single_shape = (
                shapes
                >> filter(_.shape_id == route)
                >> mutate(shape_pt_sequence=_.shape_pt_sequence.astype(int))
                # arrange in the order of stop sequence
                >> arrange(_.shape_pt_sequence)
            )

            # Convert from a bunch of points to a line (for a route, there are multiple points)
            route_line = shapely.geometry.LineString(list(single_shape["geometry"]))
            single_route = single_shape[
                ["calitp_itp_id", "calitp_url_number", "shape_id"]
            ].iloc[
                [0]
            ]  # preserve info cols
            single_route["geometry"] = route_line
            single_route = gpd.GeoDataFrame(single_route, crs=WGS84)

            # https://stackoverflow.com/questions/15819050/pandas-dataframe-concat-vs-append/48168086
            all_routes = pd.concat(
                [all_routes, single_route], ignore_index=True, axis=0
            )

    all_routes = (
        all_routes.to_crs(CRS)
        .sort_values(["calitp_itp_id", "shape_id"])
        .drop_duplicates()
        .reset_index(drop=True)
    )

    return all_routes

In [12]:
#bay_area3 = make_routes_shapefile(ITP_ID_LIST = [4,279,282,290,294], CRS="EPSG:4326")

In [13]:
#bay_area3.head()

In [14]:
#bay_area3.to_file('bay_area_line.geojson', driver='GeoJSON')

## San Francisco Muni Only
* Get dim stops & dim times into one df.
* [Resource 1](https://github.com/cal-itp/data-analyses/blob/main/bus_service_increase/warehouse_queries.py#L71-L76)
* [Resource 2](https://github.com/cal-itp/data-analyses/blob/main/bus_service_increase/setup_parallel_trips_with_stops.py#L136-L153)
    * What df are you supposed to put in here?
* [Resource 3](https://docs.calitp.org/data-infra/analytics_examples/new_tutorial.html)

In [15]:
#just getting stops table first.
SF = (
    tbl.views.gtfs_schedule_dim_stops()
    >> select(_.itp_id == _.calitp_itp_id, _.stop_id, 
             _.stop_lat, _.stop_lon, _.stop_name)
    >> arrange(_.itp_id, _.stop_id, 
               _.stop_lat, _.stop_lon)
    >> collect()
    >> filter(_.itp_id == 282)
    >> distinct()
)

In [16]:
SF.shape

(6373, 5)

In [17]:
SF = SF.drop_duplicates(subset = ['stop_id','stop_name'])

In [18]:
SF.stop_id.nunique()

6328

In [44]:
SF.sort_values('stop_id').head(50)

    itp_id stop_id   stop_lat    stop_lon                       stop_name
0      282   10390  37.721190 -122.475096       19th Avenue & Holloway St
1      282   10913  37.719192 -122.425802       Dublin St & La Grande Ave
2      282   13016  37.772618 -122.389786                 3rd St & 4th St
3      282   13018  37.727739 -122.403240        Bacon St & San Bruno Ave
4      282   13019  37.727645 -122.403269        Bacon St & San Bruno Ave
5      282   13020  37.726670 -122.407460          Bacon St & Somerset St
6      282   13021  37.726540 -122.407660          Bacon St & Somerset St
7      282   13023  37.790249 -122.482263      Baker Beach Parking Lot Sw
8      282   13024  37.797606 -122.445693         Baker St & Greenwich St
9      282   13031  37.806094 -122.409161              Bay St & Midway St
10     282   13032  37.777396 -122.461751             Balboa St & 4th Ave
11     282   13033  37.777262 -122.461969             Balboa St & 4th Ave
12     282   13034  37.777289 -122.464158             Balboa St & 6th Ave
13     282   13035  37.777173 -122.463849             Balboa St & 6th Ave
14     282   13036  37.777199 -122.466038             Balboa St & 8th Ave
15     282   13037  37.777065 -122.466256             Balboa St & 8th Ave
16     282   13038  37.777101 -122.468170            Balboa St & 10th Ave
17     282   13039  37.776967 -122.468388            Balboa St & 10th Ave
18     282   13040  37.777002 -122.470313            Balboa St & 12th Ave
19     282   13041  37.776868 -122.470531            Balboa St & 12th Ave
20     282   13043  37.776760 -122.475769            Balboa St & 17th Ave
21     282   13044  37.776626 -122.475987            Balboa St & 17th Ave
22     282   13045  37.776662 -122.477912            Balboa St & 19th Ave
23     282   13046  37.776528 -122.478130            Balboa St & 19th Ave
24     282   13047  37.776563 -122.480056            Balboa St & 21st Ave
25     282   13048  37.776429 -122.480273            Balboa St & 21st Ave
26     282   13049  37.776470 -122.482190            Balboa St & 23rd Ave
27     282   13050  37.776330 -122.482417            Balboa St & 23rd Ave
28     282   13051  37.776356 -122.484606            Balboa St & 25th Ave
29     282   13052  37.776240 -122.484296            Balboa St & 25th Ave
30     282   13053  37.776222 -122.487551            Balboa St & 28th Ave
31     282   13054  37.776088 -122.487769            Balboa St & 28th Ave
32     282   13055  37.776114 -122.489958            Balboa St & 30th Ave
33     282   13056  37.775989 -122.489912            Balboa St & 30th Ave
34     282   13057  37.776024 -122.491838            Balboa St & 32nd Ave
35     282   13058  37.775890 -122.492056            Balboa St & 32nd Ave
36     282   13059  37.775791 -122.494199            Balboa St & 34th Ave
37     282   13060  37.775898 -122.494577            Balboa St & 35th Ave
38     282   13061  37.775781 -122.497202            Balboa St & 37th Ave
39     282   13062  37.775647 -122.497419            Balboa St & 37th Ave
40     282   13063  37.775637 -122.500399            Balboa St & 40th Ave
41     282   13064  37.775503 -122.500617            Balboa St & 40th Ave
42     282   13065  37.775484 -122.503620            Balboa St & 43rd Ave
43     282   13066  37.775350 -122.503838            Balboa St & 43rd Ave
44     282   13067  37.777470 -122.458860       Balboa St & Arguello Blvd
45     282   13070  37.776895 -122.472227  Balboa St & Park Presidio Blvd
46     282   13071  37.776788 -122.472411  Balboa St & Park Presidio Blvd
47     282   13072  37.801541 -122.444798           Broderick St & Bay St
48     282   13074  37.803415 -122.445176         Broderick St & Beach St
49     282   13075  37.800622 -122.444603     Broderick St & Francisco St

### Stop Sequence
* Why do I need to get calitp deleted at > max date

In [20]:
'''
Tiffany's Code.
    tbl_stop_times = (tbl.views.gtfs_schedule_dim_stop_times()
                      >> filter(_.calitp_extracted_at <= min_date, 
                                _.calitp_deleted_at > max_date)
                      >> select(_.calitp_itp_id, _.trip_id, _.departure_time,
                                _.stop_sequence, _.stop_id)
    )
   
'''

"\nTiffany's Code.\n    tbl_stop_times = (tbl.views.gtfs_schedule_dim_stop_times()\n                      >> filter(_.calitp_extracted_at <= min_date, \n                                _.calitp_deleted_at > max_date)\n                      >> select(_.calitp_itp_id, _.trip_id, _.departure_time,\n                                _.stop_sequence, _.stop_id)\n    )\n   \n"

In [21]:
SELECTED_DATE = "2022-02-28"

In [22]:
#getting times so I can grab the sequence of stops.
SF_times = (
    tbl.views.gtfs_schedule_stop_times()
    >> filter(_.calitp_itp_id == 282)
    >> filter(_.calitp_extracted_at <= SELECTED_DATE)
    >> select(_.calitp_itp_id, _.trip_id, _.departure_time,
                                _.stop_sequence, _.stop_id)
    >> collect()
    >> distinct()
)

In [23]:
SF_times.dtypes

calitp_itp_id      int64
trip_id           object
departure_time    object
stop_sequence      int64
stop_id           object
dtype: object

In [24]:
#filter out for only one trip id, 9987569
#https://www.sfmta.com/routes/29-sunset
SF_times2 = SF_times.loc[SF_times['trip_id'] == '9987569']

In [25]:
SF_times2.stop_id.nunique()

92

In [26]:
SF_times2.shape

(165, 5)

### How do go about the stop sequence corresponding with different stop ids?
* 21, 22, 23, 24 are examples

In [27]:
SF_times2.sort_values('stop_sequence').head(50)

         calitp_itp_id  trip_id departure_time  stop_sequence stop_id
20624              282  9987569       13:36:00              1    4648
1983191            282  9987569       13:36:36              2    4647
1751045            282  9987569       13:37:21              3    4646
1989597            282  9987569       13:38:09              4    4645
972095             282  9987569       13:39:10              5    4784
381960             282  9987569       13:39:45              6    5955
692532             282  9987569       13:40:52              7    5115
1523742            282  9987569       13:41:35              8    5116
399915             282  9987569       13:42:14              9    4976
2226693            282  9987569       13:42:58             10    4785
1539785            282  9987569       13:43:43             11    4786
419186             282  9987569       13:44:27             12    4783
428050             282  9987569       13:45:18             13    5902
1294545            282  9987569       13:45:41             14    5901
1030296            282  9987569       13:46:12             15    5899
1307779            282  9987569       13:46:32             16    5904
455307             282  9987569       13:48:00             17    5350
1317424            282  9987569       13:48:26             18    5337
1579797            282  9987569       13:48:45             19    5342
474678             282  9987569       13:48:57             20    5352
2470903            282  9987569       13:48:57             21    5352
1832906            282  9987569       13:49:25             21    5343
2474387            282  9987569       13:49:25             22    5343
1342756            282  9987569       13:49:55             22    5339
498308             282  9987569       13:49:55             23    5339
182832             282  9987569       13:50:32             23    5353
803468             282  9987569       13:50:32             24    5353
2284816            282  9987569       13:51:22             24    5345
1360502            282  9987569       13:51:22             25    5345
1088390            282  9987569       13:52:29             25    5347
2491348            282  9987569       13:52:29             26    5347
1857744            282  9987569       13:53:34             26    5909
817229             282  9987569       13:54:58             27    5920
520914             282  9987569       13:53:34             27    5909
2500116            282  9987569       13:54:58             28    5920
2091314            282  9987569       13:55:26             28    5914
1380608            282  9987569       13:55:26             29    5914
2307036            282  9987569       13:55:39             29    5907
1116640            282  9987569       13:56:07             30    5916
2101503            282  9987569       13:55:39             30    5907
2315428            282  9987569       13:56:35             31    5910
1390522            282  9987569       13:56:07             31    5916
549221             282  9987569       13:56:35             32    5910
1646179            282  9987569       13:57:02             32    5918
2115740            282  9987569       13:57:02             33    5918
2323416            282  9987569       13:57:29             33    5912
2329555            282  9987569       13:57:29             34    5912
2118319            282  9987569       13:58:18             34    5782
1898742            282  9987569       13:58:50             35    7638
563319             282  9987569       13:58:18             35    5782

### Merging

In [28]:
SF_times2 = SF_times2.drop(columns=['calitp_itp_id'])

In [29]:
SF_joined = pd.merge(SF_times2, SF,  how='inner', on=['stop_id'], indicator=True)

In [30]:
SF_joined._merge.value_counts()

both          165
left_only       0
right_only      0
Name: _merge, dtype: int64

In [31]:
SF_joined.shape

(165, 9)

In [32]:
SF_joined2 = shared_utils.geography_utils.create_point_geometry(SF_joined, 
                                                               'stop_lon', 'stop_lat')

* Again, stop sequence and stop names sometimes don't match starting at sequence 21.
* Persia & Prague St appears at stop sequence 27 and 28.

In [33]:
SF_joined2.sort_values('stop_sequence').head(50)

,trip_id,departure_time,stop_sequence,stop_id,itp_id,stop_lat,stop_lon,stop_name,_merge,geometry
14,9987569,13:36:00,1,4648,282,37.722895,-122.394842,Fitzgerald Ave & Keith St,both,POINT (-122.39484 37.72290)
156,9987569,13:36:36,2,4647,282,37.722028,-122.393320,Fitzgerald Ave & Jennings St,both,POINT (-122.39332 37.72203)
149,9987569,13:37:21,3,4646,282,37.720966,-122.391453,Fitzgerald Ave & Ingalls St,both,POINT (-122.39145 37.72097)
157,9987569,13:38:09,4,4645,282,37.719921,-122.389587,Fitzgerald Ave & Hawes St,both,POINT (-122.38959 37.71992)
103,9987569,13:39:10,5,4784,282,37.718234,-122.388272,Gilman Ave & Griffith St,both,POINT (-122.38827 37.71823)
51,9987569,13:39:45,6,5955,282,37.717502,-122.386990,Gilman Ave and Giants Dr,both,POINT (-122.38699 37.71750)
88,9987569,13:40:52,7,5115,282,37.717012,-122.389212,Ingerson Ave & Griffith St,both,POINT (-122.38921 37.71701)
138,9987569,13:41:35,8,5116,282,37.718039,-122.390998,Ingerson Ave & Hawes St,both,POINT (-122.39100 37.71804)
52,9987569,13:42:14,9,4976,282,37.719198,-122.390012,Hawes St & Gilman Ave,both,POINT (-122.39001 37.71920)
162,9987569,13:42:58,10,4785,282,37.720350,-122.391729,Gilman Ave & Ingalls St,both,POINT (-122.39173 37.72035)
139,9987569,13:43:43,11,4786,282,37.721413,-122.393595,Gilman Ave & Jennings St,both,POINT (-122.39360 37.72141)
53,9987569,13:44:27,12,4783,282,37.722458,-122.395415,Gilman Ave & 3rd St,both,POINT (-122.39541 37.72246)
54,9987569,13:45:18,13,5902,282,37.723012,-122.397946,Paul Ave & Gould St,both,POINT (-122.39795 37.72301)
121,9987569,13:45:41,14,5901,282,37.723289,-122.399080,Paul Ave & Crane St,both,POINT (-122.39908 37.72329)
104,9987569,13:46:12,15,5899,282,37.723647,-122.400591,Paul Ave & Bay Shore Blvd,both,POINT (-122.40059 37.72365)
122,9987569,13:46:32,16,5904,282,37.723879,-122.401576,Paul Ave & San Bruno Ave,both,POINT (-122.40158 37.72388)
55,9987569,13:48:00,17,5350,282,37.721541,-122.401394,Mansell St & San Bruno Ave,both,POINT (-122.40139 37.72154)
123,9987569,13:48:26,18,5337,282,37.721096,-122.403067,Mansell St & Brussels St,both,POINT (-122.40307 37.72110)
140,9987569,13:48:45,19,5342,282,37.720766,-122.404338,Mansell St & Goettingen St,both,POINT (-122.40434 37.72077)
56,9987569,13:48:57,20,5352,282,37.720525,-122.405117,Mansell St & Somerset St,both,POINT (-122.40512 37.72053)
57,9987569,13:48:57,21,5352,282,37.720525,-122.405117,Mansell St & Somerset St,both,POINT (-122.40512 37.72053)
150,9987569,13:49:25,21,5343,282,37.720098,-122.406916,Mansell St & Hamilton St,both,POINT (-122.40692 37.72010)
151,9987569,13:49:25,22,5343,282,37.720098,-122.406916,Mansell St & Hamilton St,both,POINT (-122.40692 37.72010)
59,9987569,13:49:55,22,5339,282,37.719581,-122.408886,Mansell St & Dartmouth St,both,POINT (-122.40889 37.71958)
58,9987569,13:49:55,23,5339,282,37.719581,-122.408886,Mansell St & Dartmouth St,both,POINT (-122.40889 37.71958)
15,9987569,13:50:32,23,5353,282,37.718957,-122.411257,Mansell St & University St,both,POINT (-122.41126 37.71896)
125,9987569,13:51:22,24,5345,282,37.718119,-122.414464,Mansell St & John F Shelley Dr,both,POINT (-122.41446 37.71812)
16,9987569,13:50:32,24,5353,282,37.718957,-122.411257,Mansell St & University St,both,POINT (-122.41126 37.71896)
124,9987569,13:51:22,25,5345,282,37.718119,-122.414464,Mansell St & John F Shelley Dr,both,POINT (-122.41446 37.71812)
105,9987569,13:52:29,25,5347,282,37.718897,-122.418804,Mansell St & John F Shelley Dr,both,POINT (-122.41880 37.71890)
61,9987569,13:53:34,26,5909,282,37.717791,-122.422779,Persia Ave & Brazil Ave,both,POINT (-122.42278 37.71779)
106,9987569,13:52:29,26,5347,282,37.718897,-122.418804,Mansell St & John F Shelley Dr,both,POINT (-122.41880 37.71890)
89,9987569,13:54:58,27,5920,282,37.718961,-122.427062,Persia Ave & Prague St,both,POINT (-122.42706 37.71896)
60,9987569,13:53:34,27,5909,282,37.717791,-122.422779,Persia Ave & Brazil Ave,both,POINT (-122.42278 37.71779)
90,9987569,13:54:58,28,5920,282,37.718961,-122.427062,Persia Ave & Prague St,both,POINT (-122.42706 37.71896)
127,9987569,13:55:26,28,5914,282,37.719728,-122.428676,Persia Ave & Moscow St,both,POINT (-122.42868 37.71973)
126,9987569,13:55:26,29,5914,282,37.719728,-122.428676,Persia Ave & Moscow St,both,POINT (-122.42868 37.71973)
159,9987569,13:55:39,29,5907,282,37.720112,-122.429467,Persia Ave & Athens St,both,POINT (-122.42947 37.72011)
158,9987569,13:55:39,30,5907,282,37.720112,-122.429467,Persia Ave & Athens St,both,POINT (-122.42947 37.72011)
107,9987569,13:56:07,30,5916,282,37.720880,-122.431070,Persia Ave & Naples St,both,POINT (-122.43107 37.72088)
108,9987569,13:56:07,31,5916,282,37.720880,-122.431070,Persia Ave & Naples St,both,POINT (-122.43107 37.72088)
63,9987569,13:56:35,31,5910,282,37.721638,-122.432673,Persia Ave & Madrid St,both,POINT (-122.43267 37.72164)
141,9987569,13:57:02,32,5918,282,37.722406,-122.434276,Persia Ave & Paris St,both,POINT (-122.43428 37.72241)
62,9987569,13:56:35,32,5910,282,37.721638,-122.432673,Persia Ave & Madrid St,both,POINT (-122.43267 37.72164)
142,9987569,13:57:02,33,5918,282,37.722406,-122.434276,Persia Ave & Paris St,both,POINT (-122.43428 37.72241)
163,9987569,13:57:29,33,5912,282,37.723147,-122.435845,Persia Ave & Mission St,both,POINT (-122.43585 37.72315)
164,9987569,13:57:29,34,5912,282,37.723147,-122.435845,Persia Ave & Mission St,both,POINT (-122.43585 37.72315)
65,9987569,13:58:18,34,5782,282,37.723670,-122.438670,Ocean Ave & Cayuga Ave,both,POINT (-122.43867 37.72367)
64,9987569,13:58:18,35,5782,282,37.723670,-122.438670,Ocean Ave & Cayuga Ave,both,POINT (-122.43867 37.72367)
152,9987569,13:58:50,35,7638,282,37.723433,-122.440816,Ocean Ave & Otsego Ave,both,POINT (-122.44082 37.72343)

In [34]:
SF_joined2.stop_sequence.nunique()

93

In [35]:
len(SF_joined2)

165

* After dropping duplicate stop IDs, now some of the sequences are out of order/missing.

In [36]:
SF_joined3 = SF_joined2.drop_duplicates(subset=['stop_id'])

In [43]:
SF_joined3.sort_values('stop_sequence').head(50)

,trip_id,departure_time,stop_sequence,stop_id,itp_id,stop_lat,stop_lon,stop_name,_merge,geometry
14,9987569,13:36:00,1,4648,282,37.722895,-122.394842,Fitzgerald Ave & Keith St,both,POINT (-122.39484 37.72290)
156,9987569,13:36:36,2,4647,282,37.722028,-122.393320,Fitzgerald Ave & Jennings St,both,POINT (-122.39332 37.72203)
149,9987569,13:37:21,3,4646,282,37.720966,-122.391453,Fitzgerald Ave & Ingalls St,both,POINT (-122.39145 37.72097)
157,9987569,13:38:09,4,4645,282,37.719921,-122.389587,Fitzgerald Ave & Hawes St,both,POINT (-122.38959 37.71992)
103,9987569,13:39:10,5,4784,282,37.718234,-122.388272,Gilman Ave & Griffith St,both,POINT (-122.38827 37.71823)
51,9987569,13:39:45,6,5955,282,37.717502,-122.386990,Gilman Ave and Giants Dr,both,POINT (-122.38699 37.71750)
88,9987569,13:40:52,7,5115,282,37.717012,-122.389212,Ingerson Ave & Griffith St,both,POINT (-122.38921 37.71701)
138,9987569,13:41:35,8,5116,282,37.718039,-122.390998,Ingerson Ave & Hawes St,both,POINT (-122.39100 37.71804)
52,9987569,13:42:14,9,4976,282,37.719198,-122.390012,Hawes St & Gilman Ave,both,POINT (-122.39001 37.71920)
162,9987569,13:42:58,10,4785,282,37.720350,-122.391729,Gilman Ave & Ingalls St,both,POINT (-122.39173 37.72035)
139,9987569,13:43:43,11,4786,282,37.721413,-122.393595,Gilman Ave & Jennings St,both,POINT (-122.39360 37.72141)
53,9987569,13:44:27,12,4783,282,37.722458,-122.395415,Gilman Ave & 3rd St,both,POINT (-122.39541 37.72246)
54,9987569,13:45:18,13,5902,282,37.723012,-122.397946,Paul Ave & Gould St,both,POINT (-122.39795 37.72301)
121,9987569,13:45:41,14,5901,282,37.723289,-122.399080,Paul Ave & Crane St,both,POINT (-122.39908 37.72329)
104,9987569,13:46:12,15,5899,282,37.723647,-122.400591,Paul Ave & Bay Shore Blvd,both,POINT (-122.40059 37.72365)
122,9987569,13:46:32,16,5904,282,37.723879,-122.401576,Paul Ave & San Bruno Ave,both,POINT (-122.40158 37.72388)
55,9987569,13:48:00,17,5350,282,37.721541,-122.401394,Mansell St & San Bruno Ave,both,POINT (-122.40139 37.72154)
123,9987569,13:48:26,18,5337,282,37.721096,-122.403067,Mansell St & Brussels St,both,POINT (-122.40307 37.72110)
140,9987569,13:48:45,19,5342,282,37.720766,-122.404338,Mansell St & Goettingen St,both,POINT (-122.40434 37.72077)
56,9987569,13:48:57,20,5352,282,37.720525,-122.405117,Mansell St & Somerset St,both,POINT (-122.40512 37.72053)
150,9987569,13:49:25,21,5343,282,37.720098,-122.406916,Mansell St & Hamilton St,both,POINT (-122.40692 37.72010)
15,9987569,13:50:32,23,5353,282,37.718957,-122.411257,Mansell St & University St,both,POINT (-122.41126 37.71896)
58,9987569,13:49:55,23,5339,282,37.719581,-122.408886,Mansell St & Dartmouth St,both,POINT (-122.40889 37.71958)
124,9987569,13:51:22,25,5345,282,37.718119,-122.414464,Mansell St & John F Shelley Dr,both,POINT (-122.41446 37.71812)
105,9987569,13:52:29,25,5347,282,37.718897,-122.418804,Mansell St & John F Shelley Dr,both,POINT (-122.41880 37.71890)
89,9987569,13:54:58,27,5920,282,37.718961,-122.427062,Persia Ave & Prague St,both,POINT (-122.42706 37.71896)
60,9987569,13:53:34,27,5909,282,37.717791,-122.422779,Persia Ave & Brazil Ave,both,POINT (-122.42278 37.71779)
126,9987569,13:55:26,29,5914,282,37.719728,-122.428676,Persia Ave & Moscow St,both,POINT (-122.42868 37.71973)
158,9987569,13:55:39,30,5907,282,37.720112,-122.429467,Persia Ave & Athens St,both,POINT (-122.42947 37.72011)
107,9987569,13:56:07,30,5916,282,37.720880,-122.431070,Persia Ave & Naples St,both,POINT (-122.43107 37.72088)
141,9987569,13:57:02,32,5918,282,37.722406,-122.434276,Persia Ave & Paris St,both,POINT (-122.43428 37.72241)
62,9987569,13:56:35,32,5910,282,37.721638,-122.432673,Persia Ave & Madrid St,both,POINT (-122.43267 37.72164)
163,9987569,13:57:29,33,5912,282,37.723147,-122.435845,Persia Ave & Mission St,both,POINT (-122.43585 37.72315)
152,9987569,13:58:50,35,7638,282,37.723433,-122.440816,Ocean Ave & Otsego Ave,both,POINT (-122.44082 37.72343)
64,9987569,13:58:18,35,5782,282,37.723670,-122.438670,Ocean Ave & Cayuga Ave,both,POINT (-122.43867 37.72367)
66,9987569,14:00:00,36,5804,282,37.723004,-122.444951,Ocean Ave & San Jose Ave,both,POINT (-122.44495 37.72300)
17,9987569,14:00:43,38,7804,282,37.723031,-122.446932,Ocean Ave & I-280 On Ramp,both,POINT (-122.44693 37.72303)
19,9987569,14:01:45,39,5790,282,37.723022,-122.449784,Ocean Ave & Howth St,both,POINT (-122.44978 37.72302)
21,9987569,14:03:20,40,5794,282,37.723459,-122.453999,Ocean Ave & Lee St,both,POINT (-122.45400 37.72346)
68,9987569,14:04:17,40,5975,282,37.723638,-122.456233,Plymouth Ave & Ocean Ave,both,POINT (-122.45623 37.72364)
70,9987569,14:05:05,41,5961,282,37.721934,-122.456232,Plymouth Ave & Holloway Ave,both,POINT (-122.45623 37.72193)
91,9987569,14:05:56,43,5960,282,37.720113,-122.456221,Plymouth Ave & Grafton Ave,both,POINT (-122.45622 37.72011)
23,9987569,14:07:02,44,7194,282,37.720104,-122.459072,GRAFTON AVE & Capitol AVE,both,POINT (-122.45907 37.72010)
93,9987569,14:06:17,44,7193,282,37.720104,-122.457034,GRAFTON AVE & PLYMOUTH AVE,both,POINT (-122.45703 37.72010)
72,9987569,14:07:46,45,7195,282,37.720095,-122.461111,GRAFTON AVE & JULES AVE,both,POINT (-122.46111 37.72010)
143,9987569,14:08:38,47,4246,282,37.719988,-122.463459,Garfield St & Bright St,both,POINT (-122.46346 37.71999)
128,9987569,14:09:18,47,7196,282,37.719764,-122.465234,GARFIELD ST & VICTORIA ST,both,POINT (-122.46523 37.71976)
95,9987569,14:10:17,49,4253,282,37.719746,-122.467937,Garfield St & Vernon St,both,POINT (-122.46794 37.71975)
145,9987569,14:10:56,50,4248,282,37.719737,-122.469735,Garfield St & Byxbee St,both,POINT (-122.46974 37.71974)
130,9987569,14:11:35,50,4245,282,37.719719,-122.471533,Garfield St & Beverly St,both,POINT (-122.47153 37.71972)

In [38]:
#SF_joined4.sort_values('stop_sequence').head()

In [39]:
#SF_joined4.to_file('SF_joined4.geojson', driver='GeoJSON')