# Exercise 3:
<b>Instructions</b>
* Keep a subset of columns and clean up column names (no spaces, newlines, etc):
    * columns related to identifying the agency
    * population, passenger trips
    * transit mode
    * at least 3 service metric variables, normalized and not normalized
* Deal with duplicates - what is the unit for each row? What is the unit for desired analysis? Should an agency appear multiple times, and if so, why?
* Aggregate at least 2 ways and show an interesting comparison, after dealing with duplicates somehow (either aggregation and/or defining what the unit of analysis is)
* Calculate weighted average after the aggregation for the service metrics
* Decide on one type of chart to visualize, and generalize it as a function
* Make charts using the function

### Helpful Hints for Functions
* Opportunities are from components that are generalizable in making a chart
* Maybe these components need the same lines of code to clean them
* You can always further define variables within a function
* You can always use f-strings within functions to make slight modifications to the parameters you pass

## Reading in my file & cleaning it up

In [1]:
import pandas as pd
import numpy as np
import shared_utils
import altair as alt
from shared_utils import altair_utils 

pd.set_option('display.max_columns', None)

/opt/conda/lib/python3.9/site-packages/geopandas/_compat.py:111: UserWarning: The Shapely GEOS version (3.9.1-CAPI-1.14.2) is incompatible with the GEOS version PyGEOS was compiled with (3.10.1-CAPI-1.16.0). Conversions between both will be slow.
  warnings.warn(

In [2]:
GCS_FILE_PATH = "gs://calitp-analytics-data/data-analyses/bus_service_increase/"
FILE_NAME = "ntd_metrics_2019.csv"
df2 = pd.read_csv(f"{GCS_FILE_PATH}{FILE_NAME}")

In [3]:
#cleaning up columns
df2.columns = df2.columns.str.strip().str.replace(' ', '_')

## Subsetting for the 3 performance metrics & agency identifiers.

<b> Just notes on the different abbreviations
* TOS: Types of Service

* MB: Driving a bus

* DO: Vehicle Maintenance 

* VOMS: vehicles operated in annual maximum service

In [4]:
list(df2.columns)

['Agency',
 'City',
 'State',
 'Legacy_NTD_ID',
 'NTD_ID',
 'Organization_Type',
 'Reporter_Type',
 'Primary_UZA\n_Population',
 'Agency_VOMS',
 'Mode',
 'TOS',
 'Mode_VOMS',
 'Ratios:',
 'Fare_Revenues_per_Unlinked_Passenger_Trip',
 'Fare_Revenues_per_Unlinked_Passenger_Trip_Questionable',
 'Fare_Revenues_per_Total_Operating_Expense_(Recovery_Ratio)',
 'Fare_Revenues_per_Total_Operating_Expense_(Recovery_Ratio)_Questionable',
 'Cost_per\n_Hour',
 'Cost_per_Hour_Questionable',
 'Passengers_per_Hour',
 'Passengers_per_Hour_Questionable',
 'Cost_per_Passenger',
 'Cost_per_Passenger_Questionable',
 'Cost_per_Passenger_Mile',
 'Cost_per_Passenger_Mile_Questionable',
 'Source_Data:',
 'Fare_Revenues_Earned',
 'Fare_Revenues_Earned_Questionable',
 'Total_Operating_Expenses',
 'Total_Operating_Expenses_Questionable',
 'Unlinked_Passenger_Trips',
 'Unlinked_Passenger_Trips_Questionable',
 'Vehicle_Revenue_Hours',
 'Vehicle_Revenue_Hours_Questionable',
 'Passenger_Miles',
 'Passenger_Miles_Questionable',
 'Vehicle_Revenue_Miles',
 'Vehicle_Revenue_Miles_Questionable',
 'Any_data_questionable?',
 'Unnamed:_39',
 'Unnamed:_40',
 'Unnamed:_41',
 '1',
 'Unnamed:_43',
 'Unnamed:_44']

In [5]:
df3 = df2[['Agency', 'City', 'State', 'Legacy_NTD_ID', 'NTD_ID',
    'Primary_UZA\n_Population', 'Mode','Cost_per\n_Hour','Passengers_per_Hour','Cost_per_Passenger','TOS','Unlinked_Passenger_Trips','Total_Operating_Expenses']]

In [6]:
df3 = df3.rename(columns = {'Primary_UZA\n_Population': 'Primary_Population', 'Cost_per\n_Hour': 'Cost_per_hour'}) #renaming columns

In [7]:
print(f"There are: {len(df3)} rows before any filtering")

There are: 3685 rows before any filtering

In [8]:
df3.head(2)

,Agency,City,State,Legacy_NTD_ID,NTD_ID,Primary_Population,Mode,Cost_per_hour,Passengers_per_Hour,Cost_per_Passenger,TOS,Unlinked_Passenger_Trips,Total_Operating_Expenses
0,MTA New York City Transit,New York,NY,2008,20008,"18,351,295",HR,$267.97,139.6,$1.92,DO,"2,712,521,697","$5,206,727,193"
1,MTA New York City Transit,New York,NY,2008,20008,"18,351,295",CB,$393.55,18.6,$21.13,DO,"11,477,164","$242,520,835"

## Deal with Duplicates: What is the unit for each row? What is the unit for desired analysis? Should an agency appear multiple times, and if so, why?

* The unit for each row is the mode of transportation by agency & geography, looking at the cost per hour of operating the vehicle, how many passengers boarded per hour, total unlinked trips, cost per passenger, etc. 

* An agency should appear multiple times as some modes of transportation are contracted out to either vendors. Additionally, there are agencies in different states that have similar or even the same names.

In [9]:
#looking at duplicates...these are just NA values. 
duplicateRowsDF = df3[df3.duplicated()]
duplicateRowsDF

,Agency,City,State,Legacy_NTD_ID,NTD_ID,Primary_Population,Mode,Cost_per_hour,Passengers_per_Hour,Cost_per_Passenger,TOS,Unlinked_Passenger_Trips,Total_Operating_Expenses
3681,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3682,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3683,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3684,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
#dropping NA
df3 = df3.dropna()

In [11]:
print(f"Number of unique agencies after we deduplicated: {df3.Agency.nunique()}")

Number of unique agencies after we deduplicated: 1955

In [12]:
print(f"There are: {len(df3)} rows after  dropping duplicates")

There are: 3394 rows after  dropping duplicates

In [13]:
#looking at the few of the agencies that still have duplicates to see why...
df3[(df3.Agency.str.contains("Southern Teton Area Rapid Transit"))]

,Agency,City,State,Legacy_NTD_ID,NTD_ID,Primary_Population,Mode,Cost_per_hour,Passengers_per_Hour,Cost_per_Passenger,TOS,Unlinked_Passenger_Trips,Total_Operating_Expenses
1759,Southern Teton Area Rapid Transit,Jackson,WY,8R05-010,8R05-80188,0,DR,$22.40,1.0,$21.46,DO,"5,244","$112,528"
1761,Southern Teton Area Rapid Transit,Jackson,WY,8R05-010,8R05-80188,0,MB,$71.66,20.3,$3.53,DO,"1,098,224","$3,875,238"
3384,Southern Teton Area Rapid Transit,Jackson,WY,8R05-010,0R01-80188,0,MB,$146.39,15.4,$9.52,DO,"33,383","$317,816"

In [14]:
#looking at the few of the agencies that still have duplicates to see why...some agencies have the same name in didfferent states
df3[(df3.Agency.str.contains("Union County Transit"))]

,Agency,City,State,Legacy_NTD_ID,NTD_ID,Primary_Population,Mode,Cost_per_hour,Passengers_per_Hour,Cost_per_Passenger,TOS,Unlinked_Passenger_Trips,Total_Operating_Expenses
2849,Union County Transit,LIBERTY,IN,5R02-038,5R02-50387,0,DR,$34.50,1.7,$20.13,DO,"24,582","$494,890"
3550,Union County Transit,Blairsville,GA,4R03-012,4R03-41145,0,DR,$22.69,1.6,$14.24,DO,"6,180","$87,989"

In [15]:
#some agencies have VERY similar names in different states...The transit agency Jackson County appears in both NC and GA
df3[(df3.Agency.str.contains("Jackson County"))]

,Agency,City,State,Legacy_NTD_ID,NTD_ID,Primary_Population,Mode,Cost_per_hour,Passengers_per_Hour,Cost_per_Passenger,TOS,Unlinked_Passenger_Trips,Total_Operating_Expenses
1526,"Jackson County Transportation, Inc.",Marianna,FL,4R02-019,4R02-41198,0,DR,$52.98,1.4,$38.23,DO,"37,567","$1,436,173"
1557,"Jackson County Transportation, Inc.",Marianna,FL,4R02-019,4R02-41198,0,MB,$31.76,2.8,$11.49,DO,"2,195","$25,216"
1981,"Delaware, Dubuque & Jackson County Regional Tr...",Dubuque,IA,7R01-008,7R01-70136,0,DR,$66.81,3.6,$18.55,DO,"99,025","$1,837,191"
2047,Jackson County Mass Transit District,Carbondale,IL,5204,50204,"67,821",MB,$47.76,3.3,$14.67,DO,"93,691","$1,374,554"
2614,Jackson County,Sylva,NC,4R06-023,4R06-41167,0,DR,$47.40,1.6,$28.92,DO,"18,663","$539,672"
2660,Jackson County,Sylva,NC,4R06-023,4R06-41167,0,MB,$47.58,3.0,$15.69,DO,"8,004","$125,576"
2953,Jackson County Council on Aging,Scottsboro,AL,4R01-016,4R01-41180,0,DR,$40.65,2.9,$14.25,DO,"29,346","$418,250"
3370,Jackson County,Jefferson,GA,4R03-009,4R03-41154,0,DR,$23.39,1.7,$14.09,DO,"12,285","$173,101"

In [16]:
#same thing, there's a Valley Transit in Arkansas and in Washington.
df3[(df3.Agency.str.contains("Valley Transit"))]

,Agency,City,State,Legacy_NTD_ID,NTD_ID,Primary_Population,Mode,Cost_per_hour,Passengers_per_Hour,Cost_per_Passenger,TOS,Unlinked_Passenger_Trips,Total_Operating_Expenses
328,Victor Valley Transit Authority,Hesperia,CA,9148,90148,"328,454",CB,$109.56,5.0,$22.06,PT,"35,756","$788,860"
329,Victor Valley Transit Authority,Hesperia,CA,9148,90148,"328,454",MB,$85.55,7.5,$11.39,PT,"1,442,723","$16,436,694"
330,Victor Valley Transit Authority,Hesperia,CA,9148,90148,"328,454",DR,$89.98,3.1,$29.38,PT,"189,182","$5,557,594"
331,Victor Valley Transit Authority,Hesperia,CA,9148,90148,"328,454",VP,$32.93,5.3,$6.21,PT,"572,713","$3,555,942"
387,Pioneer Valley Transit Authority,Springfield,MA,1008,10008,"621,300",MB,$106.10,27.4,$3.88,PT,"10,120,344","$39,216,072"
388,Pioneer Valley Transit Authority,Springfield,MA,1008,10008,"621,300",DR,$53.30,1.4,$38.27,PT,"260,582","$9,973,167"
514,Minnesota Valley Transit Authority,Burnsville,MN,5222,50519,"2,650,890",MB,$158.92,15.0,$10.62,PT,"2,547,655","$27,060,351"
684,Antelope Valley Transit Authority,Lancaster,CA,9121,90121,"341,219",MB,$121.34,13.0,$9.32,PT,"2,013,685","$18,771,318"
685,Antelope Valley Transit Authority,Lancaster,CA,9121,90121,"341,219",CB,$134.13,9.3,$14.37,PT,"288,183","$4,142,476"
686,Antelope Valley Transit Authority,Lancaster,CA,9121,90121,"341,219",DR,$56.05,2.3,$24.88,PT,"50,600","$1,258,678"
688,Tri-Valley Transit Inc,Middlebury,VT,1R06-001,1R06-10143,0,MB,$72.87,5.6,$13.02,DO,"105,277","$1,370,321"
689,Tri-Valley Transit Inc,Middlebury,VT,1R06-001,1R06-10143,0,DR,$28.12,1.4,$20.29,DO,"119,556","$2,425,301"
690,Tri-Valley Transit Inc,Middlebury,VT,1R06-001,1R06-10143,0,CB,$80.41,3.5,$23.27,DO,"57,918","$1,347,724"
767,"City of Appleton, dba: Valley Transit",Appleton,WI,5001,50001,"216,154",DR,$47.23,3.4,$13.85,PT,"150,286","$2,081,046"
771,"City of Appleton, dba: Valley Transit",Appleton,WI,5001,50001,"216,154",MB,$95.67,15.9,$6.03,DO,"939,541","$5,661,984"
774,"City of Appleton, dba: Valley Transit",Appleton,WI,5001,50001,"216,154",MB,$50.65,3.5,$14.62,PT,"22,437","$327,960"
836,Livermore / Amador Valley Transit Authority,Livermore,CA,9144,90144,"615,968",MB,$121.26,13.2,$9.19,PT,"1,660,443","$15,253,896"
839,Livermore / Amador Valley Transit Authority,Livermore,CA,9144,90144,"615,968",DR,$43.74,1.2,$36.70,PT,"46,108","$1,692,058"
929,Concho Valley Transit District,San Angelo,TX,6102,60102,"92,984",DR,$79.26,2.0,$40.24,DO,"88,063","$3,543,343"
932,Concho Valley Transit District,San Angelo,TX,6102,60102,"92,984",MB,$82.59,11.0,$7.48,DO,"211,728","$1,584,665"
1321,"City of Williamsport, dba: River Valley Transit",Williamsport,PA,3026,30026,"56,142",DR,$60.92,2.2,$27.49,PT,"4,148","$114,039"
1326,"City of Williamsport, dba: River Valley Transit",Williamsport,PA,3026,30026,"56,142",MB,$141.67,23.0,$6.15,DO,"1,310,695","$8,063,312"
1332,"City of Williamsport, dba: River Valley Transit",Williamsport,PA,3026,30026,"56,142",DR,$96.00,1.4,$68.57,DO,7,$480
1598,Treasure Valley Transit,Nampa,ID,0R01-012,00373,"151,499",DR,$51.78,1.9,$27.52,DO,"45,719","$1,258,248"
1600,Treasure Valley Transit,Nampa,ID,0R01-012,00373,"151,499",MB,$73.37,4.5,$16.43,DO,"70,882","$1,164,627"
1632,Suwannee Valley Transit Authority,Live Oak,FL,4R02-005,4R02-41050,0,DR,$67.59,2.4,$28.53,DO,"57,847","$1,650,477"
1663,Suwannee Valley Transit Authority,Live Oak,FL,4R02-005,4R02-41050,0,MB,$51.47,8.6,$6.02,DO,"4,046","$24,346"
1669,Cache Valley Transit District,Logan,UT,8028,80028,"94,983",DR,$89.12,2.4,$36.81,DO,"28,079","$1,033,540"
1683,Colorado Valley Transit District,Columbus,TX,6R05-031,6R05-60238,0,DR,$37.56,2.4,$15.85,DO,"99,491","$1,577,080"
1692,Cache Valley Transit District,Logan,UT,8028,80028,"94,983",MB,$96.17,26.7,$3.61,DO,"1,424,788","$5,141,255"
1701,Valley Transit,Walla Walla,WA,0064,00064,"55,805",DR,$122.27,3.3,$37.55,DO,"44,945","$1,687,852"
1707,Valley Transit,Walla Walla,WA,0064,00064,"55,805",VP,$107.08,4.6,$23.52,DO,"6,459","$151,942"
1714,Mid Mon Valley Transit Authority,Charleroi,PA,3061,30061,"66,086",MB,$95.68,6.7,$14.26,PT,"288,056","$4,107,245"
1731,Valley Transit,Walla Walla,WA,0064,00064,"55,805",MB,$129.77,21.5,$6.02,DO,"613,298","$3,693,781"
1846,Potomac Valley Transit Authority,Petersburg,WV,3R05-018,3R05-30135,0,DR,$69.04,2.8,$24.49,DO,"22,892","$560,551"
1885,Potomac Valley Transit Authority,Petersburg,WV,3R05-018,3R05-30135,0,MB,$66.24,3.8,$17.57,DO,"73,946","$1,299,360"
1937,"Mid-Ohio Valley Transit Authority, dba: Easy R...",Parkersburg,WV,3003,30003,"67,229",MB,$78.58,11.2,$7.01,DO,"485,494","$3,403,144"
1955,"Mid-Ohio Valley Transit Authority, dba: Easy R...",Parkersburg,WV,3003,30003,"67,229",DR,$56.20,2.5,$22.07,DO,"7,097","$156,630"
1967,"City of Simi Valley, dba: Simi Valley Transit",Simi Valley,CA,9050,90050,"125,206",MB,$149.03,10.0,$14.93,DO,"266,718","$3,983,229"
2005,"City of Simi Valley, dba: Simi Valley Transit",Simi Valley,CA,9050,90050,"125,206",DR,$186.20,2.4,$78.90,DO,"40,651","$3,207,494"
2330,Valley Transit District,Derby,CT,1042,10042,"923,311",DR,$96.60,3.0,$31.90,DO,"48,529","$1,548,038"
2480,Valley Transit,Wasilla,AK,0R04-002,0R04-00327,0,DR,$91.09,1.6,$56.71,DO,"9,545","$541,318"
2490,Valley Transit,Wasilla,AK,0R04-002,0R04-00327,0,MB,$80.70,4.6,$17.41,DO,"51,456","$895,818"
3271,Glacier Valley Transit,Girdwood,AK,0R04-011,0R04-00345,0,MB,$55.53,12.5,$4.44,PT,"93,825","$416,318"

## Changing mode abbrevations 
* Mapping a few of the abbreviations to the full name for ease.

* [Transit.dot.gov's data dictionary](https://www.transit.dot.gov/ntd/national-transit-database-ntd-glossary#C)

#### Trying to map abbreviations with df.apply
Write df.apply statement lambda function.

Tiffany's code

```
df["mode_full_name"] = df.apply(lambda x: "Other" if x.mode_full_name=="" else x.mode_full_name, axis=1) #axis=1, is row

RAIL = ["LR", "HR", "CR"]
BUS = ["CB", "MB", "AR", "DR"]

def replace_modes(row):
    if RAIL in row.Mode:
        return "rail"
    elif BUS in row.Mode:
        return "bus"
    else:
        return "other"
        
df["mode_full_name"] = df.apply(lambda x: replace_modes(x), axis=1)
```

In [17]:
df3.Mode.unique().tolist()

['HR',
 'CB',
 'MB',
 'DR',
 'RB',
 'CR',
 'LR',
 'VP',
 'YR',
 'DT',
 'FB',
 'TB',
 'SR',
 'PB',
 'MG',
 'CC',
 'IP',
 'TR',
 'AR']

In [18]:
#creating a list for all rail and all bus related modes of transportation.
RAIL = ['HR',
'DR', 'CR', 'LR',
'YR', 'SR',
'TR',
'AR']

BUS = [
 'CB',
 'MB',
 'RB',
 'FB',
 'TB','PB']

### HELP This didn't work for me, error message says "TypeError: 'in <string>' requires string as left operand, not list" but when I convert it into a string, it just puts everything in the other category.

In [19]:
def replace_modes(row):
    if row.Mode in RAIL:
        return "Rail"
    elif row.Mode in BUS:
        return "Bus"
    else:
        return "Other"

In [20]:
df3["mode_full_name_test"] = df3.apply(lambda x: replace_modes(x), axis=1)

In [21]:
df3.head(3)

,Agency,City,State,Legacy_NTD_ID,NTD_ID,Primary_Population,Mode,Cost_per_hour,Passengers_per_Hour,Cost_per_Passenger,TOS,Unlinked_Passenger_Trips,Total_Operating_Expenses,mode_full_name_test
0,MTA New York City Transit,New York,NY,2008,20008,"18,351,295",HR,$267.97,139.6,$1.92,DO,"2,712,521,697","$5,206,727,193",Rail
1,MTA New York City Transit,New York,NY,2008,20008,"18,351,295",CB,$393.55,18.6,$21.13,DO,"11,477,164","$242,520,835",Bus
2,MTA New York City Transit,New York,NY,2008,20008,"18,351,295",MB,$219.87,56.6,$3.88,DO,"691,616,614","$2,685,918,268",Bus

#### Trying to map it neater

In [22]:
df3['Full_Mode_Name'] = np.nan

In [23]:
df3.loc[df3.Mode.isin(['CB','MB','RB','FB','TB','PB']),  'Full_Mode_Name'] = 'Bus'
df3.loc[df3.Mode.isin(['HR','DR','CR','LR','YR','SR','TR','AR']), 'Full_Mode_Name'] = 'Rail'

In [24]:
df3[['Full_Mode_Name']] = df3[['Full_Mode_Name']].fillna(value= 'Other')

In [25]:
df3.Full_Mode_Name.value_counts()

Rail     1843
Bus      1346
Other     205
Name: Full_Mode_Name, dtype: int64

## Cleaning up columns

In [26]:
(df3.columns)

Index(['Agency', 'City', 'State', 'Legacy_NTD_ID', 'NTD_ID',
       'Primary_Population', 'Mode', 'Cost_per_hour', 'Passengers_per_Hour',
       'Cost_per_Passenger', 'TOS', 'Unlinked_Passenger_Trips',
       'Total_Operating_Expenses', 'mode_full_name_test', 'Full_Mode_Name'],
      dtype='object')

In [27]:
#cleaning up string columns
for i in ['Agency', 'City', 'State', 'Full_Mode_Name']:
    df3[i] = df3[i].str.strip().replace(',', '').astype({i: str})

In [28]:
df3["Cost_per_Passenger"].replace({"1,218.00": "1218"}, inplace=True)

In [29]:
#cleaning up the numeric columns
for i in ['Primary_Population', 'Cost_per_hour', 'Passengers_per_Hour',
       'Cost_per_Passenger', 'Unlinked_Passenger_Trips', 'Total_Operating_Expenses']:
    df3[i] = df3[i].replace({'\$':''}, regex=True).replace(',','', regex= True).astype({i: float})

In [30]:
#making sure all the data types are accurate
df3.dtypes

Agency                       object
City                         object
State                        object
Legacy_NTD_ID                object
NTD_ID                       object
Primary_Population          float64
Mode                         object
Cost_per_hour               float64
Passengers_per_Hour         float64
Cost_per_Passenger          float64
TOS                          object
Unlinked_Passenger_Trips    float64
Total_Operating_Expenses    float64
mode_full_name_test          object
Full_Mode_Name               object
dtype: object

In [31]:
#dropping the old mode 
df3 = df3.drop(columns = ['Mode', 'mode_full_name_test'])

In [32]:
df3.to_csv("./df3.csv", index= False) #just exporting to CSV so I can check it out

# Aggregation & Chart Making

### First Analysis

In [33]:
#filter out just bus for mode
bus = df3[df3["Full_Mode_Name"] == "Bus"]

In [34]:
bus.head(2)

,Agency,City,State,Legacy_NTD_ID,NTD_ID,Primary_Population,Cost_per_hour,Passengers_per_Hour,Cost_per_Passenger,TOS,Unlinked_Passenger_Trips,Total_Operating_Expenses,Full_Mode_Name
1,MTA New York City Transit,New York,NY,2008,20008,18351295.0,393.55,18.6,21.13,DO,11477164.0,2.425208e+08,Bus
2,MTA New York City Transit,New York,NY,2008,20008,18351295.0,219.87,56.6,3.88,DO,691616614.0,2.685918e+09,Bus

In [35]:
first= bus.drop_duplicates().groupby(['State', 'Full_Mode_Name']).agg({'Unlinked_Passenger_Trips': 'sum', 'Total_Operating_Expenses': 'sum' }).reset_index()
first.sort_values(by="Unlinked_Passenger_Trips", ascending= False)

   State Full_Mode_Name  Unlinked_Passenger_Trips  Total_Operating_Expenses
36    NY            Bus              1.026697e+09              4.810735e+09
5     CA            Bus              8.455713e+08              4.665400e+09
16    IL            Bus              2.937754e+08              1.210445e+09
40    PA            Bus              2.414856e+08              1.187525e+09
51    WA            Bus              2.234103e+08              1.613615e+09
46    TX            Bus              2.147267e+08              1.310105e+09
33    NJ            Bus              1.883524e+08              1.220660e+09
10    FL            Bus              1.795735e+08              1.076548e+09
21    MA            Bus              1.431641e+08              6.505592e+08
8     DC            Bus              1.287985e+08              7.587671e+08
22    MD            Bus              9.759595e+07              6.103146e+08
6     CO            Bus              9.274524e+07              4.965811e+08
37    OH            Bus              8.068086e+07              6.195881e+08
24    MI            Bus              7.806410e+07              3.882132e+08
39    OR            Bus              7.504132e+07              4.264264e+08
4     AZ            Bus              7.396926e+07              3.824759e+08
35    NV            Bus              7.252907e+07              2.135737e+08
25    MN            Bus              7.144495e+07              4.581855e+08
11    GA            Bus              7.108250e+07              3.274502e+08
13    HI            Bus              6.555074e+07              2.359979e+08
48    VA            Bus              5.656428e+07              3.591249e+08
29    NC            Bus              5.533892e+07              2.928458e+08
52    WI            Bus              5.293262e+07              2.537729e+08
26    MO            Bus              3.867192e+07              2.785235e+08
7     CT            Bus              3.859783e+07              2.357773e+08
17    IN            Bus              2.646863e+07              1.565983e+08
45    TN            Bus              2.634575e+07              1.707968e+08
47    UT            Bus              2.532996e+07              1.793114e+08
41    PR            Bus              2.425179e+07              1.182774e+08
20    LA            Bus              2.282286e+07              1.522191e+08
14    IA            Bus              2.016510e+07              8.030360e+07
19    KY            Bus              1.936752e+07              1.188063e+08
42    RI            Bus              1.602939e+07              1.018038e+08
34    NM            Bus              1.206557e+07              7.554371e+07
43    SC            Bus              9.543891e+06              6.040178e+07
38    OK            Bus              7.687091e+06              5.004530e+07
9     DE            Bus              7.162651e+06              7.012465e+07
23    ME            Bus              5.891735e+06              3.354590e+07
1     AL            Bus              5.745229e+06              4.698728e+07
31    NE            Bus              5.692434e+06              3.886100e+07
0     AK            Bus              5.580872e+06              4.704565e+07
53    WV            Bus              5.432676e+06              4.096916e+07
18    KS            Bus              5.076250e+06              3.841205e+07
50    VT            Bus              4.981542e+06              3.095329e+07
2     AR            Bus              4.912354e+06              2.562614e+07
32    NH            Bus              3.892081e+06              3.675816e+07
28    MT            Bus              3.529885e+06              2.072505e+07
27    MS            Bus              3.099899e+06              1.669755e+07
15    ID            Bus              2.632672e+06              2.029810e+07
54    WY            Bus              2.076895e+06              8.546181e+06
30    ND            Bus              1.770841e+06              1.206191e+07
44    SD            Bus              1.206809e+06              7.152772e+06
49    VI            Bus              2.441700e+05              1.981738e+06
12    GU            Bus              1.045350e+05              1.406707e+06
3     AS            Bus              1.818000e+03              2.429580e+05

In [36]:
first = first.nlargest(10,'Unlinked_Passenger_Trips')
first["Operating_Expenses_to_Trips"] = first.Total_Operating_Expenses.divide(first.Unlinked_Passenger_Trips)
 
first

,State,Full_Mode_Name,Unlinked_Passenger_Trips,Total_Operating_Expenses,Operating_Expenses_to_Trips
36,NY,Bus,1.026697e+09,4.810735e+09,4.685643
5,CA,Bus,8.455713e+08,4.665400e+09,5.517453
16,IL,Bus,2.937754e+08,1.210445e+09,4.120307
40,PA,Bus,2.414856e+08,1.187525e+09,4.917579
51,WA,Bus,2.234103e+08,1.613615e+09,7.222654
46,TX,Bus,2.147267e+08,1.310105e+09,6.101268
33,NJ,Bus,1.883524e+08,1.220660e+09,6.480721
10,FL,Bus,1.795735e+08,1.076548e+09,5.995027
21,MA,Bus,1.431641e+08,6.505592e+08,4.544150
8,DC,Bus,1.287985e+08,7.587671e+08,5.891117

In [37]:
state_dropdown = first.State.unique().tolist()

In [38]:
input_dropdown = alt.binding_select(options=state_dropdown)
selection = alt.selection_single(fields=['State'], bind=input_dropdown, name='State')

In [39]:
#Just saving this because of the drop down menu 
#def bar_chart(df, x_col, y_col):
   # chart = (alt.Chart(df).mark_bar().encode(
           #      x=alt.X(x_col, title=x_col),
            #     y=alt.Y(y_col, title=y_col),   
              #   color =alt.Color(x_col, scale=alt.Scale(range=altair_utils.FIVETHIRTYEIGHT_CATEGORY_COLORS)),
                # tooltip = [alt.Tooltip(x_col),alt.Tooltip(y_col)])#.add_selection(selection).transform_filter(selection)
          #  )
    
  #  return chart

### HELP I feel like the colors are not working?

In [40]:
def bar_chart(df, x_col, y_col):
    chart = (alt.Chart(df).mark_bar().encode(
                 x=alt.X(x_col, title=x_col),
                 y=alt.Y(y_col, title=y_col),   
                 color =alt.Color(x_col, scale=alt.Scale(range=altair_utils.FIVETHIRTYEIGHT_CATEGORY_COLORS)),
                 tooltip = [alt.Tooltip(x_col),alt.Tooltip(y_col)]).interactive().properties(width=600,height=250)
            )
    
    return chart

In [41]:
chart_one = bar_chart(first, 'State', 'Operating_Expenses_to_Trips')
chart_one

alt.Chart(...)

### Second Analysis

In [42]:
 second = df3.groupby(['Full_Mode_Name']).agg({'Unlinked_Passenger_Trips': 'median', 'Total_Operating_Expenses': 'median' }).reset_index()

In [43]:
second.head(2)

  Full_Mode_Name  Unlinked_Passenger_Trips  Total_Operating_Expenses
0            Bus                  196085.0                 1671697.5
1          Other                   66002.0                  513227.0

In [44]:
chart_two = bar_chart(second, 'Full_Mode_Name', 'Total_Operating_Expenses')
chart_two

alt.Chart(...)

In [45]:
chart_three = bar_chart(second, 'Full_Mode_Name', 'Unlinked_Passenger_Trips')
chart_three

alt.Chart(...)