In [1]:
import os

os.environ["CALITP_BQ_MAX_BYTES"] = str(5_000_000_000_000)

from calitp_data_analysis.sql import query_sql
from calitp_data_analysis.geography_utils import WGS84, CA_NAD83Albers_m

import pandas as pd
import geopandas as gpd

from shared_utils import gtfs_utils_v2

In [2]:
import itables

itables.init_notebook_mode(all_interactive=False)
from itables import show

In [190]:
import numpy as np

### demo locations

service_date	stop_id	daily_arrivals	stop_name	feed_key	meters_from_key	gtfs_dataset_name	analysis_name	geometry
`2026-02-11	70262	56	San Jose Diridon Caltrain Station Southbound	f927889951544b7b4e2ad9dfe4d44dc8	14.446896	Bay Area 511 Caltrain Schedule	Peninsula Corridor Joint Powers Board	POINT (-121.90317 37.32923)`

In [3]:
analysis_date = "2026-02-11"

In [4]:
identifiers = query_sql('''
select t1.feed_key, t1.gtfs_dataset_name, t2.analysis_name
from cal-itp-data-infra.mart_gtfs.fct_daily_schedule_feeds as t1
join cal-itp-data-infra.mart_transit_database.bridge_gtfs_analysis_name_x_ntd as t2
on t1.gtfs_dataset_name = t2.schedule_gtfs_dataset_name
where t1.date = "2026-02-11"

''')

/home/jovyan/data-analyses/.venv/lib/python3.11/site-packages/google/cloud/bigquery/client.py:613: UserWarning: Cannot create BigQuery Storage client, the dependency google-cloud-bigquery-storage is not installed.
  warnings.warn(

In [133]:
# identifiers

In [6]:
identifiers[identifiers.gtfs_dataset_name.str.contains('Santa Clara')]

,feed_key,gtfs_dataset_name,analysis_name
34,eef3ec6d4eda424edca5f8c6330aae15,Bay Area 511 Santa Clara Transit Schedule,Santa Clara Valley Transportation Authority

In [99]:
diridon_stops = query_sql('''
select service_date, stop_id, daily_arrivals, stop_name, pt_geom, feed_key, cast((st_distance(t1.pt_geom, st_geogpoint(-121.90317, 37.32923))) as INT64) as meters_from_key
from cal-itp-data-infra.mart_gtfs.fct_daily_scheduled_stops as t1
where service_date = "2026-02-11"
and st_distance(t1.pt_geom, st_geogpoint(-121.90317, 37.32923)) < 1000
'''
)

/home/jovyan/data-analyses/.venv/lib/python3.11/site-packages/google/cloud/bigquery/client.py:613: UserWarning: Cannot create BigQuery Storage client, the dependency google-cloud-bigquery-storage is not installed.
  warnings.warn(

In [100]:
df = diridon_stops.merge(identifiers, on='feed_key')
df['key_stop_id'] = '70262'

In [101]:
gdf = gpd.GeoDataFrame(data=df, geometry=gpd.GeoSeries.from_wkt(df.pt_geom), crs=WGS84).drop(columns=['pt_geom'])
# gdf.sort_values('meters_from_key')

## From collection to usable data

* need, essentially, a walking distance/time matrix (existing tools do 1 m/s straightline, we could too for now)
* then join to rt, figure out filters/precalc...

In [10]:
trips = gtfs_utils_v2.get_trips(selected_date=analysis_date, operator_feeds=gdf.feed_key)

/home/jovyan/data-analyses/.venv/lib/python3.11/site-packages/google/cloud/bigquery/client.py:613: UserWarning: Cannot create BigQuery Storage client, the dependency google-cloud-bigquery-storage is not installed.
  warnings.warn(

In [11]:
st = gtfs_utils_v2.get_stop_times(selected_date=analysis_date, operator_feeds=gdf.feed_key, trip_df=trips)

In [12]:
st_cols = ['trip_id', 'stop_id', 'feed_key',
           'arrival_time', 'departure_time', 'arrival_sec',
           'departure_sec']
st = st[st_cols]

In [13]:
st.head(3)

,trip_id,stop_id,feed_key,arrival_time,departure_time,arrival_sec,departure_sec
0,118,70122,f927889951544b7b4e2ad9dfe4d44dc8,10:01:00,10:01:00,36060,36060
1,116,70232,f927889951544b7b4e2ad9dfe4d44dc8,10:01:00,10:01:00,36060,36060
2,121,70221,f927889951544b7b4e2ad9dfe4d44dc8,10:12:00,10:12:00,36720,36720

In [102]:
merged = st.merge(trips[['trip_id', 'feed_key', 'route_short_name']], on=['trip_id', 'feed_key']).merge(gdf, on=['stop_id', 'feed_key'])

In [103]:
merged.drop_duplicates(subset=['stop_id']).head(3)

,trip_id,stop_id,feed_key,arrival_time,departure_time,arrival_sec,departure_sec,route_short_name,service_date,daily_arrivals,stop_name,meters_from_key,gtfs_dataset_name,analysis_name,key_stop_id,geometry
0,147,70261,f927889951544b7b4e2ad9dfe4d44dc8,16:28:00,16:28:00,59280,59280,Local Weekday,2026-02-11,56,San Jose Diridon Caltrain Station Northbound,14,Bay Area 511 Caltrain Schedule,Peninsula Corridor Joint Powers Board,70262,POINT (-121.90301 37.32924)
1,416,70262,f927889951544b7b4e2ad9dfe4d44dc8,16:58:00,16:58:00,61080,61080,Limited,2026-02-11,56,San Jose Diridon Caltrain Station Southbound,0,Bay Area 511 Caltrain Schedule,Peninsula Corridor Joint Powers Board,70262,POINT (-121.90317 37.32923)
21,US0831-6411-0640022026-SFD6#POE6-00,229b2dc8-6a3d-4659-9e9a-80b25561f5a0,5f6d3bd4f5d79132418beb28cfcbdd8f,08:30:00,08:55:00,30600,32100,Greyhound US0831,2026-02-11,4,San Jose Diridon Station,195,Flixbus Schedule,FlixBus and Greyhound,70262,POINT (-121.90200 37.33072)

In [104]:
inbound = gdf[gdf.meters_from_key == gdf.meters_from_key.min()]

## Calculations

In [105]:
inbound_st = merged[merged.meters_from_key == merged.meters_from_key.min()].copy()

In [106]:
inbound_cols = ['trip_id', 'feed_key', 'arrival_time', 'arrival_sec', 'key_stop_id']

In [107]:
inbound_st = inbound_st[inbound_cols]
inbound_st.columns = ['inb_' + col for col in inbound_st.columns]

In [108]:
inbound_st.iloc[0:1]

,inb_trip_id,inb_feed_key,inb_arrival_time,inb_arrival_sec,inb_key_stop_id
1,416,f927889951544b7b4e2ad9dfe4d44dc8,16:58:00,61080,70262

In [109]:
outbound_st = merged[merged.meters_from_key != merged.meters_from_key.min()].copy()
outbound_cols = ['trip_id', 'feed_key', 'route_short_name',
                  'analysis_name', 'departure_time', 'departure_sec',
                    'meters_from_key', 'key_stop_id']
outbound_st = outbound_st[outbound_cols]

In [114]:
outbound_st.head(3)

,trip_id,feed_key,route_short_name,analysis_name,departure_time,departure_sec,meters_from_key,key_stop_id
3532,1001020,0cc4c66d9d61e84088a9e5008dcd4041,17,Santa Cruz Metropolitan Transit District,14:12:00,51120,125,70262
3540,1004020,0cc4c66d9d61e84088a9e5008dcd4041,17,Santa Cruz Metropolitan Transit District,06:40:00,24000,125,70262
95,101,f927889951544b7b4e2ad9dfe4d44dc8,Local Weekday,Peninsula Corridor Joint Powers Board,4:43:00,16980,14,70262

### single inbound trip

In [115]:
outbound_st = outbound_st.loc[outbound_st.groupby('trip_id').meters_from_key.idxmin()] # use nearest stop for each trip

In [161]:
df = pd.merge(inbound_st.iloc[0:1], outbound_st, left_on='inb_key_stop_id', right_on='key_stop_id')

In [162]:
df['arrive_depart_seconds'] = df.departure_sec - df.inb_arrival_sec - df.meters_from_key # fixed 1 m/s straight line walk

In [134]:
# df[df.arrive_depart_seconds < 1200].sort_values('arrive_depart_seconds')

In [119]:
def filter_outbound(inbound_row, outbound_df, minutes_cutoff):
    seconds_cutoff = minutes_cutoff * 60
    df = pd.merge(inbound_row, outbound_st, left_on='inb_key_stop_id', right_on='key_stop_id')
    df['arrive_depart_seconds'] = df.departure_sec - df.inb_arrival_sec - df.meters_from_key # fixed 1 m/s straight line walk
    df = df[df.arrive_depart_seconds.abs() <= seconds_cutoff]
    return df.sort_values('arrive_depart_seconds')

In [154]:
# df = filter_outbound(inbound_st.iloc[0:1], outbound_st, minutes_cutoff=10)

In [122]:
df = filter_outbound(inbound_st.iloc[1:2], outbound_st, minutes_cutoff=10)

### fan out all trips?

In [167]:
inbound_st = inbound_st.reset_index(drop=True)

In [168]:
outbound_st = outbound_st.reset_index(drop=True)

In [173]:
outbound_st.shape[0] * inbound_st.shape[0]

82208

In [182]:
many_trips = pd.merge(inbound_st, outbound_st, left_on='inb_key_stop_id', right_on='key_stop_id')

In [183]:
many_trips['arrive_depart_seconds'] = many_trips.departure_sec - many_trips.inb_arrival_sec - many_trips.meters_from_key # fixed 1 m/s straight line walk

In [184]:
many_trips.shape

(82208, 14)

### for display

In [206]:
df = many_trips

In [207]:
df = df[df.arrive_depart_seconds.abs() < 1200].sort_values('arrive_depart_seconds')

In [208]:
def sec_to_m_s(sec):
    sec = int(sec)
    mins = sec // 60
    sec_remain = sec % 60

    return f'{mins}:{sec_remain:0>2}'

In [209]:
display_cols = ['inb_trip_id', 'inb_arrival_time', 'inb_key_stop_id', 'trip_id', 'route_short_name', 'analysis_name', 'departure_time', 'meters_from_key', 'wait_time']

df['wait_time'] = df.arrive_depart_seconds.apply(sec_to_m_s)
df = df[display_cols]

In [211]:
def color_waits(x):
    # print(x, end='')
    split = x.split(':')
    mins = abs(int(split[0]))
    secs = int(split[1])
    total_secs = mins * 60 + secs
    total_secs = -total_secs if x[0] == '-' else total_secs
    # print(f'...{total_secs}')
    if total_secs < 0:
        color = 'red'
    elif total_secs < 30:
        color = 'yellow'
    elif total_secs < 360:
        color = 'green'
    elif total_secs < 600:
        color = 'yellow'
    elif total_secs < 1200:
        color = 'orange'
    return f"background-color: {color};"

## Inbound Stop

In [210]:
inbound

,service_date,stop_id,daily_arrivals,stop_name,feed_key,meters_from_key,gtfs_dataset_name,analysis_name,key_stop_id,geometry
12,2026-02-11,70262,56,San Jose Diridon Caltrain Station Southbound,f927889951544b7b4e2ad9dfe4d44dc8,0,Bay Area 511 Caltrain Schedule,Peninsula Corridor Joint Powers Board,70262,POINT (-121.90317 37.32923)

In [212]:
styled = df.style.apply(lambda col: col.map(color_waits), subset='wait_time')

In [214]:
show(styled,
     layout={'top1': 'searchPanes'},
     columnDefs=[{"searchPanes": {"show": True}, "targets": [1]}],
     searchPanes={"layout": "columns-3", "cascadePanes": True, "columns": [1, 6, 5]},
     allow_html=True,
     pageLength = 50
    )

## Next Steps

* interface, generally
* screen out inbound buses from outbound (many routes end here...)
* include route headsign/direction...