In [1]:
import sys

# sys.path.append("../bus_service_increase")
# sys.path.append("../starter_kit")  # to test out style_df function
sys.path.append("../")
# sys.path.append("../update_vars")

In [4]:
import os
os.getcwd()

'/home/jovyan/data-analyses/ntd/monthly_ridership_report'

In [5]:
from ridership_report_utils import _01_ntd_ridership_utils

ModuleNotFoundError: No module named 'ridership_report_utils'

In [3]:
import update_vars

In [8]:
%%capture
import warnings

warnings.filterwarnings("ignore")
from calitp_data_analysis.sql import query_sql, to_snakecase

import altair as alt
import calitp_data_analysis.magics
import pandas as pd
# from shared_utils.portfolio_utils import label_visualization
# from _starterkit_utils import style_df
from calitp_data_analysis import calitp_color_palette as cp
from explore_monthly_ridership_by_rtpa import sum_by_group
from IPython.display import HTML, Markdown, display
from update_vars import YEAR, MONTH, PUBLIC_FILENAME, YEAR, NTD_MODES, NTD_TOS
from _01_ntd_ridership_utils import ntd_id_to_rtpa_crosswalk, add_change_columns, get_percent_change, sum_by_group

# for testing


# from monthly_ridership_by_rtpa import get_percent_change
# from shared_utils.rt_dates import MONTH_DICT

# Temp file path for testing
GCS_FILE_PATH = "gs://calitp-analytics-data/data-analyses/ntd/"

# alt.renderers.enable("html")
alt.data_transformers.enable("default", max_rows=None)

In [3]:
from functools import cache

from calitp_data_analysis.gcs_pandas import GCSPandas

@cache
def gcs_pandas():
    return GCSPandas()

In [4]:
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

In [5]:
# parameters cell for local
rtpa = "Metropolitan Transportation Commission"  # lots of reporters
# rtpa = "Butte County Association of Governments" # 2 reporters
# rtpa = "San Joaquin Council of Governments" # 4 reporters

In [6]:
%%capture_parameters
rtpa

{"rtpa": "Metropolitan Transportation Commission"}

---

# 02/31/2026 fixing `add_change_column` function
was getting error at the 
>`df = df.assign(
        # unpacks dictionary to use change_col arg
        **{change_col: (df.sort_values(sort_cols).groupby(group_cols)["upt"].apply(lambda x: x.shift(1)))}
    )`

with error message: `TypeError: incompatible index of inserted column with frame index`

In [13]:
data = gcs_pandas().read_parquet("gs://calitp-analytics-data/data-analyses/ntd/ntd_monthly_ridership_2025_December.parquet")

display(
    data.info(),
    data.head()
)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 124764 entries, 0 to 124763
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   ntd_id             124764 non-null  object
 1   agency             124764 non-null  object
 2   reporter_type      124764 non-null  object
 3   period_year_month  124764 non-null  object
 4   period_year        124764 non-null  object
 5   period_month       124764 non-null  object
 6   mode               124764 non-null  object
 7   tos                124764 non-null  object
 8   Status             124764 non-null  object
 9   uza_name           124764 non-null  object
 10  upt                124764 non-null  float64
dtypes: float64(1), object(10)
memory usage: 10.5+ MB

None

,ntd_id,agency,reporter_type,period_year_month,period_year,period_month,mode,tos,Status,uza_name,upt
0,00058,City of Portland,Full Reporter,2020-08,2020,08,TR,PT,Active,"Portland, OR--WA",0.0
1,00058,City of Portland,Full Reporter,2023-06,2023,06,TR,PT,Active,"Portland, OR--WA",112754.0
2,00058,City of Portland,Full Reporter,2022-05,2022,05,TR,PT,Active,"Portland, OR--WA",73336.0
3,00058,City of Portland,Full Reporter,2024-08,2024,08,TR,PT,Active,"Portland, OR--WA",108338.0
4,00058,City of Portland,Full Reporter,2020-04,2020,04,TR,PT,Active,"Portland, OR--WA",19433.0

In [ ]:
monthly_sort_cols = [
        "ntd_id",
        "mode",
        "tos",
        "period_month",
        "period_year",
    ]  # got the order correct with ["period_month", "period_year"]! sorted years with grouped months

monthly_group_cols = ["ntd_id", "mode", "tos"]

monthly_change_col = "previous_y_m_upt"

# df = add_change_columns(
#     data, 
#     sort_cols=monthly_sort_cols, 
#     group_cols=monthly_group_cols, 
#     change_col=monthly_change_col
#     ) #-> this was giving me the same error

In [14]:
# add_change_column function breakdown
if {"period_year", "period_month"}.issubset(data.columns):
        data[["period_year", "period_month"]] = data[["period_year", "period_month"]].astype(int)

In [15]:
data.info() # -> confirm the above is making period year and period month int

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 124764 entries, 0 to 124763
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   ntd_id             124764 non-null  object
 1   agency             124764 non-null  object
 2   reporter_type      124764 non-null  object
 3   period_year_month  124764 non-null  object
 4   period_year        124764 non-null  int64
 5   period_month       124764 non-null  int64
 6   mode               124764 non-null  object
 7   tos                124764 non-null  object
 8   Status             124764 non-null  object
 9   uza_name           124764 non-null  object
 10  upt                124764 non-null  float64
dtypes: float64(1), int64(2), object(8)
memory usage: 10.5+ MB

In [25]:
sort_cols=monthly_sort_cols
group_cols=monthly_group_cols
change_col=monthly_change_col

# initial code
# test_assign = data.assign(
#         # unpacks dictionary to use change_col arg
#         **{change_col: (data.sort_values(sort_cols).groupby(group_cols)["upt"].apply(lambda x: x.shift(1)))}
#     )

# updated code, removed .apply(lambda) section and used .shift instead
test_assign = data.assign(
        # unpacks dictionary to use change_col arg
        **{change_col: (data.sort_values(sort_cols).groupby(group_cols)["upt"].shift(1))}
    )

In [33]:
test_assign[
    (test_assign["uza_name"].str.contains(", CA"))
    & (test_assign["ntd_id"]=="90019")
].sort_values(by=sort_cols)

,ntd_id,agency,reporter_type,period_year_month,period_year,period_month,mode,tos,Status,uza_name,upt,previous_y_m_upt
54843,90019,Sacramento Regional Transit District,Full Reporter,2018-01,2018,1,DR,DO,Active,"Sacramento, CA",629.0,NaN
54872,90019,Sacramento Regional Transit District,Full Reporter,2019-01,2019,1,DR,DO,Active,"Sacramento, CA",9671.0,629.0
54933,90019,Sacramento Regional Transit District,Full Reporter,2020-01,2020,1,DR,DO,Active,"Sacramento, CA",9489.0,9671.0
54977,90019,Sacramento Regional Transit District,Full Reporter,2021-01,2021,1,DR,DO,Active,"Sacramento, CA",21516.0,9489.0
54902,90019,Sacramento Regional Transit District,Full Reporter,2022-01,2022,1,DR,DO,Active,"Sacramento, CA",31512.0,21516.0
54943,90019,Sacramento Regional Transit District,Full Reporter,2023-01,2023,1,DR,DO,Active,"Sacramento, CA",33822.0,31512.0
54951,90019,Sacramento Regional Transit District,Full Reporter,2024-01,2024,1,DR,DO,Active,"Sacramento, CA",38350.0,33822.0
54903,90019,Sacramento Regional Transit District,Full Reporter,2025-01,2025,1,DR,DO,Active,"Sacramento, CA",25968.0,38350.0
54889,90019,Sacramento Regional Transit District,Full Reporter,2018-02,2018,2,DR,DO,Active,"Sacramento, CA",707.0,25968.0
54894,90019,Sacramento Regional Transit District,Full Reporter,2019-02,2019,2,DR,DO,Active,"Sacramento, CA",9994.0,707.0
54971,90019,Sacramento Regional Transit District,Full Reporter,2020-02,2020,2,DR,DO,Active,"Sacramento, CA",11971.0,9994.0
54910,90019,Sacramento Regional Transit District,Full Reporter,2021-02,2021,2,DR,DO,Active,"Sacramento, CA",23399.0,11971.0
54875,90019,Sacramento Regional Transit District,Full Reporter,2022-02,2022,2,DR,DO,Active,"Sacramento, CA",32550.0,23399.0
54970,90019,Sacramento Regional Transit District,Full Reporter,2023-02,2023,2,DR,DO,Active,"Sacramento, CA",35196.0,32550.0
54976,90019,Sacramento Regional Transit District,Full Reporter,2024-02,2024,2,DR,DO,Active,"Sacramento, CA",37824.0,35196.0
54957,90019,Sacramento Regional Transit District,Full Reporter,2025-02,2025,2,DR,DO,Active,"Sacramento, CA",24108.0,37824.0
54863,90019,Sacramento Regional Transit District,Full Reporter,2018-03,2018,3,DR,DO,Active,"Sacramento, CA",1232.0,24108.0
54960,90019,Sacramento Regional Transit District,Full Reporter,2019-03,2019,3,DR,DO,Active,"Sacramento, CA",9963.0,1232.0
54930,90019,Sacramento Regional Transit District,Full Reporter,2020-03,2020,3,DR,DO,Active,"Sacramento, CA",10461.0,9963.0
54842,90019,Sacramento Regional Transit District,Full Reporter,2021-03,2021,3,DR,DO,Active,"Sacramento, CA",27334.0,10461.0
54887,90019,Sacramento Regional Transit District,Full Reporter,2022-03,2022,3,DR,DO,Active,"Sacramento, CA",37442.0,27334.0
54847,90019,Sacramento Regional Transit District,Full Reporter,2023-03,2023,3,DR,DO,Active,"Sacramento, CA",39553.0,37442.0
54916,90019,Sacramento Regional Transit District,Full Reporter,2024-03,2024,3,DR,DO,Active,"Sacramento, CA",39783.0,39553.0
54839,90019,Sacramento Regional Transit District,Full Reporter,2025-03,2025,3,DR,DO,Active,"Sacramento, CA",26787.0,39783.0
54906,90019,Sacramento Regional Transit District,Full Reporter,2018-04,2018,4,DR,DO,Active,"Sacramento, CA",1819.0,26787.0
54964,90019,Sacramento Regional Transit District,Full Reporter,2019-04,2019,4,DR,DO,Active,"Sacramento, CA",9069.0,1819.0
54939,90019,Sacramento Regional Transit District,Full Reporter,2020-04,2020,4,DR,DO,Active,"Sacramento, CA",8265.0,9069.0
54940,90019,Sacramento Regional Transit District,Full Reporter,2021-04,2021,4,DR,DO,Active,"Sacramento, CA",28453.0,8265.0
54956,90019,Sacramento Regional Transit District,Full Reporter,2022-04,2022,4,DR,DO,Active,"Sacramento, CA",35057.0,28453.0
54983,90019,Sacramento Regional Transit District,Full Reporter,2023-04,2023,4,DR,DO,Active,"Sacramento, CA",35735.0,35057.0
54846,90019,Sacramento Regional Transit District,Full Reporter,2024-04,2024,4,DR,DO,Active,"Sacramento, CA",42540.0,35735.0
54917,90019,Sacramento Regional Transit District,Full Reporter,2025-04,2025,4,DR,DO,Active,"Sacramento, CA",29899.0,42540.0
54888,90019,Sacramento Regional Transit District,Full Reporter,2018-05,2018,5,DR,DO,Active,"Sacramento, CA",3594.0,29899.0
54874,90019,Sacramento Regional Transit District,Full Reporter,2019-05,2019,5,DR,DO,Active,"Sacramento, CA",9442.0,3594.0
54931,90019,Sacramento Regional Transit District,Full Reporter,2020-05,2020,5,DR,DO,Active,"Sacramento, CA",9980.0,9442.0
54908,90019,Sacramento Regional Transit District,Full Reporter,2021-05,2021,5,DR,DO,Active,"Sacramento, CA",27709.0,9980.0
54932,90019,Sacramento Regional Transit District,Full Reporter,2022-05,2022,5,DR,DO,Active,"Sacramento, CA",35405.0,27709.0
54861,90019,Sacramento Regional Transit District,Full Reporter,2023-05,2023,5,DR,DO,Active,"Sacramento, CA",38655.0,35405.0
54921,90019,Sacramento Regional Transit District,Full Reporter,2024-05,2024,5,DR,DO,Active,"Sacramento, CA",42396.0,38655.0
54928,90019,Sacramento Regional Transit District,Full Reporter,2025-05,2025,5,DR,DO,Active,"Sacramento, CA",26327.0,42396.0
54972,90019,Sacramento Regional Transit District,Full Reporter,2018-06,2018,6,DR,DO,Active,"Sacramento, CA",4073.0,26327.0
54840,90019,Sacramento Regional Transit District,Full Reporter,2019-06,2019,6,DR,DO,Active,"Sacramento, CA",8477.0,4073.0
54950,90019,Sacramento Regional Transit District,Full Reporter,2020-06,2020,6,DR,DO,Active,"Sacramento, CA",12928.0,8477.0
54909,90019,Sacramento Regional Transit District,Full Reporter,2021-06,2021,6,DR,DO,Active,"Sacramento, CA",29158.0,12928.0
54855,90019,Sacramento Regional Transit District,Full Reporter,2022-06,2022,6,DR,DO,Active,"Sacramento, CA",33512.0,29158.0
54878,90019,Sacramento Regional Transit District,Full Reporter,2023-06,2023,6,DR,DO,Active,"Sacramento, CA",37113.0,33512.0
54978,90019,Sacramento Regional Transit District,Full Reporter,2024-06,2024,6,DR,DO,Active,"Sacramento, CA",37606.0,37113.0
54905,90019,Sacramento Regional Transit District,Full Reporter,2025-06,2025,6,DR,DO,Active,"Sacramento, CA",28607.0,37606.0
54948,90019,Sacramento Regional Transit District,Full Reporter,2018-07,2018,7,DR,DO,Active,"Sacramento, CA",4884.0,28607.0
54914,90019,Sacramento Regional Transit District,Full Reporter,2019-07,2019,7,DR,DO,Active,"Sacramento, CA",9814.0,4884.0
54851,90019,Sacramento Regional Transit District,Full Reporter,2020-07,2020,7,DR,DO,Active,"Sacramento, CA",25598.0,9814.0
54973,90019,Sacramento Regional Transit District,Full Reporter,2021-07,2021,7,DR,DO,Active,"Sacramento, CA",31681.0,25598.0
54897,90019,Sacramento Regional Transit District,Full Reporter,2022-07,2022,7,DR,DO,Active,"Sacramento, CA",31626.0,31681.0
54848,90019,Sacramento Regional Transit District,Full Reporter,2023-07,2023,7,DR,DO,Active,"Sacramento, CA",35914.0,31626.0
54907,90019,Sacramento Regional Transit District,Full Reporter,2024-07,2024,7,DR,DO,Active,"Sacramento, CA",38013.0,35914.0
54923,90019,Sacramento Regional Transit District,Full Reporter,2025-07,2025,7,DR,DO,Active,"Sacramento, CA",28358.0,38013.0
54927,90019,Sacramento Regional Transit District,Full Reporter,2018-08,2018,8,DR,DO,Active,"Sacramento, CA",7385.0,28358.0
54966,90019,Sacramento Regional Transit District,Full Reporter,2019-08,2019,8,DR,DO,Active,"Sacramento, CA",10382.0,7385.0
54845,90019,Sacramento Regional Transit District,Full Reporter,2020-08,2020,8,DR,DO,Active,"Sacramento, CA",24439.0,10382.0
54853,90019,Sacramento Regional Transit District,Full Reporter,2021-08,2021,8,DR,DO,Active,"Sacramento, CA",33069.0,24439.0
54936,90019,Sacramento Regional Transit District,Full Reporter,2022-08,2022,8,DR,DO,Active,"Sacramento, CA",36381.0,33069.0
54857,90019,Sacramento Regional Transit District,Full Reporter,2023-08,2023,8,DR,DO,Active,"Sacramento, CA",41110.0,36381.0
54868,90019,Sacramento Regional Transit District,Full Reporter,2024-08,2024,8,DR,DO,Active,"Sacramento, CA",41882.0,41110.0
54864,90019,Sacramento Regional Transit District,Full Reporter,2025-08,2025,8,DR,DO,Active,"Sacramento, CA",30776.0,41882.0
54946,90019,Sacramento Regional Transit District,Full Reporter,2018-09,2018,9,DR,DO,Active,"Sacramento, CA",6353.0,30776.0
54862,90019,Sacramento Regional Transit District,Full Reporter,2019-09,2019,9,DR,DO,Active,"Sacramento, CA",10449.0,6353.0
54961,90019,Sacramento Regional Transit District,Full Reporter,2020-09,2020,9,DR,DO,Active,"Sacramento, CA",24642.0,10449.0
54899,90019,Sacramento Regional Transit District,Full Reporter,2021-09,2021,9,DR,DO,Active,"Sacramento, CA",34505.0,24642.0
54876,90019,Sacramento Regional Transit District,Full Reporter,2022-09,2022,9,DR,DO,Active,"Sacramento, CA",35150.0,34505.0
54869,90019,Sacramento Regional Transit District,Full Reporter,2023-09,2023,9,DR,DO,Active,"Sacramento, CA",37204.0,35150.0
54871,90019,Sacramento Regional Transit District,Full Reporter,2024-09,2024,9,DR,DO,Active,"Sacramento, CA",39914.0,37204.0
54925,90019,Sacramento Regional Transit District,Full Reporter,2025-09,2025,9,DR,DO,Active,"Sacramento, CA",30184.0,39914.0
54901,90019,Sacramento Regional Transit District,Full Reporter,2018-10,2018,10,DR,DO,Active,"Sacramento, CA",8925.0,30184.0
54856,90019,Sacramento Regional Transit District,Full Reporter,2019-10,2019,10,DR,DO,Active,"Sacramento, CA",11857.0,8925.0
54898,90019,Sacramento Regional Transit District,Full Reporter,2020-10,2020,10,DR,DO,Active,"Sacramento, CA",26198.0,11857.0
54886,90019,Sacramento Regional Transit District,Full Reporter,2021-10,2021,10,DR,DO,Active,"Sacramento, CA",35311.0,26198.0
54849,90019,Sacramento Regional Transit District,Full Reporter,2022-10,2022,10,DR,DO,Active,"Sacramento, CA",37818.0,35311.0
54975,90019,Sacramento Regional Transit District,Full Reporter,2023-10,2023,10,DR,DO,Active,"Sacramento, CA",39988.0,37818.0
54982,90019,Sacramento Regional Transit District,Full Reporter,2024-10,2024,10,DR,DO,Active,"Sacramento, CA",43360.0,39988.0
54985,90019,Sacramento Regional Transit District,Full Reporter,2025-10,2025,10,DR,DO,Active,"Sacramento, CA",31756.0,43360.0
54912,90019,Sacramento Regional Transit District,Full Reporter,2018-11,2018,11,DR,DO,Active,"Sacramento, CA",7233.0,31756.0
54854,90019,Sacramento Regional Transit District,Full Reporter,2019-11,2019,11,DR,DO,Active,"Sacramento, CA",10307.0,7233.0
54974,90019,Sacramento Regional Transit District,Full Reporter,2020-11,2020,11,DR,DO,Active,"Sacramento, CA",23423.0,10307.0
54963,90019,Sacramento Regional Transit District,Full Reporter,2021-11,2021,11,DR,DO,Active,"Sacramento, CA",33702.0,23423.0
54881,90019,Sacramento Regional Transit District,Full Reporter,2022-11,2022,11,DR,DO,Active,"Sacramento, CA",34765.0,33702.0
54850,90019,Sacramento Regional Transit District,Full Reporter,2023-11,2023,11,DR,DO,Active,"Sacramento, CA",36554.0,34765.0
54958,90019,Sacramento Regional Transit District,Full Reporter,2024-11,2024,11,DR,DO,Active,"Sacramento, CA",36386.0,36554.0
54919,90019,Sacramento Regional Transit District,Full Reporter,2025-11,2025,11,DR,DO,Active,"Sacramento, CA",24848.0,36386.0
54835,90019,Sacramento Regional Transit District,Full Reporter,2018-12,2018,12,DR,DO,Active,"Sacramento, CA",7194.0,24848.0
54882,90019,Sacramento Regional Transit District,Full Reporter,2019-12,2019,12,DR,DO,Active,"Sacramento, CA",10205.0,7194.0
54867,90019,Sacramento Regional Transit District,Full Reporter,2020-12,2020,12,DR,DO,Active,"Sacramento, CA",23508.0,10205.0
54947,90019,Sacramento Regional Transit District,Full Reporter,2021-12,2021,12,DR,DO,Active,"Sacramento, CA",33839.0,23508.0
54859,90019,Sacramento Regional Transit District,Full Reporter,2022-12,2022,12,DR,DO,Active,"Sacramento, CA",33501.0,33839.0
54968,90019,Sacramento Regional Transit District,Full Reporter,2023-12,2023,12,DR,DO,Active,"Sacramento, CA",34803.0,33501.0
54949,90019,Sacramento Regional Transit District,Full Reporter,2024-12,2024,12,DR,DO,Active,"Sacramento, CA",35631.0,34803.0
54895,90019,Sacramento Regional Transit District,Full Reporter,2025-12,2025,12,DR,DO,Active,"Sacramento, CA",29813.0,35631.0
54865,90019,Sacramento Regional Transit District,Full Reporter,2025-01,2025,1,DR,PT,Active,"Sacramento, CA",1636.0,NaN
54952,90019,Sacramento Regional Transit District,Full Reporter,2025-02,2025,2,DR,PT,Active,"Sacramento, CA",1858.0,1636.0
54918,90019,Sacramento Regional Transit District,Full Reporter,2025-03,2025,3,DR,PT,Active,"Sacramento, CA",2165.0,1858.0
54883,90019,Sacramento Regional Transit District,Full Reporter,2025-04,2025,4,DR,PT,Active,"Sacramento, CA",2334.0,2165.0
54879,90019,Sacramento Regional Transit District,Full Reporter,2025-05,2025,5,DR,PT,Active,"Sacramento, CA",2500.0,2334.0
54880,90019,Sacramento Regional Transit District,Full Reporter,2025-06,2025,6,DR,PT,Active,"Sacramento, CA",2039.0,2500.0
54926,90019,Sacramento Regional Transit District,Full Reporter,2025-07,2025,7,DR,PT,Active,"Sacramento, CA",1908.0,2039.0
54841,90019,Sacramento Regional Transit District,Full Reporter,2025-08,2025,8,DR,PT,Active,"Sacramento, CA",2058.0,1908.0
54934,90019,Sacramento Regional Transit District,Full Reporter,2025-09,2025,9,DR,PT,Active,"Sacramento, CA",2812.0,2058.0
54945,90019,Sacramento Regional Transit District,Full Reporter,2025-10,2025,10,DR,PT,Active,"Sacramento, CA",3448.0,2812.0
54967,90019,Sacramento Regional Transit District,Full Reporter,2025-11,2025,11,DR,PT,Active,"Sacramento, CA",2747.0,3448.0
54953,90019,Sacramento Regional Transit District,Full Reporter,2025-12,2025,12,DR,PT,Active,"Sacramento, CA",3271.0,2747.0
54980,90019,Sacramento Regional Transit District,Full Reporter,2023-01,2023,1,DR,TN,Active,"Sacramento, CA",4890.0,NaN
54838,90019,Sacramento Regional Transit District,Full Reporter,2024-01,2024,1,DR,TN,Active,"Sacramento, CA",7428.0,4890.0
54959,90019,Sacramento Regional Transit District,Full Reporter,2025-01,2025,1,DR,TN,Active,"Sacramento, CA",8167.0,7428.0
54893,90019,Sacramento Regional Transit District,Full Reporter,2023-02,2023,2,DR,TN,Active,"Sacramento, CA",5072.0,8167.0
54942,90019,Sacramento Regional Transit District,Full Reporter,2024-02,2024,2,DR,TN,Active,"Sacramento, CA",7794.0,5072.0
54984,90019,Sacramento Regional Transit District,Full Reporter,2025-02,2025,2,DR,TN,Active,"Sacramento, CA",7162.0,7794.0
54860,90019,Sacramento Regional Transit District,Full Reporter,2023-03,2023,3,DR,TN,Active,"Sacramento, CA",6229.0,7162.0
54924,90019,Sacramento Regional Transit District,Full Reporter,2024-03,2024,3,DR,TN,Active,"Sacramento, CA",7948.0,6229.0
54935,90019,Sacramento Regional Transit District,Full Reporter,2025-03,2025,3,DR,TN,Active,"Sacramento, CA",7788.0,7948.0
54873,90019,Sacramento Regional Transit District,Full Reporter,2022-04,2022,4,DR,TN,Active,"Sacramento, CA",336.0,7788.0
54955,90019,Sacramento Regional Transit District,Full Reporter,2023-04,2023,4,DR,TN,Active,"Sacramento, CA",6028.0,336.0
54941,90019,Sacramento Regional Transit District,Full Reporter,2024-04,2024,4,DR,TN,Active,"Sacramento, CA",7870.0,6028.0
54962,90019,Sacramento Regional Transit District,Full Reporter,2025-04,2025,4,DR,TN,Active,"Sacramento, CA",7865.0,7870.0
54844,90019,Sacramento Regional Transit District,Full Reporter,2022-05,2022,5,DR,TN,Active,"Sacramento, CA",1670.0,7865.0
54938,90019,Sacramento Regional Transit District,Full Reporter,2023-05,2023,5,DR,TN,Active,"Sacramento, CA",6833.0,1670.0
54929,90019,Sacramento Regional Transit District,Full Reporter,2024-05,2024,5,DR,TN,Active,"Sacramento, CA",7950.0,6833.0
54890,90019,Sacramento Regional Transit District,Full Reporter,2025-05,2025,5,DR,TN,Active,"Sacramento, CA",7945.0,7950.0
54969,90019,Sacramento Regional Transit District,Full Reporter,2022-06,2022,6,DR,TN,Active,"Sacramento, CA",2826.0,7945.0
54834,90019,Sacramento Regional Transit District,Full Reporter,2023-06,2023,6,DR,TN,Active,"Sacramento, CA",6112.0,2826.0
54896,90019,Sacramento Regional Transit District,Full Reporter,2024-06,2024,6,DR,TN,Active,"Sacramento, CA",7539.0,6112.0
54911,90019,Sacramento Regional Transit District,Full Reporter,2025-06,2025,6,DR,TN,Active,"Sacramento, CA",8378.0,7539.0
54913,90019,Sacramento Regional Transit District,Full Reporter,2022-07,2022,7,DR,TN,Active,"Sacramento, CA",3751.0,8378.0
54915,90019,Sacramento Regional Transit District,Full Reporter,2023-07,2023,7,DR,TN,Active,"Sacramento, CA",5535.0,3751.0
54986,90019,Sacramento Regional Transit District,Full Reporter,2024-07,2024,7,DR,TN,Active,"Sacramento, CA",7472.0,5535.0
54877,90019,Sacramento Regional Transit District,Full Reporter,2025-07,2025,7,DR,TN,Active,"Sacramento, CA",8304.0,7472.0
54866,90019,Sacramento Regional Transit District,Full Reporter,2022-08,2022,8,DR,TN,Active,"Sacramento, CA",4271.0,8304.0
54870,90019,Sacramento Regional Transit District,Full Reporter,2023-08,2023,8,DR,TN,Active,"Sacramento, CA",6811.0,4271.0
54885,90019,Sacramento Regional Transit District,Full Reporter,2024-08,2024,8,DR,TN,Active,"Sacramento, CA",8822.0,6811.0
54922,90019,Sacramento Regional Transit District,Full Reporter,2025-08,2025,8,DR,TN,Active,"Sacramento, CA",9804.0,8822.0
54892,90019,Sacramento Regional Transit District,Full Reporter,2022-09,2022,9,DR,TN,Active,"Sacramento, CA",4970.0,9804.0
54944,90019,Sacramento Regional Transit District,Full Reporter,2023-09,2023,9,DR,TN,Active,"Sacramento, CA",6937.0,4970.0
54852,90019,Sacramento Regional Transit District,Full Reporter,2024-09,2024,9,DR,TN,Active,"Sacramento, CA",8425.0,6937.0
54954,90019,Sacramento Regional Transit District,Full Reporter,2025-09,2025,9,DR,TN,Active,"Sacramento, CA",9363.0,8425.0
54837,90019,Sacramento Regional Transit District,Full Reporter,2022-10,2022,10,DR,TN,Active,"Sacramento, CA",5797.0,9363.0
54858,90019,Sacramento Regional Transit District,Full Reporter,2023-10,2023,10,DR,TN,Active,"Sacramento, CA",7789.0,5797.0
54920,90019,Sacramento Regional Transit District,Full Reporter,2024-10,2024,10,DR,TN,Active,"Sacramento, CA",9171.0,7789.0
54965,90019,Sacramento Regional Transit District,Full Reporter,2025-10,2025,10,DR,TN,Active,"Sacramento, CA",10192.0,9171.0
54836,90019,Sacramento Regional Transit District,Full Reporter,2022-11,2022,11,DR,TN,Active,"Sacramento, CA",5218.0,10192.0
54884,90019,Sacramento Regional Transit District,Full Reporter,2023-11,2023,11,DR,TN,Active,"Sacramento, CA",7032.0,5218.0
54979,90019,Sacramento Regional Transit District,Full Reporter,2024-11,2024,11,DR,TN,Active,"Sacramento, CA",7337.0,7032.0
54891,90019,Sacramento Regional Transit District,Full Reporter,2025-11,2025,11,DR,TN,Active,"Sacramento, CA",8154.0,7337.0
54937,90019,Sacramento Regional Transit District,Full Reporter,2022-12,2022,12,DR,TN,Active,"Sacramento, CA",5120.0,8154.0
54904,90019,Sacramento Regional Transit District,Full Reporter,2023-12,2023,12,DR,TN,Active,"Sacramento, CA",7039.0,5120.0
54981,90019,Sacramento Regional Transit District,Full Reporter,2024-12,2024,12,DR,TN,Active,"Sacramento, CA",7632.0,7039.0
54900,90019,Sacramento Regional Transit District,Full Reporter,2025-12,2025,12,DR,TN,Active,"Sacramento, CA",8482.0,7632.0
68771,90019,Sacramento Regional Transit District,Full Reporter,2018-01,2018,1,LR,DO,Active,"Sacramento, CA",757550.0,NaN
68760,90019,Sacramento Regional Transit District,Full Reporter,2019-01,2019,1,LR,DO,Active,"Sacramento, CA",841380.0,757550.0
68759,90019,Sacramento Regional Transit District,Full Reporter,2020-01,2020,1,LR,DO,Active,"Sacramento, CA",903994.0,841380.0
68764,90019,Sacramento Regional Transit District,Full Reporter,2021-01,2021,1,LR,DO,Active,"Sacramento, CA",279101.0,903994.0
68789,90019,Sacramento Regional Transit District,Full Reporter,2022-01,2022,1,LR,DO,Active,"Sacramento, CA",366827.0,279101.0
68746,90019,Sacramento Regional Transit District,Full Reporter,2023-01,2023,1,LR,DO,Active,"Sacramento, CA",496265.0,366827.0
68765,90019,Sacramento Regional Transit District,Full Reporter,2024-01,2024,1,LR,DO,Active,"Sacramento, CA",550184.0,496265.0
68812,90019,Sacramento Regional Transit District,Full Reporter,2025-01,2025,1,LR,DO,Active,"Sacramento, CA",626171.0,550184.0

In [22]:
test_group = data.sort_values(sort_cols).groupby(group_cols)["upt"]

In [23]:
print(test_group.groups)

{('00001', 'DR', 'PT'): [12406, 12553, 12576, 12414, 12542, 12471, 12449, 12541, 12523, 12433, 12479, 12469, 12494, 12516, 12572, 12507, 12411, 12512, 12561, 12490, 12493, 12583, 12438, 12468, 12492, 12484, 12588, 12481, 12575, 12442, 12431, 12443, 12565, 12592, 12505, 12504, 12491, 12569, 12567, 12596, 12437, 12509, 12451, 12486, 12482, 12473, 12430, 12463, 12539, 12571, 12577, 12496, 12457, 12544, 12428, 12454, 12413, 12420, 12563, 12417, 12453, 12540, 12436, 12533, 12557, 12524, 12580, 12589, 12475, 12543, 12459, 12447, 12498, 12497, 12478, 12573, 12409, 12485, 12458, 12552, 12560, 12445, 12446, 12530, 12586, 12416, 12415, 12590, 12477, 12535, 12410, 12467, 12495, 12448, 12517, 12525], ('00001', 'DR', 'TX'): [12566, 12513, 12510, 12472, 12483, 12585, 12488, 12514, 12506, 12456, 12425, 12537, 12531, 12527, 12526, 12591, 12555, 12461, 12593, 12528, 12568, 12538, 12570, 12536, 12440, 12520, 12579, 12466, 12594, 12584, 12547, 12462, 12418, 12499, 12546, 12559, 12545, 12427, 12532, 12460, 12518, 12582, 12426, 12470, 12429, 12439, 12408, 12551, 12556, 12465, 12441, 12435, 12558, 12489, 12550, 12534, 12562, 12574, 12474, 12511, 12487, 12432, 12522, 12519, 12422, 12549, 12421, 12464, 12412, 12455, 12597, 12452, 12508, 12564, 12476, 12587, 12480, 12423, 12521, 12595, 12419, 12554, 12434, 12581, 12578, 12548, 12529, 12503, 12500, 12407, 12515, 12501, 12424, 12502, 12450, 12444], ('00001', 'FB', 'DO'): [61832, 61809, 61777, 61785, 61836, 61826, 61760, 61786, 61781, 61810, 61771, 61789, 61812, 61842, 61814, 61757, 61769, 61764, 61750, 61796, 61783, 61841, 61831, 61794, 61821, 61778, 61799, 61779, 61829, 61751, 61803, 61834, 61775, 61801, 61762, 61791, 61813, 61787, 61805, 61782, 61795, 61808, 61811, 61754, 61788, 61776, 61828, 61804, 61755, 61758, 61759, 61800, 61807, 61749, 61843, 61780, 61763, 61797, 61824, 61798, 61815, 61774, 61835, 61820, 61753, 61766, 61770, 61784, 61761, 61773, 61822, 61844, 61830, 61818, 61793, 61825, 61837, 61752, 61827, 61823, 61792, 61819, 61765, 61790, 61817, 61802, 61838, 61840, 61806, 61772, 61768, 61839, 61756, 61833, 61767, 61816], ('00001', 'MB', 'DO'): [69759, 69785, 69693, 69869, 69769, 69725, 69858, 69771, 69801, 69744, 69789, 69807, 69817, 69816, 69826, 69743, 69692, 69698, 69681, 69763, 69829, 69765, 69713, 69768, 69688, 69823, 69772, 69805, 69819, 69730, 69853, 69798, 69849, 69864, 69814, 69808, 69834, 69701, 69863, 69694, 69724, 69838, 69795, 69706, 69740, 69782, 69847, 69846, 69809, 69770, 69746, 69727, 69777, 69783, 69867, 69828, 69780, 69803, 69709, 69837, 69797, 69835, 69850, 69708, 69714, 69830, 69857, 69796, 69831, 69866, 69856, 69818, 69680, 69841, 69766, 69721, 69747, 69868, 69871, 69720, 69844, 69757, 69845, 69756, 69760, 69702, 69751, 69761, 69824, 69716, 69753, 69843, 69733, 69699, 69812, 69791], ('00001', 'MB', 'PT'): [69710, 69860, 69833, 69754, 69788, 69742, 69790, 69825, 69778, 69703, 69696, 69810, 69793, 69707, 69815, 69784, 69859, 69687, 69840, 69690, 69870, 69851, 69787, 69832, 69748, 69779, 69686, 69704, 69734, 69767, 69865, 69719, 69820, 69726, 69750, 69842, 69799, 69806, 69774, 69821, 69738, 69691, 69712, 69839, 69731, 69705, 69737, 69700, 69862, 69854, 69855, 69792, 69695, 69836, 69749, 69739, 69861, 69722, 69711, 69775, 69752, 69822, 69848, 69745, 69697, 69762, 69736, 69715, 69800, 69811, 69802, 69852, 69735, 69718, 69781, 69773, 69684, 69804, 69776, 69755, 69729, 69683, 69764, 69758, 69813, 69689, 69685, 69682, 69741, 69827, 69732, 69728, 69717, 69786, 69723, 69794], ('00001', 'SR', 'DO'): [113878, 113843, 113850, 113835, 113830, 113924, 113855, 113909, 113898, 113907, 113916, 113841, 113838, 113917, 113856, 113915, 113891, 113913, 113899, 113863, 113874, 113877, 113866, 113873, 113876, 113854, 113867, 113889, 113914, 113848, 113887, 113903, 113902, 113911, 113921, 113845, 113871, 113840, 113908, 113882, 113893, 113865, 113861, 113858, 113852, 113859, 113890, 113832, 113842, 113904, 113875, 113922, 113839, 113872, 113880, 113883, 113849, 113897, 113833, 113895, 113896, 113894, 113862, 113831, 113879, 113919, 113910, 113901, 113918, 113905, 113851, 113884, 113847, 113860, 113888, 113836, 113906, 113920, 113900, 113844, 113837, 113857, 113834, 113869, 113881, 113846, 113864, 113923, 113829, 113870, 113892, 113886, 113868, 113885, 113853, 113912], ('00001', 'TB', 'DO'): [116091, 116104, 116068, 116096, 116147, 116138, 116132, 116062, 116134, 116101, 116124, 116116, 116114, 116071, 116098, 116105, 116074, 116067, 116119, 116083, 116141, 116144, 116088, 116102, 116110, 116150, 116103, 116069, 116081, 116127, 116100, 116107, 116126, 116113, 116077, 116080, 116075, 116076, 116155, 116130, 116108, 116121, 116079, 116135, 116078, 116065, 116070, 116085, 116064, 116097, 116139, 116073, 116082, 116093, 116087, 116115, 116106, 116061, 116123, 116118, 116125, 116092, 116142, 116094, 116117, 116122, 116084, 116133, 116129, 116151, 116145, 116060, 116149, 116131, 116090, 116089, 116120, 116111, 116095, 116146, 116137, 116086, 116072, 116063, 116099, 116140, 116154, 116128, 116148, 116136, 116143, 116109, 116066, 116153, 116152, 116112], ('00001', 'VP', 'DO'): [116543, 116504, 116582, 116569, 116522, 116528, 116564, 116588, 116579, 116586, 116571, 116518, 116533, 116573, 116521, 116568, 116562, 116516, 116546, 116584, 116540, 116592, 116500, 116532, 116551, 116508, 116563, 116517, 116525, 116553, 116535, 116538, 116555, 116515, 116520, 116529, 116566, 116548, 116560, 116556, 116550, 116527, 116509, 116583, 116547, 116545, 116570, 116502, 116524, 116544, 116537, 116505, 116552, 116507, 116591, 116577, 116526, 116589, 116561, 116513, 116565, 116578, 116519, 116581, 116536, 116590, 116514, 116576, 116541, 116510, 116585, 116575, 116542, 116498, 116531, 116530, 116503, 116523, 116539, 116558, 116593, 116559, 116580, 116534, 116554, 116512, 116511, 116572, 116549, 116587, 116574, 116501, 116506, 116557, 116499, 116567], ('00002', 'DR', 'DO'): [12772, 12766, 12640, 12628, 12703, 12672, 12673, 12738, 12734, 12678, 12605, 12642, 12610, 12750, 12729, 12701, 12620, 12759, 12599, 12741, 12685, 12727, 12615, 12626, 12604, 12762, 12695, 12776, 12761, 12650, 12613, 12757, 12760, 12710, 12782, 12636, 12617, 12730, 12778, 12681, 12676, 12688, 12631, 12649, 12768, 12737, 12691, 12697, 12751, 12623, 12619, 12787, 12687, 12616, 12608, 12747, 12718, 12763, 12786, 12700, 12753, 12633, 12733, 12744, 12769, 12652, 12656, 12785, 12632, 12748, 12645, 12635, 12693, 12665, 12712, 12706, 12647, 12694, 12646, 12746, 12598, 12657, 12684, 12743, 12621, 12668, 12721, 12634, 12689, 12696, 12664, 12777, 12671, 12692, 12669, 12779], ('00002', 'DR', 'PT'): [12662, 12611, 12789, 12714, 12644, 12773, 12607, 12683, 12612, 12765, 12661, 12663, 12720, 12749, 12719, 12698, 12775, 12659, 12660, 12728, 12736, 12609, 12603, 12774, 12637, 12618, 12708, 12670, 12713, 12667, 12770, 12622, 12731, 12699, 12624, 12606, 12739, 12682, 12630, 12655, 12735, 12726, 12723, 12764, 12651, 12745, 12654, 12643, 12725, 12724, 12666, 12627, 12742, 12788, 12658, 12704, 12653, 12752, 12771, 12755, 12629, 12717, 12783, 12679, 12780, 12732, 12674, 12705, 12758, 12601, 12602, 12702, 12756, 12784, 12680, 12641, 12715, 12781, 12767, 12638, 12675, 12716, 12709, 12677, 12625, 12648, 12711, 12740, 12639, 12614, 12754, 12722, 12690, 12600, 12707, 12686], ('00002', 'MB', 'DO'): [69880, 69961, 69951, 69897, 69901, 69930, 69886, 69933, 69953, 69898, 69877, 69917, 69919, 69960, 69965, 69935, 69911, 69946, 69963, 69879, 69937, 69912, 69924, 69881, 69932, 69875, 69964, 69873, 69896, 69947, 69926, 69916, 69906, 69909, 69928, 69884, 69954, 69959, 69966, 69895, 69940, 69962, 69893, 69927, 69929, 69941, 69892, 69887, 69950, 69874, 69905, 69923, 69904, 69876, 69882, 69957, 69907, 69902, 69936, 69888, 69931, 69949, 69894, 69934, 69878, 69913, 69942, 69967, 69890, 69891, 69914, 69899, 69943, 69944, 69915, 69908, 69956, 69939, 69900, 69922, 69872, 69958, 69910, 69952, 69918, 69920, 69945, 69925, 69883, 69938, 69885, 69948, 69955, 69921, 69903, 69889], ('00002', 'VP', 'DO'): [116665, 116619, 116613, 116653, 116621, 116633, 116667, 116615, 116622, 116595, 116671, 116654, 116632, 116670, 116628, 116626, 116634, 116614, 116668, 116606, 116617, 116688, 116636, 116641, 116624, 116640, 116661, 116674, 116655, 116657, 116645, 116627, 116684, 116663, 116642, 116635, 116652, 116658, 116681, 116598, 116625, 116596, 116611, 116602, 116664, 116609, 116643, 116601, 116623, 116648, 116594, 116677, 116686, 116631, 116687, 116604, 116638, 116605, 116660, 116683, 116678, 116679, 116603, 116616, 116639, 116680, 116618, 116656, 116651, 116646, 116672, 116629, 116620, 116637, 116689, 116676, 116673, 116597, 116607, 116650, 116649, 116669, 116600, 116644, 116612, 116630, 116662, 116659, 116685, 116608, 116682, 116647, 116599, 116675, 116666, 116610], ('00003', 'DR', 'DO'): [12845, 12801, 12866, 12793, 12807, 12900, 12894, 12942, 12928, 12852, 12897, 12909, 12914, 12844, 12869, 12918, 12917, 12949, 12840, 12979, 12861, 12856, 12911, 12805, 12905, 12902, 12804, 12790, 12812, 12932, 12893, 12827, 12819, 12919, 12941, 12903, 12877, 12803, 12848, 12920, 12945, 12915, 12830, 12809, 12898, 12927, 12875, 12974, 12798, 12820, 12863, 12811, 12888, 12970, 12838, 12864, 12859, 12939, 12841, 12868, 12816, 12889, 12799, 12885, 12892, 12884, 12802, 12831, 12981, 12933, 12832, 12967, 12896, 12922, 12926, 12954, 12899, 12923, 12890, 12895, 12924, 12958, 12921, 12968, 12930, 12815, 12878, 12963, 12913, 12853, 12929, 12821, 12969, 12880, 12795, 12882], ('00003', 'DR', 'PT'): [12952, 12791, 12870, 12814, 12835, 12813, 12881, 12907, 12873, 12843, 12854, 12837, 12935, 12966, 12972, 12800, 12973, 12839, 12829, 12937, 12822, 12936, 12871, 12946, 12943, 12886, 12818, 12971, 12865, 12851, 12978, 12948, 12872, 12955, 12957, 12976, 12847, 12908, 12961, 12912, 12842, 12965, 12792, 12797, 12824, 12836, 12951, 12916, 12910, 12953, 12849, 12825, 12959, 12833, 12940, 12931, 12823, 12879, 12906, 12828, 12867, 12794, 12938, 12860, 12846, 12925, 12862, 12857, 12834, 12964, 12956, 12806, 12977, 12850, 12817, 12960, 12980, 12947, 12796, 12874, 12876, 12855, 12950, 12975, 12944, 12887, 12810, 12934, 12883, 12904, 12858, 12901, 12962, 12826, 12808, 12891], ('00003', 'MB', 'DO'): [69970, 70017, 69987, 70013, 70052, 70035, 70041, 69998, 70059, 70030, 70034, 70021, 70055, 70001, 69988, 70051, 69980, 70037, 70012, 69983, 70025, 70044, 70036, 69991, 69974, 70024, 69997, 70040, 70047, 70020, 69978, 70056, 70060, 69989, 70045, 69981, 70015, 70009, 70002, 70004, 70019, 70042, 69982, 69990, 70032, 69992, 70039, 70057, 70054, 70005, 70053, 70046, 70007, 70018, 69996, 69976, 70014, 70043, 69979, 69971, 70062, 70011, 69986, 69969, 70050, 70063, 70006, 69999, 70000, 69985, 69968, 70058, 70061, 70023, 70048, 69993, 69977, 70016, 70026, 70038, 70049, 69995, 69975, 70027, 70028, 70029, 69984, 69994, 70008, 70031, 70033, 69973, 70003, 70010, 69972, 70022], ('00003', 'VP', 'DO'): [116705, 116727, 116754, 116765, 116697, 116693, 116775, 116760, 116763, 116777, 116698, 116706, 116695, 116717, 116755, 116767, 116723, 116731, 116729, 116709, 116750, 116744, 116782, 116762, 116707, 116703, 116736, 116696, 116737, 116769, 116713, 116726, 116701, 116720, 116768, 116724, 116770, 116764, 116691, 116716, 116715, 116784, 116756, 116757, 116734, 116746, 116752, 116774, 116740, 116708, 116719, 116702, 116735, 116781, 116704, 116699, 116739, 116778, 116694, 116766, 116690, 116722, 116751, 116732, 116742, 116761, 116773, 116771, 116758, 116759, 116741, 116776, 116733, 116748, 116712, 116738, 116743, 116700, 116779, 116711, 116730, 116749, 116772, 116783, 116728, 116714, 116692, 116780, 116725, 116747, 116710, 116718, 116753, 116721, 116785, 116745], ('00005', 'DR', 'DO'): [13012, 13005, 13072, 13004, 13062, 13031, 13016, 13030, 12999, 13013, 13073, 13002, 12995, 13049, 13060, 13028, 13048, 13070, 13026, 12997, 13063, 13041, 13059, 12988, 13058, 13027, 13033, 13034, 13069, 13074, 13018, 12983, 13066, 13071, 12986, 12985, 12984, 13006, 13076, 13068, 13042, 12987, 13045, 12996, 13055, 13052, 13067, 13077, 13039, 13017, 13038, 13050, 13061, 12990, 13047, 13001, 12998, 12989, 13065, 13056, 13020, 13022, 13053, 13025, 13011, 12982, 13035, 13024, 13075, 13008, 13051, 13043, 12994, 13009, 12993, 13000, 13046, 13003, 13010, 13044, 13032, 13054, 12992, 13037, 13015, 12991, 13021, 13014, 13007, 13029, 13036, 13064, 13019, 13023, 13040, 13057], ('00005', 'MB', 'DO'): [70071, 70069, 70158, 70120, 70080, 70111, 70149, 70097, 70136, 70088, 70102, 70081, 70133, 70066, 70147, 70089, 70114, 70091, 70070, 70159, 70134, 70096, 70154, 70130, 70118, 70115, 70126, 70098, 70153, 70090, 70127, 70078, 70123, 70129, 70116, 70128, 70104, 70076, 70101, 70106, 70113, 70137, 70084, 70072, 70085, 70074, 70157, 70109, 70135, 70099, 70145, 70155, 70067, 70105, 70065, 70125, 70119, 70082, 70152, 70077, 70068, 70131, 70083, 70093, 70103, 70141, 70150, 70140, 70075, 70110, 70095, 70143, 70100, 70151, 70108, 70094, 70117, 70142, 70132, 70148, 70144, 70087, 70156, 70139, 70146, 70079, 70086, 70121, 70064, 70122, 70092, 70124, 70073, 70138, 70107, 70112], ('00006', 'CB', 'PT'): [1792, 1780, 1762, 1781, 1826, 1784, 1789, 1763, 1765, 1753, 1793, 1800, 1733, 1788, 1764, 1739, 1807, 1825, 1740, 1823, 1742, 1795, 1737, 1754, 1746, 1811, 1779, 1751, 1806, 1736, 1812, 1805, 1767, 1752, 1785, 1790, 1768, 1749, 1771, 1748, 1801, 1776, 1750, 1794, 1798, 1758, 1770, 1799, 1817, 1734, 1809, 1738, 1814, 1778, 1808, 1815, 1755, 1743, 1766, 1804, 1769, 1810, 1796, 1791, 1777, 1822, 1828, 1747, 1819, 1741, 1783, 1786, 1813, 1745, 1820, 1759, 1775, 1760, 1756, 1827, 1772, 1735, 1774, 1816, 1757, 1821, 1818, 1803, 1802, 1824, 1761, 1744, 1782, 1797, 1773, 1787], ('00006', 'DR', 'PT'): [13128, 13156, 13092, 13171, 13147, 13137, 13160, 13150, 13105, 13143, 13161, 13078, 13107, 13138, 13083, 13114, 13129, 13169, 13089, 13080, 13148, 13130, 13103, 13155, 13100, 13151, 13118, 13154, 13134, 13158, 13140, 13125, 13172, 13084, 13117, 13079, 13127, 13109, 13112, 13095, 13157, 13121, 13098, 13108, 13144, 13097, 13090, 13139, 13115, 13145, 13131, 13135, 13102, 13094, 13122, 13110, 13120, 13164, 13124, 13142, 13093, 13081, 13113, 13091, 13149, 13086, 13170, 13173, 13159, 13099, 13096, 13123, 13153, 13146, 13085, 13163, 13088, 13166, 13116, 13087, 13111, 13126, 13104, 13141, 13152, 13106, 13101, 13167, 13165, 13132, 13162, 13082, 13119, 13133, 13168, 13136], ('00006', 'MB', 'DO'): [70180, 70190, 70178, 70252, 70195, 70175, 70222, 70197, 70186, 70240, 70200, 70185, 70188, 70234, 70233, 70179, 70242, 70236, 70247, 70214, 70255, 70249, 70237, 70168, 70182, 70210, 70246, 70250, 70202, 70176, 70220, 70203, 70231, 70194, 70213, 70177, 70243, 70227, 70173, 70198, 70193, 70248, 70170, 70221, 70187, 70162, 70207, 70225, 70224, 70230, 70165, 70238, 70204, 70172, 70215, 70164, 70163, 70160, 70212, 70245, 70239, 70218, 70216, 70169, 70205, 70191, 70184, 70211, 70183, 70219, 70226, 70241, 70229, 70217, 70253, 70201, 70244, 70181, 70235, 70206, 70199, 70171, 70196, 70161, 70251, 70167, 70254, 70174, 70208, 70209, 70189, 70232, 70166, 70192, 70223, 70228], ('00006', 'VP', 'DO'): [116809, 116826, 116802, 116795, 116817, 116794, 116823, 116786, 116805, 116798, 116791, 116807, 116821, 116815, 116806, 116796, 116814, 116828, 116790, 116816, 116800, 116793, 116799, 116831, 116825, 116811, 116808, 116812, 116822, 116788, 116787, 116789, 116810, 116829, 116818, 116833, 116830, 116792, 116819, 116827, 116813, 116803, 116824, 116804, 116801, 116797, 116820, 116832], ('00007', 'CB', 'PT'): [1832, 1833, 1831, 1829, 1830, 1834], ('00007', 'DR', 'PT'): [13256, 13225, 13251, 13178, 13246, 13263, 13253, 13233, 13209, 13364, 13287, 13207, 13269, 13206, 13361, 13347, 13249, 13357, 13299, 13323, 13230, 13243, 13283, 13350, 13176, 13309, 13215, 13340, 13208, 13219, 13363, 13320, 13330, 13199, 13352, 13254, 13181, 13210, 13214, 13259, 13295, 13201, 13315, 13213, 13345, 13321, 13305, 13292, 13339, 13335, 13282, 13264, 13217, 13261, 13343, 13284, 13336, 13303, 13272, 13236, 13325, 13223, 13265, 13346, 13258, 13300, 13285, 13212, 13356, 13268, 13297, 13228, 13229, 13192, 13240, 13205, 13195, 13308, 13184, 13329, 13291, 13327, 13266, 13231, 13338, 13271, 13262, 13274, 13312, 13365, 13324, 13273, 13237, 13318, 13200, 13245], ('00007', 'DR', 'TX'): [13196, 13204, 13183, 13354, 13359, 13310, 13235, 13342, 13175, 13362, 13250, 13294, 13281, 13180, 13311, 13276, 13239, 13293, 13314, 13242, 13288, 13222, 13232, 13351, 13353, 13277, 13358, 13267, 13182, 13211, 13337, 13241, 13348, 13302, 13260, 13344, 13270, 13275, 13190, 13227, 13301, 13360, 13203, 13187, 13307, 13333, 13341, 13316, 13334, 13185, 13298, 13257, 13186, 13244, 13226, 13238, 13255, 13248, 13290, 13194, 13197, 13304, 13174, 13179, 13322, 13317, 13202, 13193, 13289, 13188, 13280, 13220, 13216, 13306, 13224, 13331, 13326, 13349, 13247, 13177, 13279, 13278, 13252, 13319, 13296, 13198, 13234, 13286, 13189, 13221, 13355, 13313, 13218, 13328, 13332, 13191], ('00007', 'MB', 'DO'): [70402, 70315, 70288, 70441, 70268, 70446, 70387, 70272, 70274, 70438, 70362, 70283, 70384, 70355, 70257, 70341, 70342, 70406, 70333, 70419, 70363, 70302, 70311, 70368, 70300, 70294, 70285, 70340, 70444, 70435, 70266, 70264, 70360, 70442, 70290, 70382, 70409, 70429, 70275, 70352, 70386, 70262, 70263, 70366, 70425, 70428, 70310, 70404, 70346, 70408, 70334, 70350, 70412, 70293, 70391, 70327, 70410, 70289, 70396, 70304, 70307, 70365, 70379, 70286, 70447, 70353, 70417, 70434, 70437, 70287, 70284, 70351, 70297, 70397, 70282, 70301, 70413, 70403, 70322, 70329, 70256, 70422, 70369, 70260, 70398, 70348, 70433, 70279, 70258, 70280, 70330, 70388, 70373, 70377, 70328, 70317], ('00007', 'MB', 'PT'): [70292, 70339, 70356, 70358, 70415, 70267, 70443, 70383, 70361, 70370, 70416, 70430, 70427, 70411, 70414, 70395, 70326, 70319, 70367, 70324, 70261, 70336, 70359, 70390, 70347, 70378, 70431, 70405, 70381, 70309, 70436, 70349, 70418, 70344, 70421, 70426, 70323, 70314, 70269, 70376, 70331, 70281, 70265, 70389, 70440, 70318, 70407, 70316, 70277, 70399, 70332, 70325, 70303, 70354, 70401, 70380, 70320, 70423, 70424, 70298, 70439, 70338, 70276, 70385, 70420, 70372, 70400, 70273, 70295, 70308, 70375, 70296, 70312, 70364, 70305, 70374, 70432, 70393, 70321, 70337, 70345, 70270, 70259, 70291, 70299, 70343, 70392, 70306, 70371, 70271, 70335, 70394, 70313, 70278, 70357, 70445], ('00007', 'RB', 'DO'): [208, 193, 260, 283, 256, 248, 228, 284, 262, 207, 277, 279, 216, 205, 199, 240, 282, 278, 214, 250, 225, 242, 223, 196, 266, 263, 287, 273, 234, 255, 257, 202, 200, 285, 264, 281, 220, 267, 224, 269, 235, 259, 237, 258, 254, 245, 215, 252, 221, 204, 197, 211, 236, 217, 286, 198, 227, 201, 280, 209, 253, 213, 218, 275, 212, 192, 195, 270, 247, 206, 231, 243, 265, 226, 249, 219, 222, 232, 268, 274, 233, 194, 251, 272, 203, 244, 276, 246, 261, 210, 241, 230, 271, 239, 229, 238], ('00007', 'VP', 'PT'): [116855, 116906, 116858, 116885, 116928, 116922, 116867, 116918, 116887, 116893, 116929, 116901, 116895, 116865, 116924, 116841, 116850, 116870, 116842, 116891, 116923, 116920, 116871, 116857, 116866, 116844, 116912, 116898, 116849, 116848, 116890, 116925, 116835, 116864, 116900, 116915, 116905, 116879, 116847, 116862, 116837, 116909, 116903, 116851, 116897, 116914, 116853, 116840, 116838, 116880, 116875, 116839, 116834, 116916, 116908, 116856, 116926, 116913, 116868, 116911, 116881, 116882, 116852, 116872, 116854, 116902, 116927, 116892, 116860, 116921, 116888, 116884, 116883, 116836, 116919, 116917, 116894, 116859, 116877, 116910, 116873, 116845, 116904, 116861, 116899, 116843, 116876, 116886, 116846, 116907, 116878, 116863, 116874, 116869, 116889, 116896], ('00008', 'DR', 'PT'): [13395, 13390, 13542, 13558, 13540, 13546, 13580, 13465, 13376, 13397, 13568, 13422, 13519, 13466, 13545, 13442, 13467, 13384, 13373, 13429, 13585, 13538, 13450, 13383, 13490, 13374, 13396, 13472, 13381, 13553, 13423, 13549, 13567, 13458, 13524, 13573, 13575, 13473, 13517, 13529, 13445, 13577, 13420, 13516, 13477, 13486, 13492, 13482, 13528, 13417, 13379, 13400, 13564, 13562, 13434, 13533, 13559,

In [ ]:
test_assign

In [ ]:
    df["change_1yr"] = df["upt"] - df[change_col]

    df = get_percent_change(df, change_col=change_col)

    return df

## 09/24/2025 Update new table in function

In [ ]:
# initiald function with current data table
def produce_ntd_monthly_ridership_by_rtpa(year: int, month: int) -> pd.DataFrame:
    """
    This function works with the warehouse `dim_monthly_ntd_ridership_with_adjustments` long data format.
    Import NTD data from warehouse, filter to CA,
    merge in crosswalk, checks for unmerged rows, then creates new columns for full Mode and TOS name.

    """
    # REMOVED 2025 FOR TESTING PURPOSES
    monthly_query ="""
    SELECT 
      ntd_id,
      agency,
      reporter_type,
      period_year_month,
      period_year,
      period_month,
      mode,
      tos,
      mode_type_of_service_status AS Status,
      primary_uza_name as uza_name,
      upt
    FROM
      `cal-itp-data-infra.mart_ntd.dim_monthly_ridership_with_adjustments`
    WHERE
      period_year IN ("2018", "2019", "2020", "2021", "2022", "2023", "2024") 
      AND agency IS NOT NULL
    """
    full_upt = query_sql(monthly_query, as_df=True)

    # full_upt.to_parquet(
    #     f"{GCS_FILE_PATH}ntd_monthly_ridership_{year}_{month}.parquet"
    # )

    ca = full_upt[
        (full_upt["uza_name"].str.contains(", CA")) & (full_upt.agency.notna())
    ].reset_index(drop=True)

    # use new crosswalk function
    crosswalk = ntd_id_to_rtpa_crosswalk(split_scag=True)

    min_year = 2018

    # get agencies with last report year and data after > 2018.
    last_report_query = """
    SELECT DISTINCT
      source_agency,
      last_report_year,
      ntd_id,
    FROM
      `cal-itp-data-infra.mart_ntd_funding_and_expenses.fct_service_data_and_operating_expenses_time_series_by_mode_upt`
    WHERE
      year >= 2018
      AND last_report_year >= 2018
      AND (
        primary_uza_name LIKE "%, CA%"
        OR primary_uza_name LIKE "%CA-NV%"
        OR primary_uza_name LIKE "%California Non-UZA%"
      )
    """

    last_report_year = query_sql(last_report_query, as_df=True)

    # merge last report year to CA UPT data
    df = pd.merge(ca, last_report_year, left_on="ntd_id", right_on="ntd_id", how="inner")
    # merge crosswalk to CA last report year
    df = pd.merge(
        df,
        # Merging on too many columns can create problems
        # because csvs and dtypes aren't stable / consistent
        # for NTD ID, Legacy NTD ID, and UZA
        crosswalk[["ntd_id_2022", "rtpa_name"]],
        left_on="ntd_id",
        right_on="ntd_id_2022",
        how="left",
        indicator=True,
    )

    print(df._merge.value_counts())

    # check for unmerged rows
    if len(df[df._merge == "left_only"]) > 0:
        raise ValueError("There are unmerged rows to crosswalk")
    
    monthly_sort_cols =  [
    "ntd_id",
    "mode", 
    "tos",
    "period_month", 
    "period_year"
] # got the order correct with ["period_month", "period_year"]! sorted years with grouped months

    monthly_group_cols = [
        "ntd_id",
        "mode", 
        "tos"
                  ]

    monthly_change_col ="previous_y_m_upt"

    df = add_change_columns(
        df,
        sort_cols = monthly_sort_cols,
        group_cols = monthly_group_cols,
        change_col = monthly_change_col
    )

    
    df = df.assign(
        Mode_full = df["mode"].map(NTD_MODES),
        TOS_full = df["tos"].map(NTD_TOS)
    )
    
    return df

In [ ]:
# new data table
def produce_ntd_monthly_ridership_by_rtpa_v2(year: int, month: int) -> pd.DataFrame:
    """
    This function works with the warehouse `dim_monthly_ntd_ridership_with_adjustments` long data format.
    Import NTD data from warehouse, filter to CA,
    merge in crosswalk, checks for unmerged rows, then creates new columns for full Mode and TOS name.

    """
    # REMOVED 2025 FOR TESTING PURPOSES
    monthly_query ="""
    SELECT 
      ntd_id,
      agency,
      reporter_type,
      period_year_month,
      period_year,
      period_month,
      mode,
      tos,
      mode_type_of_service_status AS Status,
      uza_name,
      upt
    FROM
      `cal-itp-data-infra.mart_ntd_ridership.fct_complete_monthly_ridership_with_adjustments_and_estimates`
    WHERE
      period_year IN ("2018", "2019", "2020", "2021", "2022", "2023", "2024")
      AND agency IS NOT NULL
    """
    full_upt = query_sql(monthly_query, as_df=True)

    # full_upt.to_parquet(
    #     f"{GCS_FILE_PATH}ntd_monthly_ridership_{year}_{month}.parquet"
    # )

    ca = full_upt[
        (full_upt["uza_name"].str.contains(", CA")) & (full_upt.agency.notna())
    ].reset_index(drop=True)

    # use new crosswalk function
    crosswalk = ntd_id_to_rtpa_crosswalk(split_scag=True)

    min_year = 2018

    # get agencies with last report year and data after > 2018.
    last_report_query = """
    SELECT DISTINCT
      source_agency,
      last_report_year,
      ntd_id,
    FROM
      `cal-itp-data-infra.mart_ntd_funding_and_expenses.fct_service_data_and_operating_expenses_time_series_by_mode_upt`
    WHERE
      year >= 2018
      AND last_report_year >= 2018
      AND (
        primary_uza_name LIKE "%, CA%"
        OR primary_uza_name LIKE "%CA-NV%"
        OR primary_uza_name LIKE "%California Non-UZA%"
      )
    """

    last_report_year = query_sql(last_report_query, as_df=True)

    # merge last report year to CA UPT data
    df = pd.merge(ca, last_report_year, left_on="ntd_id", right_on="ntd_id", how="inner")
    # merge crosswalk to CA last report year
    df = pd.merge(
        df,
        # Merging on too many columns can create problems
        # because csvs and dtypes aren't stable / consistent
        # for NTD ID, Legacy NTD ID, and UZA
        crosswalk[["ntd_id_2022", "rtpa_name"]],
        left_on="ntd_id",
        right_on="ntd_id_2022",
        how="left",
        indicator=True,
    )

    print(df._merge.value_counts())

    # check for unmerged rows
    if len(df[df._merge == "left_only"]) > 0:
        raise ValueError("There are unmerged rows to crosswalk")
    
    monthly_sort_cols =  [
    "ntd_id",
    "mode", 
    "tos",
    "period_month", 
    "period_year"
] # got the order correct with ["period_month", "period_year"]! sorted years with grouped months

    monthly_group_cols = [
        "ntd_id",
        "mode", 
        "tos"
                  ]

    monthly_change_col ="previous_y_m_upt"

    df = add_change_columns(
        df,
        sort_cols = monthly_sort_cols,
        group_cols = monthly_group_cols,
        change_col = monthly_change_col
    )

    
    df = df.assign(
        Mode_full = df["mode"].map(NTD_MODES),
        TOS_full = df["tos"].map(NTD_TOS)
    )
    
    return df

In [ ]:
df_v1 = produce_ntd_monthly_ridership_by_rtpa(YEAR, MONTH)
print(df_v1.columns) # good to go!

In [ ]:
df_v2 = produce_ntd_monthly_ridership_by_rtpa_v2(YEAR, MONTH)
print(df_v2.columns) # good to go!

In [ ]:
display(
    df_v1.equals(df_v2),
    df_v1["ntd_id"].nunique(),
    df_v2["ntd_id"].nunique(),
)
# Why do they differ?

In [ ]:
df_1_agg = df_v1.groupby(["ntd_id","agency"]).agg({"upt":"sum"}).reset_index()
df_2_agg = df_v2.groupby(["ntd_id","agency"]).agg({"upt":"sum"}).reset_index()

check_merge = df_1_agg.merge(
    df_2_agg, 
    on=["ntd_id","agency"], 
    how="outer", 
    indicator=True,
)

In [ ]:
display(
    df_1_agg.head(),
    df_2_agg.head()
)

In [ ]:
check_merge["_merge"].value_counts()

In [ ]:
check_merge[check_merge["agency"].str.contains("Modesto")]

In [ ]:
check_merge[check_merge["ntd_id"]=="90007"]

In [ ]:
check_merge[check_merge["_merge"]!="both"].sort_values(by="ntd_id")

## Warehouse research
- RE: 90007 Modesto
  - Compared identical year, month, tos, mode. The dim_monthly table includes NULL UPT rows, whereas the fct_monthly tables does not have NULL rows. Other than the NULL rows, the reamining UPT values match
  
- RE: 90296 Claremont
  - same variables as previous. dim_monthly tables ONLY contain NULL rows for this agency. fct_monthly does not contain this agency

- Filtered dataframe for `left_only` & `right_only`
  - All agencies were accounted for
  - agencies with 0 in dim_montly had NaN in fct_monthly
  - agencies with data in dim_monthly had equivienelt data in_fct_monthly, just didnt match for some reason. 

- Solution
  - Demo'd observations during round table meeting. OK'd to remove 0/NULL values and to make note of it on the report.

## if i took out `zero/NULL/NaN` rows from dim_monthly, will it be the same as fct_monthly?

In [ ]:
set(df_v1[df_v1["upt"]!=0].dropna()["ntd_id"].unique()) == set(df_v2["ntd_id"].unique()) # TRUE!!!!!!!!!!

In [ ]:
dim_monthly_set = set(df_v1[df_v1["upt"]!=0].dropna()["ntd_id"].unique())
fct_monthly_set = set(df_v2["ntd_id"].unique())

diff_dim_fct = dim_monthly_set - fct_monthly_set

diff_fct_dim = fct_monthly_set - dim_monthly_set

print(diff_dim_fct, diff_dim_fct)

## how many agencies do i lose if i drop zero values rows?

In [ ]:
df_v1[
    (df_v1["upt"]==0) 
    | (df_v1["upt"].isna())
]["ntd_id"].nunique()

In [ ]:
df_v1[
    (df_v1["upt"]==0) 
    | (df_v1["upt"].isna())
]

In [ ]:
df_v1[
    (df_v1["upt"] > 0) 
    & (df_v1["upt"].notna())
]["ntd_id"].nunique()

In [ ]:
print(
    f"""Total Number of unique ntd_id from dim_monthly test table: {df_v1["ntd_id"].nunique()}.
    Number of unique ntd_id with zero-value/NaN/NULL metrics: {df_v1[df_v1["upt"]==0 | df_v1["upt"].isna()]["ntd_id"].nunique()}.
    Number of remaining uniqe ntd_id:{df_v1[df_v1["upt"]!=0].dropna()["ntd_id"].nunique()}
    """
)

## Results
Confirm that the unique non-zero/null ntd_id values in dim_monthly are the same in fct_monthly. confident to move forward in

## 09/18/2025 remove siuba from report

In [ ]:
# DEPRECATED OLD FUNCTION
# def produce_ntd_monthly_ridership_by_rtpa(year: int, month: int) -> pd.DataFrame:
#     """
#     This function works with the warehouse `dim_monthly_ntd_ridership_with_adjustments` long data format.
#     Import NTD data from warehouse, filter to CA,
#     merge in crosswalk, checks for unmerged rows, then creates new columns for full Mode and TOS name.

#     """

#     full_upt = (
#         tbls.mart_ntd.dim_monthly_ridership_with_adjustments()
#         >> filter(
#             _.period_year.isin(
#                 ["2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025"]
#             )
#         )
#         >>select(
#             _.ntd_id,
#             _.agency,
#             _.reporter_type,
#             _.period_year_month,
#             _.period_year,
#             _.period_month,
#             _.mode,
#             _.tos,
#             _.mode_type_of_service_status,
#             _.primary_uza_name,
#             _.upt
            
#         )
#         >> collect()
#     ).rename(
#         columns={
#             "mode_type_of_service_status": "Status",
#             "primary_uza_name": "uza_name",
#         }
#     )

#     full_upt = full_upt[full_upt.agency.notna()].reset_index(drop=True)

#     full_upt.to_parquet(
#         f"{GCS_FILE_PATH}ntd_monthly_ridership_{year}_{month}.parquet"
#     )

#     ca = full_upt[
#         (full_upt["uza_name"].str.contains(", CA")) & (full_upt.agency.notna())
#     ].reset_index(drop=True)

#     # use new crosswalk function
#     crosswalk = ntd_id_to_rtpa_crosswalk(split_scag=True)

#     min_year = 2018

#     # get agencies with last report year and data after > 2018.
#     last_report_year = (
#         tbls.mart_ntd_funding_and_expenses.fct_service_data_and_operating_expenses_time_series_by_mode_upt()
#         >> filter(
#             _.year >= min_year,  # see if this changes anything
#             _.last_report_year >= min_year,
#             _.primary_uza_name.str.contains(", CA")
#             | _.primary_uza_name.str.contains("CA-NV")
#             | _.primary_uza_name.str.contains("California Non-UZA"),
#         )
#         >> distinct(
#             "source_agency",
#             "last_report_year",
#             "ntd_id",
#         )
#         >> collect()
#     )

#     # merge last report year to CA UPT data
#     df = pd.merge(ca, last_report_year, left_on="ntd_id", right_on="ntd_id", how="inner")

In [ ]:
# full_upt = (
#         tbls.mart_ntd.dim_monthly_ridership_with_adjustments()
#         >> filter(
#             _.period_year.isin(
#                 ["2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025"]
#             )
#         )
#         >>select(
#             _.ntd_id,
#             _.agency,
#             _.reporter_type,
#             _.period_year_month,
#             _.period_year,
#             _.period_month,
#             _.mode,
#             _.tos,
#             _.mode_type_of_service_status,
#             _.primary_uza_name,
#             _.upt
            
#         )
#         >> collect()
#     ).rename(
#         columns={
#             "mode_type_of_service_status": "Status",
#             "primary_uza_name": "uza_name",
#         }
#     )

# full_upt = full_upt[full_upt.agency.notna()].reset_index(drop=True)

# full_upt.info()

In [ ]:
# min_year = 2018
# last_report_year = (
#         tbls.mart_ntd_funding_and_expenses.fct_service_data_and_operating_expenses_time_series_by_mode_upt()
#         >> filter(
#             _.year >= min_year,  # see if this changes anything
#             _.last_report_year >= min_year,
#             _.primary_uza_name.str.contains(", CA")
#             | _.primary_uza_name.str.contains("CA-NV")
#             | _.primary_uza_name.str.contains("California Non-UZA"),
#         )
#         >> distinct(
#             "source_agency",
#             "last_report_year",
#             "ntd_id",
#         )
#         >> collect()
#     )

# last_report_year.info()

In [ ]:
# merge last report year to CA UPT data
df = pd.merge(ca, last_report_year, left_on="ntd_id", right_on="ntd_id", how="inner")
    # merge crosswalk to CA last report year
df = pd.merge(
    df,
        # Merging on too many columns can create problems
        # because csvs and dtypes aren't stable / consistent
        # for NTD ID, Legacy NTD ID, and UZA
    crosswalk[["ntd_id_2022", "rtpa_name"]],
    left_on="ntd_id",
    right_on="ntd_id_2022",
    how="left",
    indicator=True,
    )

In [ ]:
display(
    full_upt.equals(full_upt_test),
    last_report_year.equals(last_report_year_test)
) # TRUE TRUE!!
# good to go

In [ ]:
# UPDATED without siuba
def produce_ntd_monthly_ridership_by_rtpa(year: int, month: int) -> pd.DataFrame:
    """
    This function works with the warehouse `dim_monthly_ntd_ridership_with_adjustments` long data format.
    Import NTD data from warehouse, filter to CA,
    merge in crosswalk, checks for unmerged rows, then creates new columns for full Mode and TOS name.

    """
    monthly_query ="""
    SELECT 
      ntd_id,
      agency,
      reporter_type,
      period_year_month,
      period_year,
      period_month,
      mode,
      tos,
      mode_type_of_service_status AS Status,
      primary_uza_name as uza_name,
      upt
    FROM
      `cal-itp-data-infra.mart_ntd.dim_monthly_ridership_with_adjustments`
    WHERE
      period_year IN ("2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025")
      AND agency IS NOT NULL
    """
    full_upt = query_sql(monthly_query, as_df=True)

    # full_upt.to_parquet(
    #     f"{GCS_FILE_PATH}ntd_monthly_ridership_{year}_{month}.parquet"
    # )

    ca = full_upt[
        (full_upt["uza_name"].str.contains(", CA")) & (full_upt.agency.notna())
    ].reset_index(drop=True)

    # use new crosswalk function
    crosswalk = ntd_id_to_rtpa_crosswalk(split_scag=True)

    min_year = 2018

    # get agencies with last report year and data after > 2018.
    last_report_query = """
    SELECT DISTINCT
      source_agency,
      last_report_year,
      ntd_id,
    FROM
      `cal-itp-data-infra.mart_ntd_funding_and_expenses.fct_service_data_and_operating_expenses_time_series_by_mode_upt`
    WHERE
      year >= 2018
      AND last_report_year >= 2018
      AND (
        primary_uza_name LIKE "%, CA%"
        OR primary_uza_name LIKE "%CA-NV%"
        OR primary_uza_name LIKE "%California Non-UZA%"
      )
    """

    last_report_year = query_sql(last_report_query, as_df=True)

    # merge last report year to CA UPT data
    df = pd.merge(ca, last_report_year, left_on="ntd_id", right_on="ntd_id", how="inner")
    # merge crosswalk to CA last report year
    df = pd.merge(
        df,
        # Merging on too many columns can create problems
        # because csvs and dtypes aren't stable / consistent
        # for NTD ID, Legacy NTD ID, and UZA
        crosswalk[["ntd_id_2022", "rtpa_name"]],
        left_on="ntd_id",
        right_on="ntd_id_2022",
        how="left",
        indicator=True,
    )

    print(df._merge.value_counts())

    # check for unmerged rows
    if len(df[df._merge == "left_only"]) > 0:
        raise ValueError("There are unmerged rows to crosswalk")
    
    monthly_sort_cols =  [
    "ntd_id",
    "mode", 
    "tos",
    "period_month", 
    "period_year"
] # got the order correct with ["period_month", "period_year"]! sorted years with grouped months

    monthly_group_cols = [
        "ntd_id",
        "mode", 
        "tos"
                  ]

    monthly_change_col ="previous_y_m_upt"

    df = add_change_columns(
        df,
        sort_cols = monthly_sort_cols,
        group_cols = monthly_group_cols,
        change_col = monthly_change_col
    )

    
    df = df.assign(
        Mode_full = df["mode"].map(NTD_MODES),
        TOS_full = df["tos"].map(NTD_TOS)
    )
    
    return df

## Update `produce_ntd_monthly_ridership_by_rtpa` function

In [ ]:
from calitp_data_analysis.tables import tbls
from siuba import _, collect, distinct, filter, select

In [ ]:
# from annual_ridership_report.annual_ridership_module import ntd_id_to_rtpa_crosswalk

In [ ]:
from _01_ntd_ridership_utils import ntd_id_to_rtpa_crosswalk, add_change_columns

In [ ]:
xwalk_no_split = ntd_id_to_rtpa_crosswalk(split_scag=False)

In [ ]:
# display(
#     test.head(),
#     test.info(),
#     test["rtpa_name"].value_counts()
# )

In [ ]:
xwalk_w_split = ntd_id_to_rtpa_crosswalk(split_scag=True)

In [ ]:
xwalk_no_split["rtpa_name"].unique() == xwalk_w_split["rtpa_name"].unique()

In [ ]:
xwalk_w_split.columns.tolist()

In [ ]:
# updated
def produce_ntd_monthly_ridership_by_rtpa(year: int, month: int) -> pd.DataFrame:
    """
    This function works with the warehouse `dim_monthly_ntd_ridership_with_adjustments` long data format.
    Import NTD data from warehouse, filter to CA,
    merge in crosswalk, checks for unmerged rows, then creates new columns for full Mode and TOS name.

    """

    full_upt = (
        tbls.mart_ntd.dim_monthly_ridership_with_adjustments()
        >> filter(
            _.period_year.isin(
                ["2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025"]
            )
        )
        >>select(
            _.ntd_id,
            _.agency,
            _.reporter_type,
            _.period_year_month,
            _.period_year,
            _.period_month,
            _.mode,
            _.tos,
            _.mode_type_of_service_status,
            _.primary_uza_name,
            _.upt
            
        )
        >> collect()
    ).rename(
        columns={
            "mode_type_of_service_status": "Status",
            "primary_uza_name": "uza_name",
        }
    )

    full_upt = full_upt[full_upt.agency.notna()].reset_index(drop=True)

    # full_upt.to_parquet(
    #     f"{GCS_FILE_PATH}ntd_monthly_ridership_{year}_{month}.parquet"
    # )

    ca = full_upt[
        (full_upt["uza_name"].str.contains(", CA")) & (full_upt.agency.notna())
    ].reset_index(drop=True)

    # use new crosswalk function
    crosswalk = ntd_id_to_rtpa_crosswalk(split_scag=True)

    min_year = 2018

    # get agencies with last report year and data after > 2018.
    last_report_year = (
        tbls.mart_ntd_funding_and_expenses.fct_service_data_and_operating_expenses_time_series_by_mode_upt()
        >> filter(
            _.year >= min_year,  # see if this changes anything
            _.last_report_year >= min_year,
            _.primary_uza_name.str.contains(", CA")
            | _.primary_uza_name.str.contains("CA-NV")
            | _.primary_uza_name.str.contains("California Non-UZA"),
        )
        >> distinct(
            "source_agency",
            #'agency_status',
            #'legacy_ntd_id',
            "last_report_year",
            #'mode',
            "ntd_id",
            #'reporter_type',
            #'reporting_module',
            #'service',
            #'uace_code',
            #'primary_uza_name',
            #'uza_population',
            #'year',
            #'upt',
        )
        >> collect()
    )

    # merge last report year to CA UPT data
    df = pd.merge(ca, last_report_year, left_on="ntd_id", right_on="ntd_id", how="inner")

    # merge crosswalk to CA last report year
    df = pd.merge(
        df,
        # Merging on too many columns can create problems
        # because csvs and dtypes aren't stable / consistent
        # for NTD ID, Legacy NTD ID, and UZA
        crosswalk[["ntd_id_2022", "rtpa_name"]],
        left_on="ntd_id",
        right_on="ntd_id_2022",
        how="left",
        indicator=True,
    )

    print(df._merge.value_counts())

    # check for unmerged rows
    if len(df[df._merge == "left_only"]) > 0:
        raise ValueError("There are unmerged rows to crosswalk")
    
    df = add_change_columns(df)
    
    df = df.assign(
        Mode_full = df["mode"].map(NTD_MODES),
        TOS_full = df["tos"].map(NTD_TOS)
    )
    
    return df

In [ ]:
data = produce_ntd_monthly_ridership_by_rtpa(YEAR, MONTH)

In [ ]:
display(
    data.info(),
    data["rtpa_name"].value_counts(),
    data.describe()
)

In [ ]:
df_check = pd.read_parquet(
        f"{GCS_FILE_PATH}ca_monthly_ridership_{YEAR}_{MONTH}.parquet"
    )

In [ ]:
df_check["rtpa_name"].sort_values().unique()
# wher is SLOCOG??!?!
# City of SLO was in SANDAG, adjusted city of slo RTPA in airtable 6/20/2025. should be fixed in the next report update

In [ ]:
ntd_rtpa_orgs = (
        tbls.mart_transit_database.dim_organizations()
        >> filter(
            _._is_current == True,
            _.ntd_id_2022.notna(),
            _.rtpa_name.notna(),
        )
        >> select(
            _.name, 
            _.ntd_id_2022, 
            _.rtpa_name, 
            _.mpo_name, 
            _.key
        )
        >> collect()
    )

    # join bridge org county geo to get agency counties
bridge_counties = (
        tbls.mart_transit_database.bridge_organizations_x_headquarters_county_geography()
        >> filter(
            _._is_current == True
        )
        >> select(
            _.county_geography_name, 
            _.organization_key
        )
        >> collect()
    )

In [ ]:
ntd_rtpa_orgs[ntd_rtpa_orgs["name"].str.contains("San Luis")]

In [ ]:
bridge_counties["county_geography_name"].value_counts()

In [ ]:
ntd_to_rtpa_crosswalk = ntd_rtpa_orgs.merge(
        bridge_counties, 
        left_on="key", 
        right_on="organization_key", 
        how="left"
    )

In [ ]:
ntd_to_rtpa_crosswalk[ntd_to_rtpa_crosswalk["rtpa_name"].str.contains("San Luis")]

---

# {rtpa}
## Monthly Ridership Trends

**Download data from our public [folder](https://console.cloud.google.com/storage/browser/calitp-publish-data-analysis)** by navigating to `ntd_monthly_ridership` and selecting a file.

Transit operators/agencies that are **Urban full reporters, that submit monthly ridership data to NTD from 2018 to present**, are included in this report. Reporters that were previously Urban full reporters, but are currently not, may appear. This may result in Reporters showing zero or partial ridership data in the report. 

If a Reporter is not a monthly reporter, or has not reported data since 2018, they will not appear in the report.

Examples: 
- Reporter A is an urban full reporter from 2019-2022, then became a reduced reporter for 2023. Reporter A's ridership data will be displayed for 2019-2022 only.
- Reporter B is an urban full reporter from 2000-2017, then became a reduced reporter for 2018. Reporter B will be named in the report, but will not display ridership data.
- Reporter C was a reduced reporter form 2015-2020, then became an urban full reporter and began submitting monthly ridership data to NTD for 2021. Reporter C's ridership data will be displayed for 2021-present.

In [ ]:
URL = "https://console.cloud.google.com/storage/" "browser/calitp-publish-data-analysis"

display(
    HTML(
        f"""
        <a href={URL}>
        Download the latest month of data: {PUBLIC_FILENAME}</a>
        """
    )
)

In [ ]:
MIN_YEAR = 2018

# updated to filter for period_year greater than 2018
df = produce_ntd_monthly_ridership_by_rtpa_v2(YEAR, MONTH).drop(
    columns=["mode", "tos"]
).rename(
    columns={"Mode_full": "Mode", "TOS_full": "TOS"}
)

In [ ]:
df.info()

In [ ]:
# KEEPING AS IS FOR NOW, BUT MAY NEED TO REWORK


def remove_zero_upt_rows(df: pd.DataFrame) -> pd.DataFrame:
    """
    takes the by_agency_long df, filters for rows with zero UPT AND zero change_1yr.
    then removes these rows from the by_agency_long df.
    resulting df should only contain rows with change in UPT not due to (0 UPT - 0 UPT) and net zero change in UPT
    zero UPT and zero change_1yr occurs when (0 upt - 0upt = 0change), dont need to show this
    but a net zero change (100upt - 100upt = 0 change), should be shown
    """

    # df of rows with zero UPT for 2 years
    zero_UPT_2years = df[(df["upt"] == 0) & (df["change_1yr"] == 0)]

    merge = df.merge(zero_UPT_2years, how="left", indicator=True)
    no_zero_UPT_rows = (
        merge[merge["_merge"] == "left_only"]
        .drop(columns=["_merge"])
        .dropna(subset="change_1yr")
    )

    return no_zero_UPT_rows

In [ ]:
def group_by_agency(df):
    """
    Take in the 'by_ageny_long' df and aggregatese by rtpa, and calculates upt % of total.
    To be used in pie chart
    """
    initial_agg = df.groupby("agency").agg(total_upt=("upt", "sum")).reset_index()

    # % total columns
    initial_agg["pct_of_total_upt"] = (
        initial_agg["total_upt"] / initial_agg["total_upt"].sum()
    ) * 100

    # cleaning data types and rounding
    initial_agg["total_upt"] = initial_agg["total_upt"].astype("int64")
    initial_agg["pct_of_total_upt"] = initial_agg["pct_of_total_upt"].round(decimals=2)
    cleaned_agg = initial_agg.sort_values(by="total_upt", ascending=False)

    return cleaned_agg

In [ ]:
from _01_ntd_ridership_utils import sum_by_group

In [ ]:
agency_cols = ["ntd_id", "agency", "rtpa_name"]
mode_cols = ["Mode", "rtpa_name"]
tos_cols = ["TOS", "rtpa_name"]

# by_agency_long = _01_ntd_ridership_utils.sum_by_group(df, agency_cols)
# by_mode_long = _01_ntd_ridership_utils.sum_by_group(df, mode_cols)
# by_tos_long = _01_ntd_ridership_utils.sum_by_group(df, tos_cols)

monthly_group_col_2 = [
            'period_year',
            'period_month',
            'period_year_month']

monthly_agg_col = {
            "upt":"sum",
            "previous_y_m_upt":"sum",
            "change_1yr":"sum"
            }
monthly_change_col ="previous_y_m_upt"

by_agency_long = sum_by_group(
                df = df,
                group_cols= agency_cols,
                group_col2= monthly_group_col_2,# look into combingin with base grou_cols
                agg_cols = monthly_agg_col,
                change_col= monthly_change_col
            )

by_mode_long = sum_by_group(
                df = df,
                group_cols= mode_cols,
                group_col2= monthly_group_col_2,# look into combingin with base grou_cols
                agg_cols = monthly_agg_col,
                change_col= monthly_change_col
            )
    
by_tos_long = sum_by_group(
                df = df,
                group_cols= tos_cols,
                group_col2= monthly_group_col_2,# look into combingin with base grou_cols
                agg_cols = monthly_agg_col,
                change_col= monthly_change_col
            )

# remove zero UPT rows 
by_agency_long_no_zero_upt = remove_zero_upt_rows(by_agency_long)

# agg by agency, for pie chart
agency_agg_yr = group_by_agency(by_agency_long)

# total UPT check 
total_upt = by_agency_long["upt"].sum()
agency_count = by_agency_long["agency"].nunique()

In [ ]:
# REMOVE

# I STILL NEED FILTERED df BY AGENCY, MODE AND TOS

# by_agency_long = assemble_long_df(by_agency, agency_cols)
# by_mode_long = assemble_long_df(by_mode, mode_cols)
# by_tos_long = assemble_long_df(by_tos, tos_cols)

# by_agency_long_no_zero_upt = remove_zero_upt_rows(by_agency_long)

## TEST Charts

In [ ]:
LABELING_DICT = {
    "upt": "Unlinked Passenger Trips",
    "change_1yr": "Change in Unlinked Passenger Trips from Prior Year",
    "TOS": "Type of Service",
    "year_month": "Date",
}


def labeling(word: str) -> str:
    return label_visualization(word, LABELING_DICT)


WIDTH = 300
HEIGHT = 150

In [ ]:
def make_line_chart(
    df: pd.DataFrame,
    y_col: str,
    color_col: str,
) -> alt.Chart:
    df = df[df[y_col] > 0].dropna(subset=y_col)

    x_label = [
        i
        for i in df.period_year_month.unique()
        if any(substring in i for substring in ["-01", "-06"])
    ]
    chart = (
        (
            alt.Chart(df)
            .mark_line()
            .encode(
                x=alt.X(
                    "period_year_month:O", axis=alt.Axis(values=x_label), title="Date"
                ),
                y=alt.Y(y_col, title=labeling(y_col)),
                color=alt.Color(
                    color_col,
                    title="",
                    scale=alt.Scale(
                        range=cp.CALITP_CATEGORY_BRIGHT_COLORS
                        + cp.CALITP_CATEGORY_BOLD_COLORS
                    ),
                ),
                tooltip=["period_year_month", y_col, color_col, "rtpa_name"],
            )
            .properties(width=WIDTH, height=HEIGHT)
            .facet(color_col, columns=2, title="")
            .resolve_scale(y="independent")
        )
        .properties(title=f"{labeling(y_col)} by {labeling(color_col)}")
        .interactive()
    )

    return chart

In [ ]:
def make_bar_chart(
    df: pd.DataFrame,
    y_col: str,
    color_col: str,
) -> alt.Chart:

    def short_label(word):
        shorten_dict = {
            "change_1yr": "Change",
            "pct_change_1yr": "Change",
        }
        return shorten_dict[word]

    # For change column, we are missing everything prior to 2023
    # df = df.dropna(subset = y_col)

    # need flag for y_col >,<, 0, missing?
    # count function to how many agencies fall in those categories, then look at those agencies
    # present table

    x_label = [
        i
        for i in df.period_year_month.unique()
        if any(substring in i for substring in ["-01", "-03", "-06", "-09"])
    ]

    chart = (
        (
            alt.Chart(df)
            .mark_bar()
            .encode(
                x=alt.X(
                    "period_year_month:O", axis=alt.Axis(values=x_label), title="Date"
                ),
                y=alt.Y(y_col, title=short_label(y_col)),
                color=alt.Color(
                    color_col,
                    title="",
                    scale=alt.Scale(
                        range=cp.CALITP_CATEGORY_BRIGHT_COLORS
                        + cp.CALITP_CATEGORY_BOLD_COLORS
                    ),
                ),
                tooltip=["period_year_month", y_col, color_col, "rtpa_name"],
            )
            .properties(width=WIDTH, height=HEIGHT)
            .facet(color_col, columns=2, title="")
            .resolve_scale(x="shared", y="independent")
        )
        .properties(title=f"{labeling(y_col)} by {labeling(color_col)}")
        .interactive()
    )

    return chart

In [ ]:
### initial pie code
def make_pie_chart(df, col, color_col):

    pie = (
        alt.Chart(df)
        .mark_arc(radius=150)
        .encode(
            theta=col,
            color=color_col,
            tooltip=["agency", "total_upt", "pct_of_total_upt"],
        )
        .properties(
            title=f"Total Unlinked Passenger Trips per agency in RTPA since {MIN_YEAR}",
        )
    )

    return pie

In [ ]:
## moved to prod notebook 1/15/2025
# simple bar chart for total agencies and UPT
def total_upt_chart(df: pd.DataFrame, x_col: str, y_col: str, tool_tip: list):
    bar_chart = (
        alt.Chart(df)
        .mark_bar()
        .encode(
            x=alt.X(x_col).sort("-y"),
            y=alt.Y(y_col),
            tooltip=tool_tip,
            color=alt.Color(
                x_col,
                title="",
                scale=alt.Scale(
                    range=cp.CALITP_CATEGORY_BRIGHT_COLORS
                    + cp.CALITP_CATEGORY_BOLD_COLORS
                ),
            ),
        )
        .properties(
            title=f"Total Unlinked Passenger Trips per agency in RTPA since {MIN_YEAR}",
            width=WIDTH,
            height=HEIGHT,
        )
        .resolve_scale(y="independent")
        .interactive()
    )

    return bar_chart

### Totals

In [ ]:
Markdown(
    f"""
Within {rtpa}:
- Number of Agencies/Operators: <b>{agency_count}</b>.
- Total Unlinked Passenger Trips since {MIN_YEAR}: <b>{total_upt:,}</b>.
- Individual agency/operator ridership breakdown:
"""
)

In [ ]:
df_html = agency_agg_yr.reset_index(drop=True).to_html()

print(df_html)

In [ ]:
df_markdown = agency_agg_yr.reset_index(drop=True).to_markdown()

print(df_markdown)

In [ ]:
tooltip_list = ["agency", "total_upt", "pct_of_total_upt"]

total_upt_chart(agency_agg_yr, x_col="agency", y_col="total_upt", tool_tip=tooltip_list)

In [ ]:
make_pie_chart(agency_agg_yr, col="total_upt", color_col="agency")

### Transit Agency

In [ ]:
by_agency_long.head()

In [ ]:
make_line_chart(by_agency_long, y_col="upt", color_col="agency")

Change in Unlinked Passenger Trips from the prior year. For example, July 2023's change would be the change in July 2023's reported values against July 2022's reported values.

In [ ]:
# TEST OF BAR CHART WITH % CHANGE 1 YEAR
make_bar_chart(
    by_agency_long_no_zero_upt[by_agency_long_no_zero_upt["period_year"] >= 2018],
    y_col="pct_change_1yr",
    color_col="agency",
)

In [ ]:
make_bar_chart(
    by_agency_long_no_zero_upt[by_agency_long_no_zero_upt["period_year"] >= 2024],
    y_col="change_1yr",
    color_col="agency",
)

In [ ]:
make_bar_chart(by_agency_long_no_zero_upt, y_col="change_1yr", color_col="agency")

### Transit Mode

In [ ]:
make_line_chart(by_mode_long, y_col="upt", color_col="Mode")

In [ ]:
make_bar_chart(
    by_mode_long[by_mode_long["period_year"] >= 2024],
    y_col="change_1yr",
    color_col="Mode",
)

### Type of Service

In [ ]:
make_line_chart(by_tos_long, y_col="upt", color_col="TOS")

In [ ]:
make_bar_chart(
    by_tos_long[by_tos_long["period_year"] >= 2024], y_col="change_1yr", color_col="TOS"
)