## Compile Projects
To-do
* Figure out how to version things b/c projects will get updated and we want to track any changes.
* This only needs to be done with data from lp2000 and ctips.
* Need to track changes across all the different dataframes
* Use merges to figure it out?

In [1]:
import hashlib
from datetime import datetime

import _harmonization_utils as har_utils
import _lrtp_utils as lrtp_utils
import _sb1_utils as sb1_utils
import _specific_list_utils
import _state_rail_plan_utils as srp_utils
import geopandas as gpd
import pandas as pd
from calitp_data_analysis.sql import to_snakecase

In [2]:
pd.options.display.max_columns = 100
pd.options.display.float_format = "{:.2f}".format
pd.set_option("display.max_rows", None)
pd.set_option("display.max_colwidth", None)

In [3]:
GCS_FILE_PATH = "gs://calitp-analytics-data/data-analyses/project_list/"

## General Functions

In [4]:
def create_notes(df, note_cols: list, new_col_name: str):
    """
    Concat multiple columns into one.
    """
    prefix = "_"
    for column in note_cols:
        df[f"{prefix}{column}"] = df[column].astype(str)
    note_cols = [prefix + sub for sub in note_cols]

    # https://stackoverflow.com/questions/65532480/how-to-combine-column-names-and-values
    def combine_notes(x):
        return ", ".join([col + ": " + x[col] for col in note_cols])

    df[new_col_name] = df.apply(combine_notes, axis=1)
    df[new_col_name] = df[new_col_name].str.replace("_", " ")

    return df

In [5]:
def separate_out_df(df: pd.DataFrame, columns_to_keep: list) -> pd.DataFrame:
    """
    Subset the DataFrame based on the specified columns to keep,
    drop any rows in which the values are NaN or "None."

    Parameters:
    df (pd.DataFrame): Input DataFrame.
    columns_to_keep (list): List of column names to keep in the DataFrame.

    Returns:
    pd.DataFrame: DataFrame with specified columns and cleaned rows.
    """
    # Subset DataFrame based on columns_to_keep
    df2 = df[columns_to_keep]

    # Fill in missing values with 'none' if possible
    try:
        df2 = df2.fillna("none")
    except:
        df2

    # Remove 'project_number' from columns_to_keep
    columns_to_keep.remove("project_number")

    # Drop rows that are NaN or "None" based on how many columns are being included in the
    # new dataframe
    if len(columns_to_keep) == 1:
        # Drop rows with any NaN values
        df2 = df2.dropna(how="any")
        # Drop rows where any value in the row is 'none'
        df2 = df2[
            df2.applymap(lambda x: x.lower() if isinstance(x, str) else x) != "none"
        ].dropna()
    else:
        # Keep any row that has a non-null value in at least one of the specified columns
        df2 = df2.dropna(how="all", subset=columns_to_keep)

    print(f"Number of rows left {len(df2)}")
    return df2

In [6]:
def explode_dataframe(df: pd.DataFrame, column_to_explode: str) -> pd.DataFrame:
    """
    Explode a DataFrame based on a specified column.

    This function converts a column of lists or strings separated by commas into multiple rows,
    with each element in the list or string becoming a separate row entry.

    Parameters:
    df (pd.DataFrame): Input DataFrame.
    column_to_explode (str): Name of the column to explode.

    Returns:
    pd.DataFrame: Exploded DataFrame.
    """
    # Apply a function to the specified column to split the strings into lists of elements
    df["Column2"] = df[column_to_explode].apply(
        lambda x: [int(i) if i.isdigit() else i for i in x.replace(",", "").split()]
    )

    # Drop the original column that was exploded
    df = df.drop(columns=[column_to_explode])

    # Explode the DataFrame based on the newly created 'Column2'
    df2 = df.explode("Column2")

    # Rename the exploded column back to the original column name
    df2 = df2.rename(columns={"Column2": column_to_explode})

    df2 = df2.sort_values(by=["project_number"]).reset_index(drop=True)
    return df2

In [7]:
def generate_hash(string) -> str:

    hash_object = hashlib.sha1(string.encode())
    hash_hex = hash_object.hexdigest()
    return hash_hex[:10]

In [8]:
def generate_project_id(df: pd.DataFrame, project_name_col: str) -> pd.DataFrame:
    df = df.reset_index(drop=True)
    df["index_number"] = df.index
    df["combo"] = df.index_number.astype("str") + df[project_name_col].astype('str').fillna("none")
    df["project_number"] = df["combo"].apply(generate_hash)
    df = df.drop(columns=["index_number", "combo"])

    print("Checking that there are the same number of unique project numbers & rows")
    print(f"{len(df) == df.project_number.nunique()}")
    return df

## Separate out data based on schema

### LRTP/LOST

In [9]:
lrtp_lost_df, lrtp_lost_gdf = lrtp_utils.all_mpo(True)

/home/jovyan/data-analyses/project_list/_lrtp_utils.py:66: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cost_columns = df.columns[df.columns.str.contains("(cost|funds)")].tolist()
/home/jovyan/data-analyses/project_list/_lrtp_utils.py:66: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cost_columns = df.columns[df.columns.str.contains("(cost|funds)")].tolist()
/home/jovyan/data-analyses/project_list/_lrtp_utils.py:66: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cost_columns = df.columns[df.columns.str.contains("(cost|funds)")].tolist()
/home/jovyan/data-analyses/project_list/_lrtp_utils.py:66: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cost_columns = df.columns[df.columns.str.contains("(cost|funds)")].tolist()
/home/jovyan/data-analyses/project_list/_lrtp_utils.py:66: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cost_columns = df.columns[df.columns.str.contains("(cost|funds)")].tolist()
/home/jovyan/data-analyses/project_list/_lrtp_utils.py:66: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cost_columns = df.columns[df.columns.str.contains("(cost|funds)")].tolist()
/home/jovyan/data-analyses/project_list/_lrtp_utils.py:66: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cost_columns = df.columns[df.columns.str.contains("(cost|funds)")].tolist()
/home/jovyan/data-analyses/project_list/_lrtp_utils.py:66: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cost_columns = df.columns[df.columns.str.contains("(cost|funds)")].tolist()

96 rows are headers

/home/jovyan/data-analyses/project_list/_lrtp_utils.py:66: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cost_columns = df.columns[df.columns.str.contains("(cost|funds)")].tolist()
/home/jovyan/data-analyses/project_list/_lrtp_utils.py:720: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  sandag.cost2020m.str.replace("$", "")
/home/jovyan/data-analyses/project_list/_lrtp_utils.py:66: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cost_columns = df.columns[df.columns.str.contains("(cost|funds)")].tolist()

65 rows are headers

/home/jovyan/data-analyses/project_list/_lrtp_utils.py:66: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cost_columns = df.columns[df.columns.str.contains("(cost|funds)")].tolist()
/home/jovyan/data-analyses/project_list/_lrtp_utils.py:66: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cost_columns = df.columns[df.columns.str.contains("(cost|funds)")].tolist()
/home/jovyan/data-analyses/project_list/_lrtp_utils.py:66: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cost_columns = df.columns[df.columns.str.contains("(cost|funds)")].tolist()

360 rows are headers

/home/jovyan/data-analyses/project_list/_lrtp_utils.py:66: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cost_columns = df.columns[df.columns.str.contains("(cost|funds)")].tolist()
/home/jovyan/data-analyses/project_list/_lrtp_utils.py:66: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cost_columns = df.columns[df.columns.str.contains("(cost|funds)")].tolist()

68 rows are headers

/home/jovyan/data-analyses/project_list/_lrtp_utils.py:66: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cost_columns = df.columns[df.columns.str.contains("(cost|funds)")].tolist()
/home/jovyan/data-analyses/project_list/_lrtp_utils.py:66: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cost_columns = df.columns[df.columns.str.contains("(cost|funds)")].tolist()
/home/jovyan/data-analyses/project_list/_lrtp_utils.py:66: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cost_columns = df.columns[df.columns.str.contains("(cost|funds)")].tolist()
/home/jovyan/data-analyses/project_list/_lrtp_utils.py:66: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  cost_columns = df.columns[df.columns.str.contains("(cost|funds)")].tolist()

In [10]:
lrtp_lost_df = generate_project_id(lrtp_lost_df, "project_title")

Checking that there are the same number of unique project numbers & rows
True

In [11]:
lrtp_lost_df.sample()

,project_title,lead_agency,project_year,project_description,total_project_cost,geometry,city,county,data_source,notes,project_number
429,Silver Dollar Way Extension,Bcag,-,From Mlk Parkway To Fair St. Connect Exist Road Stubs,2760000.00,POINT (-121.811009 39.718602),None,None,Bcag Lrtp,"Project Type: Capacity Increasing, Status: Unconstrained, Fund Estimate: $2.76 Million, Fund Source: Unfunded",0a4fe365ba

In [12]:
lrtp_lost_county = separate_out_df(lrtp_lost_df, ["project_number", "county"])

Number of rows left 4012

In [13]:
lrtp_lost_city = separate_out_df(lrtp_lost_df, ["project_number", "city"])

Number of rows left 745

In [14]:
lrtp_lost_agency = separate_out_df(lrtp_lost_df, ["project_number", "lead_agency"])

Number of rows left 16276

In [15]:
lrtp_lost_geo = separate_out_df(lrtp_lost_df, ["project_number", "geometry"])

Number of rows left 1357

In [16]:
lrtp_to_drop = ["county", "city", "lead_agency", "geometry"]

In [17]:
lrtp_lost_df = lrtp_lost_df.drop(columns=lrtp_to_drop)

In [18]:
lrtp_lost_df.sample()

,project_title,project_year,project_description,total_project_cost,data_source,notes,project_number
13594,None,2040,Widen From 2 To 4 Lanes.,5402895.00,Stancog Lrtp,"Jurisdiction: Patterson, Location: Ward Av, Project Limits: Sperry Av To American Eagle Way, Funding Source: Measure L, Sb 1, Stip, Cmaq, Stbg, System Preserv : Nan, Capacity Enhance : X, Safety: X, Oper : Nan, Complete Streets: X, Active\nTransporta Tion: Nan, Transit: Nan, Other: Nan",ea2d238e75

### SB1

In [19]:
sb1_df = sb1_utils.load_sb1()

/home/jovyan/data-analyses/project_list/_sb1_utils.py:23: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  gdf[i]
/home/jovyan/data-analyses/project_list/_sb1_utils.py:23: FutureWarning: The default value of regex will change from True to False in a future version.
  gdf[i]

0 rows are mising geometry
7917 rows contain invalid geography

In [20]:
sb1_df.sample()

,projectid,projname,projcatcode,projcategory,projprogcode,projprogram,multiprogfunded,projstatus,description,cost,assemblydistrict,senatedistrict,assemblycode,senatecode,countyname,cityname,countycode,citycode,appagencyname,impagencyname,geometry,totalcosts,routes,constyear,costfull,projagency
7551,LsrFy18195942Pp308,Golden State Boulevard Over Fowler Switch Bridge Replacement,Local,Local And Regional,Lsr1819,201819 Local Streets And Roads,NaN,PreConstruction,Replace Bridge,NaN,31,14,31,14,Fresno Submitted By County,NaN,Fre,NaN,NaN,NaN,None,NaN,NaN,2023,0.00,Fresno County

In [21]:
sb1_df = generate_project_id(sb1_df, "projectid")

Checking that there are the same number of unique project numbers & rows
True

#### Check that assemblydistrict and assemblycode are the same values
* Yes they are, just padded with zeroes or spaced out differently.

In [22]:
sb1_df["assembly_same"] = sb1_df.assemblycode == sb1_df.assemblydistrict

In [23]:
sb1_df.assembly_same.value_counts()

True     7217
False    1969
Name: assembly_same, dtype: int64

In [24]:
sb1_df.loc[sb1_df.assembly_same == False][["assemblycode", "assemblydistrict"]].sample(
    10
)

     assemblycode assemblydistrict
17         060809         06 08 09
4594           05                5
4183           03                3
2377           03                3
5674           06                6
691          3537            35 37
7827         7778            77 78
8235           01             01 1
3848           05                5
8406           02                2

In [25]:
sb1_df["senate_same"] = sb1_df.senatedistrict == sb1_df.senatecode

In [26]:
sb1_df.senate_same.value_counts()

True     6950
False    2236
Name: senate_same, dtype: int64

In [27]:
sb1_county = separate_out_df(sb1_df, ["project_number", "countyname"])

Number of rows left 9184

In [28]:
sb1_assembly = separate_out_df(sb1_df, ["project_number", "assemblydistrict"])

Number of rows left 9185

In [29]:
sb1_assembly = explode_dataframe(sb1_assembly, "assemblydistrict")

In [30]:
# sb1_assembly.loc[sb1_assembly.project_number == "001784c575"]

In [31]:
# sb1_df.loc[sb1_df.project_number == "001784c575"]

In [32]:
sb1_senate = separate_out_df(sb1_df, ["project_number", "senatedistrict"])

Number of rows left 9185

In [33]:
sb1_senate = explode_dataframe(sb1_senate, "senatedistrict")

In [34]:
sb1_city = separate_out_df(sb1_df, ["project_number", "cityname"])

Number of rows left 6696

In [35]:
sb1_geo = separate_out_df(sb1_df, ["project_number", "geometry"])

Number of rows left 1585

In [36]:
sb1_awards = separate_out_df(sb1_df, ["project_number", "projprogram"])

Number of rows left 9186

In [37]:
sb1_agencies = separate_out_df(
    sb1_df, ["project_number", "projagency", "appagencyname", "impagencyname"]
)

Number of rows left 9186

In [38]:
sb1_df = sb1_df.drop(
    columns=[
        "countyname",
        "assemblydistrict",
        "senatedistrict",
        "cityname",
        "geometry",
        "projprogram",
        "projagency",
        "appagencyname",
        "impagencyname",
        "assemblycode",
        "senatecode",
        "countycode",
        "citycode",
        "assembly_same",
    ]
)

In [39]:
sb1_df.sample()

,projectid,projname,projcatcode,projcategory,projprogcode,multiprogfunded,projstatus,description,cost,totalcosts,routes,constyear,costfull,project_number,senate_same
6854,LsrFy18195323Pp563,Street Rehabilitaion Project Fy1718 Carryover,Local,Local And Regional,Lsr1819,NaN,PreConstruction,This Project Is Being Carried Over From Fy201718 The Project Consist Of 2Inch ColdMill Of Existing Roadway And Constructing New Asphalt Layer The Project Also Includes UpgradeReplacement Of Accessible Ramps Minor Curb And Gutter Repairs And ReStriping,NaN,NaN,NaN,2018,0.00,35cdee8755,True

### LP2000

In [40]:
def load_lp2000(file: str):

    df_project = to_snakecase(
        pd.read_excel(f"{GCS_FILE_PATH}LP2000_CTIPS/{file}", sheet_name="project")
    )

    df_county = to_snakecase(
        pd.read_excel(f"{GCS_FILE_PATH}LP2000_CTIPS/{file}", sheet_name="county")
    ).drop(columns=["project_label_name"])

    df_district = to_snakecase(
        pd.read_excel(f"{GCS_FILE_PATH}LP2000_CTIPS/{file}", sheet_name="district")
    ).drop(columns=["project_label_name"])

    df_award = to_snakecase(
        pd.read_excel(f"{GCS_FILE_PATH}LP2000_CTIPS/{file}", sheet_name="awards")
    )

    df_phase = to_snakecase(
        pd.read_excel(f"{GCS_FILE_PATH}LP2000_CTIPS/{file}", sheet_name="phase_funding")
    )

    return df_project, df_county, df_district, df_award, df_phase

In [41]:
(
    lp2000_project,
    lp2000_county,
    lp2000_district,
    lp2000_award,
    lp2000_phase,
) = load_lp2000("LP2000_projects.xlsx")

In [42]:
lp2000_project = generate_project_id(lp2000_project, "project_id")

Checking that there are the same number of unique project numbers & rows
True

In [43]:
def add_project_number(
    df_with_project_id: pd.DataFrame, right_project: pd.DataFrame, merge_col: str
) -> pd.DataFrame:
    m1 = pd.merge(df_with_project_id, right_project, on=merge_col, how="inner")
    m1 = m1.drop(columns = merge_col)
    return m1

In [44]:
lp2000_county = add_project_number(lp2000_project, lp2000_county, "project_id")

In [45]:
lp2000_district = add_project_number(lp2000_project, lp2000_district, "project_id")

In [46]:
lp2000_award = add_project_number(lp2000_project, lp2000_award, "project_id")

In [47]:
lp2000_phase = add_project_number(lp2000_project, lp2000_phase, "project_id")

### CTIPS

In [48]:
def load_ctips(file: str):

    df_project = to_snakecase(
        pd.read_excel(f"{GCS_FILE_PATH}LP2000_CTIPS/{file}", sheet_name="project")
    )

    df_county = to_snakecase(
        pd.read_excel(f"{GCS_FILE_PATH}LP2000_CTIPS/{file}", sheet_name="county")
    )

    df_district = to_snakecase(
        pd.read_excel(f"{GCS_FILE_PATH}LP2000_CTIPS/{file}", sheet_name="district")
    )

    df_phase = to_snakecase(
        pd.read_excel(f"{GCS_FILE_PATH}LP2000_CTIPS/{file}", sheet_name="phase_funding")
    )

    df_award = to_snakecase(
        pd.read_excel(f"{GCS_FILE_PATH}LP2000_CTIPS/{file}", sheet_name="awards")
    )

    df_house = to_snakecase(
        pd.read_excel(f"{GCS_FILE_PATH}LP2000_CTIPS/{file}", sheet_name="us_house")
    )

    df_senate = to_snakecase(
        pd.read_excel(f"{GCS_FILE_PATH}LP2000_CTIPS/{file}", sheet_name="senate")
    )

    df_assembly = to_snakecase(
        pd.read_excel(f"{GCS_FILE_PATH}LP2000_CTIPS/{file}", sheet_name="assembly")
    )
    return (
        df_project,
        df_county,
        df_district,
        df_phase,
        df_award,
        df_house,
        df_senate,
        df_assembly,
    )

In [49]:
(
    ctips_project,
    ctips_county,
    ctips_district,
    ctips_phase,
    ctips_award,
    ctips_house,
    ctips_senate,
    ctips_assembly,
) = load_ctips("CTIPS_data.xlsx")

In [50]:
ctips_project = generate_project_id(ctips_project, "ctips_id")

Checking that there are the same number of unique project numbers & rows
True

In [51]:
ctips_project.sample()

,ctips_id,chg_offcl,chg_qual1,chg_qual2,districtid,document,docyear,ea_number,needpurpose,ppno,proj_desc,postmiles1,pm1b,pm2b,pm3b,pm1a,pm2a,pm3a,route1,route2,route3,title,project_number
4825,13000003237,3,8,0,02,SHOPP,2022,3H770,None,3707,"Near Los Molinos, From Butte County Line To South Of Los Molinos Creek Bridge. Rehabilitate Pavement, Upgrade Guardrail And Transportation Management System (Tms) Elements, Upgrade Facilities To Meet Americans With Disabilities Act (Ada) Standards, Rehabilitate Drainage Systems, And Widen Shoulders. (G13 Contingency)",0.00,0.00,0.00,0.00,12.50,0.00,0.00,99,None,None,None,a39bf2278c

In [52]:
ctips_project.shape

(27016, 23)

In [53]:
ctips_county = add_project_number(ctips_project, ctips_county, "ctips_id")

In [54]:
ctips_district = add_project_number(ctips_project, ctips_district, "ctips_id")

In [55]:
ctips_phase = add_project_number(ctips_project, ctips_phase, "ctips_id")

In [56]:
ctips_award = add_project_number(ctips_project, ctips_award, "ctips_id")

In [57]:
ctips_house = add_project_number(ctips_project, ctips_house, "ctips_id")

In [58]:
ctips_senate = add_project_number(ctips_project, ctips_senate, "ctips_id")

In [59]:
ctips_assembly = add_project_number(ctips_project, ctips_assembly, "ctips_id")

In [60]:
ctips_assembly.shape

(4679, 23)

### State Rail Plan

In [61]:
srp_df = har_utils.load_state_rail_plan()

In [62]:
srp_df.sample()

,project_time_horizon,project_name,project_description,lead_agency,total_project_cost,srp_region,corridor,sub_corridor_node_1,sub_corridor_node_2,itsp_corridor,project_category
225,Long Term,Castroville - Monterey segment,"This project is part of the larger Monterey Regional (Around the Bay) service; which includes track, signal, and structure upgrades.",TAMC,222700000,Central Coast,Coast Route Corridor,Castroville,Monterey,Central Coast - San Jose/ San Francisco Bay Area,Capital

In [63]:
srp_df = generate_project_id(srp_df, "project_name")

Checking that there are the same number of unique project numbers & rows
True

In [64]:
srp_df_agency = separate_out_df(srp_df, ["project_number", "lead_agency"])

Number of rows left 263

In [65]:
srp_df.columns

Index(['project_time_horizon', 'project_name', 'project_description',
       'lead_agency', 'total_project_cost', 'srp_region', 'corridor',
       'sub_corridor_node_1', 'sub_corridor_node_2', 'itsp_corridor',
       'project_category', 'project_number'],
      dtype='object')

In [66]:
notes_cols = ['project_time_horizon','srp_region', 'corridor', 'sub_corridor_node_1',
       'sub_corridor_node_2', 'itsp_corridor', 'project_category',]

In [67]:
# srp_df = create_notes(srp_df, notes_cols, 'notes')

In [68]:
# srp_df = srp_df.drop(columns = notes_cols + ['lead_agency'])

## Stack

### County