# Run Functions to Add Information to Projects

To run the data through the script, all you need to do is update `my_file` path to the most recent export from FMIS and QMRS uploaded to GCS, then run the function in the section `Export Data` with your dataframe and the current date. Then your aggregated data will be ready in GCS.

In [1]:
import _data_utils
import _script_utils
import pandas as pd
from calitp_data_analysis.sql import to_snakecase

In [2]:
pip install intake-geopandas geopandas pyarrow

Requirement already satisfied: intake-geopandas in /opt/conda/lib/python3.11/site-packages (0.4.0)
Requirement already satisfied: geopandas in /opt/conda/lib/python3.11/site-packages (0.14.4)
Requirement already satisfied: pyarrow in /opt/conda/lib/python3.11/site-packages (17.0.0)
Requirement already satisfied: intake in /opt/conda/lib/python3.11/site-packages (from intake-geopandas) (2.0.9)
Requirement already satisfied: fiona>=1.8.21 in /opt/conda/lib/python3.11/site-packages (from geopandas) (1.10.1)
Requirement already satisfied: numpy>=1.22 in /opt/conda/lib/python3.11/site-packages (from geopandas) (2.0.2)
Requirement already satisfied: packaging in /opt/conda/lib/python3.11/site-packages (from geopandas) (26.2)
Requirement already satisfied: pandas>=1.4.0 in /opt/conda/lib/python3.11/site-packages (from geopandas) (2.2.3)
Requirement already satisfied: pyproj>=3.3.0 in /opt/conda/lib/python3.11/site-packages (from geopandas) (3.7.2)
Requirement already satisfied: shapely>=1.8.0 in /opt/conda/lib/python3.11/site-packages (from geopandas) (2.1.2)
Requirement already satisfied: attrs>=19.2.0 in /opt/conda/lib/python3.11/site-packages (from fiona>=1.8.21->geopandas) (24.2.0)
Requirement already satisfied: certifi in /opt/conda/lib/python3.11/site-packages (from fiona>=1.8.21->geopandas) (2024.8.30)
Requirement already satisfied: click~=8.0 in /opt/conda/lib/python3.11/site-packages (from fiona>=1.8.21->geopandas) (8.1.7)
Requirement already satisfied: click-plugins>=1.0 in /opt/conda/lib/python3.11/site-packages (from fiona>=1.8.21->geopandas) (1.1.1.2)
Requirement already satisfied: cligj>=0.5 in /opt/conda/lib/python3.11/site-packages (from fiona>=1.8.21->geopandas) (0.7.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.11/site-packages (from pandas>=1.4.0->geopandas) (2.9.0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.11/site-packages (from pandas>=1.4.0->geopandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.11/site-packages (from pandas>=1.4.0->geopandas) (2024.2)
Requirement already satisfied: fsspec>=2023.0.0 in /opt/conda/lib/python3.11/site-packages (from intake->intake-geopandas) (2024.5.0)
Requirement already satisfied: pyyaml in /opt/conda/lib/python3.11/site-packages (from intake->intake-geopandas) (6.0.2)
Requirement already satisfied: platformdirs in /opt/conda/lib/python3.11/site-packages (from intake->intake-geopandas) (4.3.6)
Requirement already satisfied: networkx in /opt/conda/lib/python3.11/site-packages (from intake->intake-geopandas) (3.4.2)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas>=1.4.0->geopandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
pip install intake

Requirement already satisfied: intake in /opt/conda/lib/python3.11/site-packages (2.0.9)
Requirement already satisfied: fsspec>=2023.0.0 in /opt/conda/lib/python3.11/site-packages (from intake) (2024.5.0)
Requirement already satisfied: pyyaml in /opt/conda/lib/python3.11/site-packages (from intake) (6.0.2)
Requirement already satisfied: platformdirs in /opt/conda/lib/python3.11/site-packages (from intake) (4.3.6)
Requirement already satisfied: networkx in /opt/conda/lib/python3.11/site-packages (from intake) (3.4.2)
Note: you may need to restart the kernel to use updated packages.

In [4]:
pip install calitp_data_analysis

Requirement already satisfied: calitp_data_analysis in /opt/conda/lib/python3.11/site-packages (2026.3.9)
Requirement already satisfied: altair>=5.1.1 in /opt/conda/lib/python3.11/site-packages (from calitp_data_analysis) (5.4.1)
Requirement already satisfied: black==24.10.0 in /opt/conda/lib/python3.11/site-packages (from calitp_data_analysis) (24.10.0)
Requirement already satisfied: dask<2025.4.0,>=2024.10.0 in /opt/conda/lib/python3.11/site-packages (from calitp_data_analysis) (2025.3.1)
Requirement already satisfied: dask-geopandas>=0.5.0 in /opt/conda/lib/python3.11/site-packages (from calitp_data_analysis) (0.5.0)
Requirement already satisfied: gcsfs==2024.5.0 in /opt/conda/lib/python3.11/site-packages (from calitp_data_analysis) (2024.5.0)
Requirement already satisfied: geopandas<0.15.0,>=0.14.0 in /opt/conda/lib/python3.11/site-packages (from calitp_data_analysis) (0.14.4)
Requirement already satisfied: gtfs-segments==2.1.7 in /opt/conda/lib/python3.11/site-packages (from calitp_data_analysis) (2.1.7)
Requirement already satisfied: ipython<9.0.0,>=8.9.0 in /opt/conda/lib/python3.11/site-packages (from calitp_data_analysis) (8.28.0)
Requirement already satisfied: jinja2<4.0.0,>=3.1.3 in /opt/conda/lib/python3.11/site-packages (from calitp_data_analysis) (3.1.4)
Requirement already satisfied: pandas<3.0.0,>=2.0.0 in /opt/conda/lib/python3.11/site-packages (from calitp_data_analysis) (2.2.3)
Requirement already satisfied: pandas-gbq<0.20.0,>=0.19.1 in /opt/conda/lib/python3.11/site-packages (from calitp_data_analysis) (0.19.2)
Requirement already satisfied: pyairtable==2.2.2 in /opt/conda/lib/python3.11/site-packages (from calitp_data_analysis) (2.2.2)
Requirement already satisfied: requests<3.0.0,>=2.31.0 in /opt/conda/lib/python3.11/site-packages (from calitp_data_analysis) (2.34.2)
Requirement already satisfied: shapely<3.0.0,>=2.0.1 in /opt/conda/lib/python3.11/site-packages (from calitp_data_analysis) (2.1.2)
Requirement already satisfied: sqlalchemy<3.0.0,>=2.0.0 in /opt/conda/lib/python3.11/site-packages (from calitp_data_analysis) (2.0.36)
Requirement already satisfied: sqlalchemy-bigquery<2.0.0,>=1.6.1 in /opt/conda/lib/python3.11/site-packages (from calitp_data_analysis) (1.17.0)
Requirement already satisfied: click>=8.0.0 in /opt/conda/lib/python3.11/site-packages (from black==24.10.0->calitp_data_analysis) (8.1.7)
Requirement already satisfied: mypy-extensions>=0.4.3 in /opt/conda/lib/python3.11/site-packages (from black==24.10.0->calitp_data_analysis) (1.1.0)
Requirement already satisfied: packaging>=22.0 in /opt/conda/lib/python3.11/site-packages (from black==24.10.0->calitp_data_analysis) (26.2)
Requirement already satisfied: pathspec>=0.9.0 in /opt/conda/lib/python3.11/site-packages (from black==24.10.0->calitp_data_analysis) (1.1.1)
Requirement already satisfied: platformdirs>=2 in /opt/conda/lib/python3.11/site-packages (from black==24.10.0->calitp_data_analysis) (4.3.6)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /opt/conda/lib/python3.11/site-packages (from gcsfs==2024.5.0->calitp_data_analysis) (3.10.10)
Requirement already satisfied: decorator>4.1.2 in /opt/conda/lib/python3.11/site-packages (from gcsfs==2024.5.0->calitp_data_analysis) (5.1.1)
Requirement already satisfied: fsspec==2024.5.0 in /opt/conda/lib/python3.11/site-packages (from gcsfs==2024.5.0->calitp_data_analysis) (2024.5.0)
Requirement already satisfied: google-auth>=1.2 in /opt/conda/lib/python3.11/site-packages (from gcsfs==2024.5.0->calitp_data_analysis) (2.55.1)
Requirement already satisfied: google-auth-oauthlib in /opt/conda/lib/python3.11/site-packages (from gcsfs==2024.5.0->calitp_data_analysis) (1.4.0)
Requirement already satisfied: google-cloud-storage in /opt/conda/lib/python3.11/site-packages (from gcsfs==2024.5.0->calitp_data_analysis) (3.12.0)
Requirement already satisfied: scipy in /opt/conda/lib/python3.11/site-packages (from gtfs-segments==2.1.7->calitp_data_analysis) (1.14.1)
Requirement already satisfied: numpy in /opt/conda/lib/python3.11/site-packages (from gtfs-segments==2.1.7->calitp_data_analysis) (2.0.2)
Requirement already satisfied: matplotlib in /opt/conda/lib/python3.11/site-packages (from gtfs-segments==2.1.7->calitp_data_analysis) (3.9.2)
Requirement already satisfied: utm in /opt/conda/lib/python3.11/site-packages (from gtfs-segments==2.1.7->calitp_data_analysis) (0.8.1)
Requirement already satisfied: contextily in /opt/conda/lib/python3.11/site-packages (from gtfs-segments==2.1.7->calitp_data_analysis) (1.7.0)
Requirement already satisfied: isoweek in /opt/conda/lib/python3.11/site-packages (from gtfs-segments==2.1.7->calitp_data_analysis) (1.3.3)
Requirement already satisfied: faust-cchardet in /opt/conda/lib/python3.11/site-packages (from gtfs-segments==2.1.7->calitp_data_analysis) (2.1.19)
Requirement already satisfied: charset-normalizer in /opt/conda/lib/python3.11/site-packages (from gtfs-segments==2.1.7->calitp_data_analysis) (3.4.0)
Requirement already satisfied: folium in /opt/conda/lib/python3.11/site-packages (from gtfs-segments==2.1.7->calitp_data_analysis) (0.20.0)
Requirement already satisfied: thefuzz in /opt/conda/lib/python3.11/site-packages (from gtfs-segments==2.1.7->calitp_data_analysis) (0.22.1)
Requirement already satisfied: inflection in /opt/conda/lib/python3.11/site-packages (from pyairtable==2.2.2->calitp_data_analysis) (0.5.1)
Requirement already satisfied: pydantic in /opt/conda/lib/python3.11/site-packages (from pyairtable==2.2.2->calitp_data_analysis) (2.9.2)
Requirement already satisfied: typing-extensions in /opt/conda/lib/python3.11/site-packages (from pyairtable==2.2.2->calitp_data_analysis) (4.12.2)
Requirement already satisfied: urllib3>=1.26 in /opt/conda/lib/python3.11/site-packages (from pyairtable==2.2.2->calitp_data_analysis) (2.2.3)
Requirement already satisfied: jsonschema>=3.0 in /opt/conda/lib/python3.11/site-packages (from altair>=5.1.1->calitp_data_analysis) (4.23.0)
Requirement already satisfied: narwhals>=1.5.2 in /opt/conda/lib/python3.11/site-packages (from altair>=5.1.1->calitp_data_analysis) (1.10.0)
Requirement already satisfied: cloudpickle>=3.0.0 in /opt/conda/lib/python3.11/site-packages (from dask<2025.4.0,>=2024.10.0->calitp_data_analysis) (3.1.0)
Requirement already satisfied: partd>=1.4.0 in /opt/conda/lib/python3.11/site-packages (from dask<2025.4.0,>=2024.10.0->calitp_data_analysis) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in /opt/conda/lib/python3.11/site-packages (from dask<2025.4.0,>=2024.10.0->calitp_data_analysis) (6.0.2)
Requirement already satisfied: toolz>=0.10.0 in /opt/conda/lib/python3.11/site-packages (from dask<2025.4.0,>=2024.10.0->calitp_data_analysis) (1.0.0)
Requirement already satisfied: importlib_metadata>=4.13.0 in /opt/conda/lib/python3.11/site-packages (from dask<2025.4.0,>=2024.10.0->calitp_data_analysis) (8.5.0)
Requirement already satisfied: fiona>=1.8.21 in /opt/conda/lib/python3.11/site-packages (from geopandas<0.15.0,>=0.14.0->calitp_data_analysis) (1.10.1)
Requirement already satisfied: pyproj>=3.3.0 in /opt/conda/lib/python3.11/site-packages (from geopandas<0.15.0,>=0.14.0->calitp_data_analysis) (3.7.2)
Requirement already satisfied: jedi>=0.16 in /opt/conda/lib/python3.11/site-packages (from ipython<9.0.0,>=8.9.0->calitp_data_analysis) (0.19.1)
Requirement already satisfied: matplotlib-inline in /opt/conda/lib/python3.11/site-packages (from ipython<9.0.0,>=8.9.0->calitp_data_analysis) (0.1.7)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /opt/conda/lib/python3.11/site-packages (from ipython<9.0.0,>=8.9.0->calitp_data_analysis) (3.0.48)
Requirement already satisfied: pygments>=2.4.0 in /opt/conda/lib/python3.11/site-packages (from ipython<9.0.0,>=8.9.0->calitp_data_analysis) (2.18.0)
Requirement already satisfied: stack-data in /opt/conda/lib/python3.11/site-packages (from ipython<9.0.0,>=8.9.0->calitp_data_analysis) (0.6.2)
Requirement already satisfied: traitlets>=5.13.0 in /opt/conda/lib/python3.11/site-packages (from ipython<9.0.0,>=8.9.0->calitp_data_analysis) (5.14.3)
Requirement already satisfied: pexpect>4.3 in /opt/conda/lib/python3.11/site-packages (from ipython<9.0.0,>=8.9.0->calitp_data_analysis) (4.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.11/site-packages (from jinja2<4.0.0,>=3.1.3->calitp_data_analysis) (3.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.11/site-packages (from pandas<3.0.0,>=2.0.0->calitp_data_analysis) (2.9.0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.11/site-packages (from pandas<3.0.0,>=2.0.0->calitp_data_analysis) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.11/site-packages (from pandas<3.0.0,>=2.0.0->calitp_data_analysis) (2024.2)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.11/site-packages (from pandas-gbq<0.20.0,>=0.19.1->calitp_data_analysis) (75.1.0)
Requirement already satisfied: db-dtypes<2.0.0,>=1.0.4 in /opt/conda/lib/python3.11/site-packages (from pandas-gbq<0.20.0,>=0.19.1->calitp_data_analysis) (1.7.0)
Requirement already satisfied: pyarrow>=3.0.0 in /opt/conda/lib/python3.11/site-packages (from pandas-gbq<0.20.0,>=0.19.1->calitp_data_analysis) (17.0.0)
Requirement already satisfied: pydata-google-auth>=1.5.0 in /opt/conda/lib/python3.11/site-packages (from pandas-gbq<0.20.0,>=0.19.1->calitp_data_analysis) (1.9.1)
Requirement already satisfied: google-api-core<3.0.0dev,>=2.10.2 in /opt/conda/lib/python3.11/site-packages (from pandas-gbq<0.20.0,>=0.19.1->calitp_data_analysis) (2.31.0)
Requirement already satisfied: google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5 in /opt/conda/lib/python3.11/site-packages (from pandas-gbq<0.20.0,>=0.19.1->calitp_data_analysis) (3.42.1)
Requirement already satisfied: google-cloud-bigquery-storage<3.0.0dev,>=2.16.2 in /opt/conda/lib/python3.11/site-packages (from pandas-gbq<0.20.0,>=0.19.1->calitp_data_analysis) (2.39.0)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.11/site-packages (from requests<3.0.0,>=2.31.0->calitp_data_analysis) (3.10)
Requirement already satisfied: certifi>=2023.5.7 in /opt/conda/lib/python3.11/site-packages (from requests<3.0.0,>=2.31.0->calitp_data_analysis) (2024.8.30)
Requirement already satisfied: greenlet!=0.4.17 in /opt/conda/lib/python3.11/site-packages (from sqlalchemy<3.0.0,>=2.0.0->calitp_data_analysis) (3.1.1)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /opt/conda/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs==2024.5.0->calitp_data_analysis) (2.4.3)
Requirement already satisfied: aiosignal>=1.1.2 in /opt/conda/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs==2024.5.0->calitp_data_analysis) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /opt/conda/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs==2024.5.0->calitp_data_analysis) (24.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs==2024.5.0->calitp_data_analysis) (1.4.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs==2024.5.0->calitp_data_analysis) (6.1.0)
Requirement already satisfied: yarl<2.0,>=1.12.0 in /opt/conda/lib/python3.11/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs==2024.5.0->calitp_data_analysis) (1.15.5)
Requirement already satisfied: click-plugins>=1.0 in /opt/conda/lib/python3.11/site-packages (from fiona>=1.8.21->geopandas<0.15.0,>=0.14.0->calitp_data_analysis) (1.1.1.2)
Requirement already satisfied: cligj>=0.5 in /opt/conda/lib/python3.11/site-packages (from fiona>=1.8.21->geopandas<0.15.0,>=0.14.0->calitp_data_analysis) (0.7.2)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.63.2 in /opt/conda/lib/python3.11/site-packages (from google-api-core<3.0.0dev,>=2.10.2->pandas-gbq<0.20.0,>=0.19.1->calitp_data_analysis) (1.75.0)
Requirement already satisfied: protobuf<8.0.0,>=5.29.6 in /opt/conda/lib/python3.11/site-packages (from google-api-core<3.0.0dev,>=2.10.2->pandas-gbq<0.20.0,>=0.19.1->calitp_data_analysis) (7.35.1)
Requirement already satisfied: proto-plus<2.0.0,>=1.24.0 in /opt/conda/lib/python3.11/site-packages (from google-api-core<3.0.0dev,>=2.10.2->pandas-gbq<0.20.0,>=0.19.1->calitp_data_analysis) (1.28.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/conda/lib/python3.11/site-packages (from google-auth>=1.2->gcsfs==2024.5.0->calitp_data_analysis) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in /opt/conda/lib/python3.11/site-packages (from google-auth>=1.2->gcsfs==2024.5.0->calitp_data_analysis) (49.0.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /opt/conda/lib/python3.11/site-packages (from google-auth-oauthlib->gcsfs==2024.5.0->calitp_data_analysis) (2.0.0)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in /opt/conda/lib/python3.11/site-packages (from google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq<0.20.0,>=0.19.1->calitp_data_analysis) (2.6.0)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in /opt/conda/lib/python3.11/site-packages (from google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq<0.20.0,>=0.19.1->calitp_data_analysis) (2.10.0)
Requirement already satisfied: grpcio<2.0.0,>=1.59.0 in /opt/conda/lib/python3.11/site-packages (from google-cloud-bigquery-storage<3.0.0dev,>=2.16.2->pandas-gbq<0.20.0,>=0.19.1->calitp_data_analysis) (1.81.1)
Requirement already satisfied: zipp>=3.20 in /opt/conda/lib/python3.11/site-packages (from importlib_metadata>=4.13.0->dask<2025.4.0,>=2024.10.0->calitp_data_analysis) (3.20.2)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in /opt/conda/lib/python3.11/site-packages (from jedi>=0.16->ipython<9.0.0,>=8.9.0->calitp_data_analysis) (0.8.4)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/conda/lib/python3.11/site-packages (from jsonschema>=3.0->altair>=5.1.1->calitp_data_analysis) (2024.10.1)
Requirement already satisfied: referencing>=0.28.4 in /opt/conda/lib/python3.11/site-packages (from jsonschema>=3.0->altair>=5.1.1->calitp_data_analysis) (0.35.1)
Requirement already satisfied: rpds-py>=0.7.1 in /opt/conda/lib/python3.11/site-packages (from jsonschema>=3.0->altair>=5.1.1->calitp_data_analysis) (0.20.0)
Requirement already satisfied: locket in /opt/conda/lib/python3.11/site-packages (from partd>=1.4.0->dask<2025.4.0,>=2024.10.0->calitp_data_analysis) (1.0.0)
Requirement already satisfied: ptyprocess>=0.5 in /opt/conda/lib/python3.11/site-packages (from pexpect>4.3->ipython<9.0.0,>=8.9.0->calitp_data_analysis) (0.7.0)
Requirement already satisfied: wcwidth in /opt/conda/lib/python3.11/site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython<9.0.0,>=8.9.0->calitp_data_analysis) (0.2.13)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas<3.0.0,>=2.0.0->calitp_data_analysis) (1.16.0)
Requirement already satisfied: geopy in /opt/conda/lib/python3.11/site-packages (from contextily->gtfs-segments==2.1.7->calitp_data_analysis) (2.4.1)
Requirement already satisfied: mercantile in /opt/conda/lib/python3.11/site-packages (from contextily->gtfs-segments==2.1.7->calitp_data_analysis) (1.2.1)
Requirement already satisfied: pillow in /opt/conda/lib/python3.11/site-packages (from contextily->gtfs-segments==2.1.7->calitp_data_analysis) (11.0.0)
Requirement already satisfied: rasterio in /opt/conda/lib/python3.11/site-packages (from contextily->gtfs-segments==2.1.7->calitp_data_analysis) (1.4.4)
Requirement already satisfied: joblib in /opt/conda/lib/python3.11/site-packages (from contextily->gtfs-segments==2.1.7->calitp_data_analysis) (1.4.2)
Requirement already satisfied: xyzservices in /opt/conda/lib/python3.11/site-packages (from contextily->gtfs-segments==2.1.7->calitp_data_analysis) (2024.9.0)
Requirement already satisfied: branca>=0.6.0 in /opt/conda/lib/python3.11/site-packages (from folium->gtfs-segments==2.1.7->calitp_data_analysis) (0.8.2)
Requirement already satisfied: google-crc32c<2.0.0,>=1.6.0 in /opt/conda/lib/python3.11/site-packages (from google-cloud-storage->gcsfs==2024.5.0->calitp_data_analysis) (1.8.0)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.11/site-packages (from matplotlib->gtfs-segments==2.1.7->calitp_data_analysis) (1.3.0)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.11/site-packages (from matplotlib->gtfs-segments==2.1.7->calitp_data_analysis) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.11/site-packages (from matplotlib->gtfs-segments==2.1.7->calitp_data_analysis) (4.54.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/conda/lib/python3.11/site-packages (from matplotlib->gtfs-segments==2.1.7->calitp_data_analysis) (1.4.7)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/conda/lib/python3.11/site-packages (from matplotlib->gtfs-segments==2.1.7->calitp_data_analysis) (3.2.0)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/conda/lib/python3.11/site-packages (from pydantic->pyairtable==2.2.2->calitp_data_analysis) (0.7.0)
Requirement already satisfied: pydantic-core==2.23.4 in /opt/conda/lib/python3.11/site-packages (from pydantic->pyairtable==2.2.2->calitp_data_analysis) (2.23.4)
Requirement already satisfied: executing>=1.2.0 in /opt/conda/lib/python3.11/site-packages (from stack-data->ipython<9.0.0,>=8.9.0->calitp_data_analysis) (2.1.0)
Requirement already satisfied: asttokens>=2.1.0 in /opt/conda/lib/python3.11/site-packages (from stack-data->ipython<9.0.0,>=8.9.0->calitp_data_analysis) (2.4.1)
Requirement already satisfied: pure-eval in /opt/conda/lib/python3.11/site-packages (from stack-data->ipython<9.0.0,>=8.9.0->calitp_data_analysis) (0.2.3)
Requirement already satisfied: rapidfuzz<4.0.0,>=3.0.0 in /opt/conda/lib/python3.11/site-packages (from thefuzz->gtfs-segments==2.1.7->calitp_data_analysis) (3.14.5)
Requirement already satisfied: cffi>=2.0.0 in /opt/conda/lib/python3.11/site-packages (from cryptography>=38.0.3->google-auth>=1.2->gcsfs==2024.5.0->calitp_data_analysis) (2.0.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.41.0 in /opt/conda/lib/python3.11/site-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq<0.20.0,>=0.19.1->calitp_data_analysis) (1.81.1)
Requirement already satisfied: pyopenssl>=20.0.0 in /opt/conda/lib/python3.11/site-packages (from google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery!=2.4.*,<4.0.0dev,>=3.3.5->pandas-gbq<0.20.0,>=0.19.1->calitp_data_analysis) (26.3.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /opt/conda/lib/python3.11/site-packages (from pyasn1-modules>=0.2.1->google-auth>=1.2->gcsfs==2024.5.0->calitp_data_analysis) (0.6.3)
Requirement already satisfied: oauthlib>=3.0.0 in /opt/conda/lib/python3.11/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib->gcsfs==2024.5.0->calitp_data_analysis) (3.2.2)
Requirement already satisfied: propcache>=0.2.0 in /opt/conda/lib/python3.11/site-packages (from yarl<2.0,>=1.12.0->aiohttp!=4.0.0a0,!=4.0.0a1->gcsfs==2024.5.0->calitp_data_analysis) (0.2.0)
Requirement already satisfied: geographiclib<3,>=1.52 in /opt/conda/lib/python3.11/site-packages (from geopy->contextily->gtfs-segments==2.1.7->calitp_data_analysis) (2.1)
Requirement already satisfied: affine in /opt/conda/lib/python3.11/site-packages (from rasterio->contextily->gtfs-segments==2.1.7->calitp_data_analysis) (2.4.0)
Requirement already satisfied: pycparser in /opt/conda/lib/python3.11/site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth>=1.2->gcsfs==2024.5.0->calitp_data_analysis) (2.22)
Note: you may need to restart the kernel to use updated packages.

In [5]:
from calitp_data_analysis.gcs_geopandas import GCSGeoPandas
gcsgp = GCSGeoPandas()

In [6]:
pd.set_option("display.max_columns", 100)
pd.set_option("display.max_colwidth", None)

In [7]:
locodes = to_snakecase(
    pd.read_excel(
        f"gs://calitp-analytics-data/data-analyses/dla/e-76Obligated/locodes_updated7122021.xlsx"
    )
)

## Read in Data and function development / Test Function

For the following function:
* update the file path for `my_file` to the most recent file name of the FMIS & QMRS export
* the second kwargs is the unique recipient identifier, in this case it should stay the same with subsequent exports
* the third kwargs is the aggregation level you want for the data. Unless otherwise specified, it should be `agg` which is one row per project

In [8]:
GCS_FILE_PATH = "gs://calitp-analytics-data/data-analyses/dla/dla-iija"

In [9]:
# update this path to the latest IIJA data
my_file = "IIJA_ToDDS_20260623.xlsx"

### Check data
* July 2025 Notes
    * `summary_recipient_defined_text_field_1_value` changed to `summary_recipient` in `script_utils.run_script_original` and `script_utils.run_script_2025.`
    * `rk_locode` is missing so I used `run_script_original` instead.
    * Updated `_script_utils.add_county_abbrev()` because the values in the counties geojson in `shared_data_catalog.yml` changed.

In [10]:
check_data = to_snakecase(pd.read_excel(f"{GCS_FILE_PATH}/{my_file}", sheet_name="Sheet1"))

In [11]:
check_data.columns

Index(['fmis_transaction_date', 'program_code', 'unnamed:_2',
       'program_code_description', 'project_number',
       'recipient_project_number', '_10_id', 'project_title', 'county_code',
       'unnamed:_9', 'congressional_district', 'project_status_description',
       'project_description', 'improvement_type',
       'improvement_type_description', 'total_cost_amount',
       'obligations_amount', 'summary_recipient_defined_text_field_1_value'],
      dtype='object')

In [12]:
check_data.head(1)

,fmis_transaction_date,program_code,unnamed:_2,program_code_description,project_number,recipient_project_number,_10_id,project_title,county_code,unnamed:_9,congressional_district,project_status_description,project_description,improvement_type,improvement_type_description,total_cost_amount,obligations_amount,summary_recipient_defined_text_field_1_value
0,2022-10-27,YS30,NaN,SURFAC TRNSP BLK GRTS-FLX IIJA,Q101398,0100000193S,0100000193,IN DEL NORTE COUNTY NEAR CRESCENT CITY FROM 0.3 MILE SOUTH OF SMITH RIVER BRIDGE TO 0.4 MILE NORTH OF SMITH RIVER BRIDGE REPLACE BRIDGE,15,NaN,Cong Dist 1,Active,"SIXTEEN STOP-CONTROLLED INTERSECTIONS AT VARIOUS LOCATIONS SYSTEMICALLY IMPROVE MINOR STREET APPROACHES WITH A COMBINATION OF ADDITIONAL INTERSECTION WARNING/REGULATORY SIGNS, IMPROVED PAVEMENT MARKINGS, AND IMPROVED SIGHT TRIANGLES.",4,4R - No Added Capacity,366560.0,329904.0,L5425BCAG

### Run Script
* Choose between `run_script_original` or `run_script_2025` depending on the dataframe you receive.

In [13]:
df = _script_utils.run_script_original(
    file_name = my_file, 
    sheet = "Sheet1",
    recipient_column = "summary_recipient_defined_text_field_1_value", 
    df_agg_level = "agg"
)

Index(['fmis_transaction_date', 'project_number', 'implementing_agency',
       'summary_recipient_defined_text_field_1_value', 'funding_type_code',
       'program_code', 'program_code_description', 'recipient_project_number',
       'improvement_type', 'improvement_type_description',
       'program_code_description_for_description', 'project_title',
       'obligations_amount', 'total_cost_amount', 'congressional_district',
       'district', 'county_code', 'county_name', 'county_name_abbrev',
       'county_name_title', 'implementing_agency_locode', 'rtpa_name',
       'mpo_name'],
      dtype='object')

False

### Testing the data

In [14]:
len(df) == check_data.project_number.nunique()

False

In [15]:
len(df)

5331

In [16]:
check_data.project_number.nunique()

3451

In [41]:
df.project_number.value_counts().head(500)

project_number
5006912    17
6049028    11
6049032     9
0056349     9
P001692     8
           ..
5956224     2
39A7001     2
15A6004     2
15A6002     2
15A5028     2
Name: count, Length: 500, dtype: int64

In [38]:
check_data.project_number.value_counts().head(500)

project_number
5006912    34
P134040    20
6049028    18
0056349    18
6049032    17
           ..
P058134     4
31RH001     4
15C4001     4
15C6001     4
15C8001     4
Name: count, Length: 500, dtype: int64

### Compare with January 2026

In [27]:
jan_2026 = to_snakecase(pd.read_excel("gs://calitp-analytics-data/data-analyses/dla/dla-iija/IIJA_ToDDS_20260113.xlsx"))

In [28]:
jan_2026_agg = _script_utils.run_script_original(
    file_name = "IIJA_ToDDS_20260113.xlsx", 
    sheet = "IIJA_ToDDS",
    recipient_column = "summary_recipient_defined_text_field_1_value", 
    df_agg_level = "agg"
)

Index(['fmis_transaction_date', 'project_number', 'implementing_agency',
       'summary_recipient_defined_text_field_1_value', 'funding_type_code',
       'program_code', 'program_code_description', 'recipient_project_number',
       'improvement_type', 'improvement_type_description',
       'program_code_description_for_description', 'project_title',
       'obligations_amount', 'total_cost_amount', 'congressional_district',
       'district', 'county_code', 'county_name', 'county_name_abbrev',
       'county_name_title', 'implementing_agency_locode', 'rtpa_name',
       'mpo_name'],
      dtype='object')

True

### 5956224

In [43]:
print("June data")
display(check_data.loc[check_data.project_number == "5956224"].T)
display(df.loc[df.project_number == "5956224"].T)
print("January Data")
display(jan_2026.loc[jan_2026.project_number == "5956224"].T)
display(jan_2026_agg.loc[jan_2026_agg.project_number == "5956224"].T)

June data

,6270,6271,6272
fmis_transaction_date,2026-02-13 00:00:00,2026-02-17 00:00:00,2026-02-17 00:00:00
program_code,YS60,Y603,Y603
unnamed:_2,NaN,NaN,NaN
program_code_description,NATIONAL HIGHWAY PERF IIJA,NATIONAL HIGHWAY PERF IIJA,HIP BRIDGE FORMULA PROGRAM-25
project_number,5956224,5956224,5956224
recipient_project_number,0814000006L,0814000006L,0814000006L
_10_id,0814000006,0814000006,0814000006
project_title,"VARIOUS LOCATIONS THROUGHOUT RIVERSIDE COUNTY, PM00076 BRIDGE PREVENTIVE MAINTENANCE PROGRAM","VARIOUS LOCATIONS THROUGHOUT RIVERSIDE COUNTY, PM00076 BRIDGE PREVENTIVE MAINTENANCE PROGRAM","VARIOUS LOCATIONS THROUGHOUT RIVERSIDE COUNTY, PM00076 BRIDGE PREVENTIVE MAINTENANCE PROGRAM"
county_code,65,65,65
unnamed:_9,NaN,NaN,NaN
congressional_district,Cong Dist 3,Cong Dist 7,Cong Dist 7
project_status_description,Active,Active,Active
project_description,FOURTEEN (14) ROADWAY CURVES THROUGHOUT NEVADA COUNTY. APPLY HIGH FRICTION SURFACE TREATMENT (HFST).,"IN THE CITY OF FOLSOM, ON FOLSOM LAKE CROSSING BETWEEN FOLSOM AUBURN ROAD AND FOLSOM DAM ROAD CONSTRUCT ROADWAY SAFETY IMPROVEMENTS THAT MAY INCLUDE A MEDIAN BARRIER, PAVEMENT RESURFACING, UPDATED ROADWAY DELINEATION AND SEGMENT LIGHTING.","IN THE CITY OF FOLSOM, ON FOLSOM LAKE CROSSING BETWEEN FOLSOM AUBURN ROAD AND FOLSOM DAM ROAD CONSTRUCT ROADWAY SAFETY IMPROVEMENTS THAT MAY INCLUDE A MEDIAN BARRIER, PAVEMENT RESURFACING, UPDATED ROADWAY DELINEATION AND SEGMENT LIGHTING."
improvement_type,17,1,15
improvement_type_description,Construction Engineering,New Construction Roadway,Preliminary Engineering
total_cost_amount,195000.0,1281970.0,132442.0
obligations_amount,175500.0,922749.0,117251.0
summary_recipient_defined_text_field_1_value,L5917NON-MPO,L5288SACOG,L5288SACOG

,4036,4041
fmis_transaction_date,2026-02-13 00:00:00,2026-02-17 00:00:00
project_number,5956224,5956224
implementing_agency,Nevada County,Folsom
summary_recipient_defined_text_field_1_value,L5917NON-MPO,L5288SACOG
funding_type_code,IIJA-F,IIJA-A
program_code,YS60,Y603
program_code_description,High Risk Rural Roads Special Rule Program,Hip Comm Proj Cong-Dir 24 Hif Program
recipient_project_number,0814000006L,0814000006L
improvement_type,17,1|15
improvement_type_description,Construction Engineering,New Construction Roadway|Preliminary Engineering
old_project_title_desc,"VARIOUS LOCATIONS THROUGHOUT RIVERSIDE COUNTY, PM00076 BRIDGE PREVENTIVE MAINTENANCE PROGRAM","VARIOUS LOCATIONS THROUGHOUT RIVERSIDE COUNTY, PM00076 BRIDGE PREVENTIVE MAINTENANCE PROGRAM"
obligations_amount,175500,1040000
total_cost_amount,195000,1414412
congressional_district,|03|,|07|
district,|03|,|03|
county_code,65,65
county_name,Nevada County,Sacramento County
county_name_abbrev,|NEV|,|SAC|
implementing_agency_locode,5917,5288
rtpa_name,Nevada County Transportation Commission,Sacramento Area Council of Governments
mpo_name,NON-MPO,Sacramento Area Council Of Governments
new_project_title,Bridge Preventive Maintenance in Folsom,Bridge Preventive Maintenance in Folsom
new_description_col,"Bridge Preventive Maintenance in Folsom, part of the High Risk Rural Roads Special Rule Program. (Federal Project ID: 5956224).","Bridge Preventive Maintenance in Folsom, part of the Hip Comm Proj Cong-Dir 24 Hif Program. (Federal Project ID: 5956224)."

January Data

,5768,5769,5770
fmis_transaction_date,2025-08-11 00:00:00,2025-08-11 00:00:00,2025-08-11 00:00:00
program_code,Y001,Y001,Y115
program_code_description,NATIONAL HIGHWAY PERF IIJA,NATIONAL HIGHWAY PERF IIJA,HIP BRIDGE FORMULA PROGRAM-25
project_number,5956224,5956224,5956224
recipient_project_number,0814000006L,0814000006L,0814000006L
_10_id,0814000006,0814000006,0814000006
project_title,"VARIOUS LOCATIONS THROUGHOUT RIVERSIDE COUNTY, PM00076 BRIDGE PREVENTIVE MAINTENANCE PROGRAM","VARIOUS LOCATIONS THROUGHOUT RIVERSIDE COUNTY, PM00076 BRIDGE PREVENTIVE MAINTENANCE PROGRAM","VARIOUS LOCATIONS THROUGHOUT RIVERSIDE COUNTY, PM00076 BRIDGE PREVENTIVE MAINTENANCE PROGRAM"
county_code,65,65,65
congressional_district,Cong Dist 25,Cong Dist 25,Cong Dist 25
project_status_description,Active,Active,Active
project_description,"VARIOUS LOCATIONS THROUGHOUT RIVERSIDE COUNTY, PM00076 BRIDGE PREVENTIVE MAINTENANCE PROGRAM","VARIOUS LOCATIONS THROUGHOUT RIVERSIDE COUNTY, PM00076 BRIDGE PREVENTIVE MAINTENANCE PROGRAM","VARIOUS LOCATIONS THROUGHOUT RIVERSIDE COUNTY, PM00076 BRIDGE PREVENTIVE MAINTENANCE PROGRAM"
improvement_type,15,17,47
improvement_type_description,Preliminary Engineering,Construction Engineering,Bridge Preservation
total_cost_amount,686701.0,635031.0,4233543.0
obligations_amount,607936.0,559708.0,3731393.0
summary_recipient_defined_text_field_1_value,L5956SCAG,L5956SCAG,L5956SCAG

                                                                                                                                                                                                                            2372
fmis_transaction_date                                                                                                                                                                                        2025-08-11 00:00:00
project_number                                                                                                                                                                                                           5956224
implementing_agency                                                                                                                                                                                             Riverside County
summary_recipient_defined_text_field_1_value                                                                                                                                                                           L5956SCAG
funding_type_code                                                                                                                                                                                                         IIJA-F
program_code                                                                                                                                                                                                           Y001|Y115
program_code_description                                                                                                                               National Highway Performance Program (NHPP)|Hip Bridge Formula Program-25
recipient_project_number                                                                                                                                                                                             0814000006L
improvement_type                                                                                                                                                                                                        15|17|47
improvement_type_description                                                                                                                                Preliminary Engineering|Construction Engineering|Bridge Preservation
old_project_title_desc                                                                                                              VARIOUS LOCATIONS THROUGHOUT RIVERSIDE COUNTY, PM00076 BRIDGE PREVENTIVE MAINTENANCE PROGRAM
obligations_amount                                                                                                                                                                                                       4899037
total_cost_amount                                                                                                                                                                                                        5555275
congressional_district                                                                                                                                                                                                      |25|
district                                                                                                                                                                                                                    |08|
county_code                                                                                                                                                                                                                   65
county_name                                                                                                                                                                                                     Riverside County
county_name_abbrev                                                                                                                                                                                                         |RIV|
implementing_agency_locode                                                                                                                                                                                                  5956
rtpa_name                                                                                                                                                                             Riverside County Transportation Commission
mpo_name                                                                                                                                                                          Southern California Association Of Governments
new_project_title                                                                                                                                                              Bridge Preventive Maintenance in Riverside County
new_description_col                            Bridge Preventive Maintenance in Riverside County, part of the National Highway Performance Program (NHPP), and the Hip Bridge Formula Program-25. (Federal Project ID: 5956224).

### 15C4001

In [39]:
print("June data")
display(check_data.loc[check_data.project_number == "15C4001"].T)
display(df.loc[df.project_number == "15C4001"].T)
print("January Data")
display(jan_2026_agg.loc[jan_2026_agg.project_number == "15C4001"].T)
display(jan_2026.loc[jan_2026.project_number == "15C4001"].T)

June data

,2596,2597,2598,2599
fmis_transaction_date,2025-03-10 00:00:00,2025-03-10 00:00:00,2025-03-10 00:00:00,2025-03-10 00:00:00
program_code,ER05,ER05,ER05,ER05
unnamed:_2,NaN,NaN,NaN,NaN
program_code_description,EMERGENCY REL 2023 SUPPLEMENT,EMERGENCY REL 2023 SUPPLEMENT,EMERGENCY REL 2023 SUPPLEMENT,EMERGENCY REL 2025 SUPPLEMENT
project_number,15C4001,15C4001,15C4001,15C4001
recipient_project_number,0421000028S,0421000028S,0421000028S,0421000028S
_10_id,0421000028,0421000028,0421000028,0421000028
project_title,"IN NAPA AND SOLANO COUNTIES ON ROUTES 121 AND 128 AT VARIOUS LOCATION REPAIR CULVERTS, RETAINING WALLS, AND PAVEMENT. REMOVE HAZARDOUS TREES, REPLACE","IN NAPA AND SOLANO COUNTIES ON ROUTES 121 AND 128 AT VARIOUS LOCATION REPAIR CULVERTS, RETAINING WALLS, AND PAVEMENT. REMOVE HAZARDOUS TREES, REPLACE","IN NAPA AND SOLANO COUNTIES ON ROUTES 121 AND 128 AT VARIOUS LOCATION REPAIR CULVERTS, RETAINING WALLS, AND PAVEMENT. REMOVE HAZARDOUS TREES, REPLACE","IN NAPA AND SOLANO COUNTIES ON ROUTES 121 AND 128 AT VARIOUS LOCATION REPAIR CULVERTS, RETAINING WALLS, AND PAVEMENT. REMOVE HAZARDOUS TREES, REPLACE"
county_code,999,999,999,999
unnamed:_9,NaN,NaN,NaN,NaN
congressional_district,Cong Dist 18,Cong Dist 18,Cong Dist 18,Cong Dist 18
project_status_description,Active,Active,Active,Active
project_description,"UPPER EAST ZAYANTE RD PM 3.51 IN SANTA CRUZ COUNTY PLACED BARRICADES, PLASTIC SHEETING, TEMPORARY BERM AND WARNING SIGNS AT THE DAMAGE SITE. STRUCTURE EX AND BACKFILL, AC PAVEMENT AND DIKE, 24"" HDPE CULVERT WITH HEADWALL, OVERSIDE DRAIN, RSP, EROSION CONTROL AND REVEGETATION.","MAIN STREET AT BATES CREEK PM 0.60 IN SANTA CRUZ COUNTY EMERGENCY OPENING - PLACED BARRICADES AND ROAD CLOSURE SIGNS AT THE DAMAGE SITE. TRAFFIC CONTROL,CLEARING/GRUBBING,REMOVE/DISPOSE OF (E) CULVERT, SHORING,EXCAVATION & BACKFILL, REINFORCED BOX CULVERT WITH WING WALLS,ROCK SLOPE PROTECTION, AGG.BASE,ASPHALT CONCRETE, PLANS.","MAIN STREET AT BATES CREEK PM 0.60 IN SANTA CRUZ COUNTY EMERGENCY OPENING - PLACED BARRICADES AND ROAD CLOSURE SIGNS AT THE DAMAGE SITE. TRAFFIC CONTROL,CLEARING/GRUBBING,REMOVE/DISPOSE OF (E) CULVERT, SHORING,EXCAVATION & BACKFILL, REINFORCED BOX CULVERT WITH WING WALLS,ROCK SLOPE PROTECTION, AGG.BASE,ASPHALT CONCRETE, PLANS.","MAIN STREET AT BATES CREEK PM 0.60 IN SANTA CRUZ COUNTY EMERGENCY OPENING - PLACED BARRICADES AND ROAD CLOSURE SIGNS AT THE DAMAGE SITE. TRAFFIC CONTROL,CLEARING/GRUBBING,REMOVE/DISPOSE OF (E) CULVERT, SHORING,EXCAVATION & BACKFILL, REINFORCED BOX CULVERT WITH WING WALLS,ROCK SLOPE PROTECTION, AGG.BASE,ASPHALT CONCRETE, PLANS."
improvement_type,17,4,15,16
improvement_type_description,Construction Engineering,4R - No Added Capacity,Preliminary Engineering,Right of Way
total_cost_amount,21000.0,2849000.0,200000.0,15000.0
obligations_amount,21000.0,2849000.0,200000.0,15000.0
summary_recipient_defined_text_field_1_value,L5936AMBAG,L5936AMBAG,L5936AMBAG,L5936AMBAG

                                                                                                                                                                                               1737
fmis_transaction_date                                                                                                                                                           2025-03-10 00:00:00
project_number                                                                                                                                                                              15C4001
implementing_agency                                                                                                                                                               Santa Cruz County
summary_recipient_defined_text_field_1_value                                                                                                                                             L5936AMBAG
funding_type_code                                                                                                                                                                               nan
program_code                                                                                                                                                                                   ER05
program_code_description                                                                                                                                                                        nan
recipient_project_number                                                                                                                                                                0421000028S
improvement_type                                                                                                                                                                         17|4|15|16
improvement_type_description                                                                                   Construction Engineering|4R - No Added Capacity|Preliminary Engineering|Right of Way
old_project_title_desc                        IN NAPA AND SOLANO COUNTIES ON ROUTES 121 AND 128 AT VARIOUS LOCATION REPAIR CULVERTS, RETAINING WALLS, AND PAVEMENT. REMOVE HAZARDOUS TREES, REPLACE
obligations_amount                                                                                                                                                                          3085000
total_cost_amount                                                                                                                                                                           3085000
congressional_district                                                                                                                                                                         |18|
district                                                                                                                                                                                       |05|
county_code                                                                                                                                                                                     999
county_name                                                                                                                                                                       Santa Cruz County
county_name_abbrev                                                                                                                                                                            |SCR|
implementing_agency_locode                                                                                                                                                                     5936
rtpa_name                                                                                                                                      Santa Cruz County Regional Transportation Commission
mpo_name                                                                                                                                               Association of Monterey Bay Area Governments
new_project_title                                                                                                                                            Road Construction in Santa Cruz County
new_description_col                                                                                         Road Construction in Santa Cruz County, part of the nan. (Federal Project ID: 15C4001).

January Data

                                                                                                                                                                                               2274
fmis_transaction_date                                                                                                                                                           2025-07-23 00:00:00
project_number                                                                                                                                                                              15C4001
implementing_agency                                                                                                                                                                      California
summary_recipient_defined_text_field_1_value                                                                                                                                           S    ER NONE
funding_type_code                                                                                                                                                                        IIJA-A|nan
program_code                                                                                                                                                                              ER03|ER05
program_code_description                                                                                                                                           Emergency Supplement Funding|nan
recipient_project_number                                                                                                                                                                0421000028S
improvement_type                                                                                                                                                                            6|16|17
improvement_type_description                                                                                                4R - Restoration & Rehabilitation|Right of Way|Construction Engineering
old_project_title_desc                        IN NAPA AND SOLANO COUNTIES ON ROUTES 121 AND 128 AT VARIOUS LOCATION REPAIR CULVERTS, RETAINING WALLS, AND PAVEMENT. REMOVE HAZARDOUS TREES, REPLACE
obligations_amount                                                                                                                                                                         12691679
total_cost_amount                                                                                                                                                                          16113179
congressional_district                                                                                                                                                                         |01|
district                                                                                                                                                                                      |nan|
county_code                                                                                                                                                                                     999
county_name                                                                                                                                                                               Statewide
county_name_abbrev                                                                                                                                                                             |NA|
implementing_agency_locode                                                                                                                                                                      nan
rtpa_name                                                                                                                                                                                      None
mpo_name                                                                                                                                                                                       None
new_project_title                                                                                                                                         Road Restoration & Rehabilitation in Napa
new_description_col                                                Road Restoration & Rehabilitation in Napa, part of the Emergency Supplement Funding, and the nan. (Federal Project ID: 15C4001).

,2404,2405,2406,2407
fmis_transaction_date,2025-07-23 00:00:00,2025-07-23 00:00:00,2025-07-23 00:00:00,2025-07-23 00:00:00
program_code,ER03,ER03,ER03,ER05
program_code_description,EMERGENCY REL 2023 SUPPLEMENT,EMERGENCY REL 2023 SUPPLEMENT,EMERGENCY REL 2023 SUPPLEMENT,EMERGENCY REL 2025 SUPPLEMENT
project_number,15C4001,15C4001,15C4001,15C4001
recipient_project_number,0421000028S,0421000028S,0421000028S,0421000028S
_10_id,0421000028,0421000028,0421000028,0421000028
project_title,"IN NAPA AND SOLANO COUNTIES ON ROUTES 121 AND 128 AT VARIOUS LOCATION REPAIR CULVERTS, RETAINING WALLS, AND PAVEMENT. REMOVE HAZARDOUS TREES, REPLACE","IN NAPA AND SOLANO COUNTIES ON ROUTES 121 AND 128 AT VARIOUS LOCATION REPAIR CULVERTS, RETAINING WALLS, AND PAVEMENT. REMOVE HAZARDOUS TREES, REPLACE","IN NAPA AND SOLANO COUNTIES ON ROUTES 121 AND 128 AT VARIOUS LOCATION REPAIR CULVERTS, RETAINING WALLS, AND PAVEMENT. REMOVE HAZARDOUS TREES, REPLACE","IN NAPA AND SOLANO COUNTIES ON ROUTES 121 AND 128 AT VARIOUS LOCATION REPAIR CULVERTS, RETAINING WALLS, AND PAVEMENT. REMOVE HAZARDOUS TREES, REPLACE"
county_code,999,999,999,999
congressional_district,Cong Dist 0,Cong Dist 0,Cong Dist 0,Cong Dist 0
project_status_description,Closed,Closed,Closed,Closed
project_description,"ON STATE ROUTE: 121. IN NAPA AND SOLANO COUNTIES ON ROUTES 121 AND 128 AT VARIOUS LOCATION REPAIR CULVERTS, RETAINING WALLS, AND PAVEMENT. REMOVE HAZARDOUS TREES, REPLACE GUARDRAILS, AND INSTALL EROSION CONTROL IN FIRE DAMAGED AREAS.","ON STATE ROUTE: 121. IN NAPA AND SOLANO COUNTIES ON ROUTES 121 AND 128 AT VARIOUS LOCATION REPAIR CULVERTS, RETAINING WALLS, AND PAVEMENT. REMOVE HAZARDOUS TREES, REPLACE GUARDRAILS, AND INSTALL EROSION CONTROL IN FIRE DAMAGED AREAS.","ON STATE ROUTE: 121. IN NAPA AND SOLANO COUNTIES ON ROUTES 121 AND 128 AT VARIOUS LOCATION REPAIR CULVERTS, RETAINING WALLS, AND PAVEMENT. REMOVE HAZARDOUS TREES, REPLACE GUARDRAILS, AND INSTALL EROSION CONTROL IN FIRE DAMAGED AREAS.","ON STATE ROUTE: 121. IN NAPA AND SOLANO COUNTIES ON ROUTES 121 AND 128 AT VARIOUS LOCATION REPAIR CULVERTS, RETAINING WALLS, AND PAVEMENT. REMOVE HAZARDOUS TREES, REPLACE GUARDRAILS, AND INSTALL EROSION CONTROL IN FIRE DAMAGED AREAS."
improvement_type,6,16,17,6
improvement_type_description,4R - Restoration & Rehabilitation,Right of Way,Construction Engineering,4R - Restoration & Rehabilitation
total_cost_amount,11069978.28,31850.53,3630259.5,1381091.52
obligations_amount,8458319.68,21239.99,2989440.0,1222680.32
summary_recipient_defined_text_field_1_value,S ER NONE,S ER NONE,S ER NONE,S ER NONE

### P170006

In [37]:
print("June data")
display(check_data.loc[check_data.project_number == "P170006"].T)
display(df.loc[df.project_number == "P170006"].T)
print("January Data")
display(jan_2026_agg.loc[jan_2026_agg.project_number == "P170006"].T)
display(jan_2026.loc[jan_2026.project_number == "P170006"].T)

June data

,5354,5355,5356
fmis_transaction_date,2025-11-21 00:00:00,2025-11-21 00:00:00,2025-11-21 00:00:00
program_code,Y001,Y001,Y001
unnamed:_2,NaN,NaN,NaN
program_code_description,NATIONAL HIGHWAY PERF IIJA,NATIONAL HIGHWAY PERF IIJA,NATIONAL HIGHWAY PERF IIJA
project_number,P170006,P170006,P170006
recipient_project_number,0716000204S,0716000204S,0716000204S
_10_id,0716000204,0716000204,0716000204
project_title,"IN THE CITY OF LOS ANGELES AND NORTH HOLLYWOOD, FROM 170/134 JUNCTION TO OXNARD STREET UNDERCROSSING PLACED STAMPED CONCRETE, ROCK BLANKETS AND CONST","IN THE CITY OF LOS ANGELES AND NORTH HOLLYWOOD, FROM 170/134 JUNCTION TO OXNARD STREET UNDERCROSSING PLACED STAMPED CONCRETE, ROCK BLANKETS AND CONST","IN THE CITY OF LOS ANGELES AND NORTH HOLLYWOOD, FROM 170/134 JUNCTION TO OXNARD STREET UNDERCROSSING PLACED STAMPED CONCRETE, ROCK BLANKETS AND CONST"
county_code,37,37,37
unnamed:_9,NaN,NaN,NaN
congressional_district,Cong Dist 25,Cong Dist 21,Cong Dist 21
project_status_description,Closed,Active,Active
project_description,"ON STATE ROUTE: 8, 11. IN IMPERIAL COUNTY IN AND NEAR EL CENTRO, AT VARIOUS LOCATIONS ON ROUTES 8 AND 111 SLOPE PAVING, MINOR CONCRETE, AND SIGN INSTALLATION","ON STATE ROUTE: 58, 204. KERN COUNTY IN BAKERSFIELD ON ROUTE 58 FROM SOUTH H STREET OVERCROSSING TO ROUTE 204 AND ON ROUTE 204 FROM ROUTE 58/204 SEPARATION TO L STREET UPDATE CURB RAMPS TO MEET ADA STANDARDS","ON STATE ROUTE: 58, 204. KERN COUNTY IN BAKERSFIELD ON ROUTE 58 FROM SOUTH H STREET OVERCROSSING TO ROUTE 204 AND ON ROUTE 204 FROM ROUTE 58/204 SEPARATION TO L STREET UPDATE CURB RAMPS TO MEET ADA STANDARDS"
improvement_type,42,17,28
improvement_type_description,Training,Construction Engineering,Facilities for Pedestrians and Bicycles
total_cost_amount,2600.0,2294000.0,4838506.08
obligations_amount,2300.0,2030800.0,4225715.65
summary_recipient_defined_text_field_1_value,S SCAG,S KCOG,S KCOG

,3487,3488
fmis_transaction_date,2025-11-21 00:00:00,2025-11-21 00:00:00
project_number,P170006,P170006
implementing_agency,California,California
summary_recipient_defined_text_field_1_value,S KCOG,S SCAG
funding_type_code,IIJA-F,IIJA-F
program_code,Y001,Y001
program_code_description,National Highway Performance Program (NHPP),National Highway Performance Program (NHPP)
recipient_project_number,0716000204S,0716000204S
improvement_type,17|28,42
improvement_type_description,Construction Engineering|Facilities for Pedestrians and Bicycles,Training
old_project_title_desc,"IN THE CITY OF LOS ANGELES AND NORTH HOLLYWOOD, FROM 170/134 JUNCTION TO OXNARD STREET UNDERCROSSING PLACED STAMPED CONCRETE, ROCK BLANKETS AND CONST","IN THE CITY OF LOS ANGELES AND NORTH HOLLYWOOD, FROM 170/134 JUNCTION TO OXNARD STREET UNDERCROSSING PLACED STAMPED CONCRETE, ROCK BLANKETS AND CONST"
obligations_amount,12513031,4600
total_cost_amount,14265012,5200
congressional_district,|21|,|25|
district,|07|,|07|
county_code,37,37
county_name,Los Angeles County,Los Angeles County
county_name_abbrev,|LA|,|LA|
implementing_agency_locode,nan,nan
rtpa_name,None,None
mpo_name,None,None
new_project_title,Project in Los Angeles County,Project in Los Angeles County
new_description_col,"Project in Los Angeles County, part of the National Highway Performance Program (NHPP). (Federal Project ID: P170006).","Project in Los Angeles County, part of the National Highway Performance Program (NHPP). (Federal Project ID: P170006)."

January Data

                                                                                                                                                                                               1545
fmis_transaction_date                                                                                                                                                           2025-03-06 00:00:00
project_number                                                                                                                                                                              P170006
implementing_agency                                                                                                                                                                      California
summary_recipient_defined_text_field_1_value                                                                                                                                              S    SCAG
funding_type_code                                                                                                                                                                            IIJA-F
program_code                                                                                                                                                                                   Y001
program_code_description                                                                                                                                National Highway Performance Program (NHPP)
recipient_project_number                                                                                                                                                                0716000204S
improvement_type                                                                                                                                                                            6|17|42
improvement_type_description                                                                                                    4R - Restoration & Rehabilitation|Construction Engineering|Training
old_project_title_desc                        IN THE CITY OF LOS ANGELES AND NORTH HOLLYWOOD, FROM 170/134 JUNCTION TO OXNARD STREET UNDERCROSSING PLACED STAMPED CONCRETE, ROCK BLANKETS AND CONST
obligations_amount                                                                                                                                                                          6912600
total_cost_amount                                                                                                                                                                           7980200
congressional_district                                                                                                                                                                         |29|
district                                                                                                                                                                                       |07|
county_code                                                                                                                                                                                      37
county_name                                                                                                                                                                      Los Angeles County
county_name_abbrev                                                                                                                                                                             |LA|
implementing_agency_locode                                                                                                                                                                      nan
rtpa_name                                                                                                                                                                                      None
mpo_name                                                                                                                                                                                       None
new_project_title                                                                                                                           Road Restoration & Rehabilitation in Los Angeles County
new_description_col                                Road Restoration & Rehabilitation in Los Angeles County, part of the National Highway Performance Program (NHPP). (Federal Project ID: P170006).

,4916,4917,4918
fmis_transaction_date,2025-03-06 00:00:00,2025-03-06 00:00:00,2025-03-06 00:00:00
program_code,Y001,Y001,Y001
program_code_description,NATIONAL HIGHWAY PERF IIJA,NATIONAL HIGHWAY PERF IIJA,NATIONAL HIGHWAY PERF IIJA
project_number,P170006,P170006,P170006
recipient_project_number,0716000204S,0716000204S,0716000204S
_10_id,0716000204,0716000204,0716000204
project_title,"IN THE CITY OF LOS ANGELES AND NORTH HOLLYWOOD, FROM 170/134 JUNCTION TO OXNARD STREET UNDERCROSSING PLACED STAMPED CONCRETE, ROCK BLANKETS AND CONST","IN THE CITY OF LOS ANGELES AND NORTH HOLLYWOOD, FROM 170/134 JUNCTION TO OXNARD STREET UNDERCROSSING PLACED STAMPED CONCRETE, ROCK BLANKETS AND CONST","IN THE CITY OF LOS ANGELES AND NORTH HOLLYWOOD, FROM 170/134 JUNCTION TO OXNARD STREET UNDERCROSSING PLACED STAMPED CONCRETE, ROCK BLANKETS AND CONST"
county_code,37,37,37
congressional_district,Cong Dist 29,Cong Dist 29,Cong Dist 29
project_status_description,Active,Active,Active
project_description,"ON STATE ROUTE: 170. IN THE CITY OF LOS ANGELES AND NORTH HOLLYWOOD, FROM 170/134 JUNCTION TO OXNARD STREET UNDERCROSSING PLACED STAMPED CONCRETE, ROCK BLANKETS AND CONSTRUCT MAINTENANCE VEHICLE PULLOUTS","ON STATE ROUTE: 170. IN THE CITY OF LOS ANGELES AND NORTH HOLLYWOOD, FROM 170/134 JUNCTION TO OXNARD STREET UNDERCROSSING PLACED STAMPED CONCRETE, ROCK BLANKETS AND CONSTRUCT MAINTENANCE VEHICLE PULLOUTS","ON STATE ROUTE: 170. IN THE CITY OF LOS ANGELES AND NORTH HOLLYWOOD, FROM 170/134 JUNCTION TO OXNARD STREET UNDERCROSSING PLACED STAMPED CONCRETE, ROCK BLANKETS AND CONSTRUCT MAINTENANCE VEHICLE PULLOUTS"
improvement_type,6,17,42
improvement_type_description,4R - Restoration & Rehabilitation,Construction Engineering,Training
total_cost_amount,2787200.0,1202000.0,900.0
obligations_amount,2391500.0,1064100.0,700.0
summary_recipient_defined_text_field_1_value,S SCAG,S SCAG,S SCAG

### X037234

In [36]:
print("June data")
display(check_data.loc[check_data.project_number == "X037234"].T)
display(df.loc[df.project_number == "X037234"].T)
print("January Data")
display(jan_2026_agg.loc[jan_2026_agg.project_number == "X037234"].T)
display(jan_2026.loc[jan_2026.project_number == "X037234"].T)

June data

,5528,5529,5530,5531,5532,5533
fmis_transaction_date,2025-12-08 00:00:00,2025-12-08 00:00:00,2025-12-08 00:00:00,2025-12-08 00:00:00,2025-12-08 00:00:00,2025-12-08 00:00:00
program_code,Y001,Y001,Y001,Y001,Y001,Y001
unnamed:_2,NaN,NaN,NaN,NaN,NaN,NaN
program_code_description,NATIONAL HIGHWAY PERF IIJA,NATIONAL HIGHWAY PERF IIJA,NATIONAL HIGHWAY PERF IIJA,NATIONAL HIGHWAY PERF IIJA,NATIONAL HIGHWAY PERF IIJA,NATIONAL HIGHWAY PERF IIJA
project_number,X037234,X037234,X037234,X037234,X037234,X037234
recipient_project_number,0718000046S,0718000046S,0718000046S,0718000046S,0718000046S,0718000046S
_10_id,0718000046,0718000046,0718000046,0718000046,0718000046,0718000046
project_title,"IN THE CITIES OF LOS ANGELES, GLENDALE, AND BURBANK, FROM NORTH OF FLETCHER DRIVE TO ROUTE 170. CONSTRUCT STORM WATER BEST MANAGEMENT PRACTICES (BMPS","IN THE CITIES OF LOS ANGELES, GLENDALE, AND BURBANK, FROM NORTH OF FLETCHER DRIVE TO ROUTE 170. CONSTRUCT STORM WATER BEST MANAGEMENT PRACTICES (BMPS","IN THE CITIES OF LOS ANGELES, GLENDALE, AND BURBANK, FROM NORTH OF FLETCHER DRIVE TO ROUTE 170. CONSTRUCT STORM WATER BEST MANAGEMENT PRACTICES (BMPS","IN THE CITIES OF LOS ANGELES, GLENDALE, AND BURBANK, FROM NORTH OF FLETCHER DRIVE TO ROUTE 170. CONSTRUCT STORM WATER BEST MANAGEMENT PRACTICES (BMPS","IN THE CITIES OF LOS ANGELES, GLENDALE, AND BURBANK, FROM NORTH OF FLETCHER DRIVE TO ROUTE 170. CONSTRUCT STORM WATER BEST MANAGEMENT PRACTICES (BMPS","IN THE CITIES OF LOS ANGELES, GLENDALE, AND BURBANK, FROM NORTH OF FLETCHER DRIVE TO ROUTE 170. CONSTRUCT STORM WATER BEST MANAGEMENT PRACTICES (BMPS"
county_code,37,37,37,37,37,37
unnamed:_9,NaN,NaN,NaN,NaN,NaN,NaN
congressional_district,Cong Dist 1,Cong Dist 1,Cong Dist 1,Cong Dist 31,Cong Dist 31,Cong Dist 31
project_status_description,Active,Active,Active,Active,Active,Active
project_description,"ON STATE ROUTE: 89. SISKIYOU COUNTY AT AND NEAR MCCLOUD FROM 0.8 MILE SOUTH OF MUD CREEK BRIDGE TOROUTE 5 PLACE HMA, REPLACE CULVERTS, INSTALL GUARDRAIL, INSTALL FENCING","ON STATE ROUTE: 89. SISKIYOU COUNTY AT AND NEAR MCCLOUD FROM 0.8 MILE SOUTH OF MUD CREEK BRIDGE TOROUTE 5 PLACE HMA, REPLACE CULVERTS, INSTALL GUARDRAIL, INSTALL FENCING","ON STATE ROUTE: 89. SISKIYOU COUNTY AT AND NEAR MCCLOUD FROM 0.8 MILE SOUTH OF MUD CREEK BRIDGE TOROUTE 5 PLACE HMA, REPLACE CULVERTS, INSTALL GUARDRAIL, INSTALL FENCING","ON STATE ROUTE: 210. IN AND NEAR GLENDORA AND SAN DIMAS, FROM EAST OF SUNFLOWER AVENUE TO EAST OF WALNUT AVENUE; ALSO FROM GLADSTONE STREET TO ROUTE 210 (PM R11.3R/R12.3R). UPGRADE HIGHWAY LIGHTING TO USE LIGHT EMITTING DIODES (LEDS), UPGRADE SIGN PANELS, REPLACE STRUCTURAL LIGHT POLES, AND MODIFY OVERHEAD SIGN STRUCTURES","ON STATE ROUTE: 210. IN AND NEAR GLENDORA AND SAN DIMAS, FROM EAST OF SUNFLOWER AVENUE TO EAST OF WALNUT AVENUE; ALSO FROM GLADSTONE STREET TO ROUTE 210 (PM R11.3R/R12.3R). UPGRADE HIGHWAY LIGHTING TO USE LIGHT EMITTING DIODES (LEDS), UPGRADE SIGN PANELS, REPLACE STRUCTURAL LIGHT POLES, AND MODIFY OVERHEAD SIGN STRUCTURES","ON STATE ROUTE: 210. IN AND NEAR GLENDORA AND SAN DIMAS, FROM EAST OF SUNFLOWER AVENUE TO EAST OF WALNUT AVENUE; ALSO FROM GLADSTONE STREET TO ROUTE 210 (PM R11.3R/R12.3R). UPGRADE HIGHWAY LIGHTING TO USE LIGHT EMITTING DIODES (LEDS), UPGRADE SIGN PANELS, REPLACE STRUCTURAL LIGHT POLES, AND MODIFY OVERHEAD SIGN STRUCTURES"
improvement_type,6,17,42,6,17,42
improvement_type_description,4R - Restoration & Rehabilitation,Construction Engineering,Training,4R - Restoration & Rehabilitation,Construction Engineering,Training
total_cost_amount,17812800.0,1790000.0,1700.0,7369400.0,2031000.0,9300.0
obligations_amount,15614600.0,1584600.0,1500.0,6595700.0,1859700.0,8500.0
summary_recipient_defined_text_field_1_value,S NON-MPO,S NON-MPO,S NON-MPO,S SCAG,S SCAG,S SCAG

,3601,3602
fmis_transaction_date,2025-12-08 00:00:00,2025-12-08 00:00:00
project_number,X037234,X037234
implementing_agency,California,California
summary_recipient_defined_text_field_1_value,S NON-MPO,S SCAG
funding_type_code,IIJA-F,IIJA-F
program_code,Y001,Y001
program_code_description,National Highway Performance Program (NHPP),National Highway Performance Program (NHPP)
recipient_project_number,0718000046S,0718000046S
improvement_type,6|17|42,6|17|42
improvement_type_description,4R - Restoration & Rehabilitation|Construction Engineering|Training,4R - Restoration & Rehabilitation|Construction Engineering|Training
old_project_title_desc,"IN THE CITIES OF LOS ANGELES, GLENDALE, AND BURBANK, FROM NORTH OF FLETCHER DRIVE TO ROUTE 170. CONSTRUCT STORM WATER BEST MANAGEMENT PRACTICES (BMPS","IN THE CITIES OF LOS ANGELES, GLENDALE, AND BURBANK, FROM NORTH OF FLETCHER DRIVE TO ROUTE 170. CONSTRUCT STORM WATER BEST MANAGEMENT PRACTICES (BMPS"
obligations_amount,34401400,16927800
total_cost_amount,39209000,18819400
congressional_district,|01|,|31|
district,|07|,|07|
county_code,37,37
county_name,Los Angeles County,Los Angeles County
county_name_abbrev,|LA|,|LA|
implementing_agency_locode,nan,nan
rtpa_name,None,None
mpo_name,None,None
new_project_title,Road Restoration & Rehabilitation in Los Angeles County,Road Restoration & Rehabilitation in Los Angeles County
new_description_col,"Road Restoration & Rehabilitation in Los Angeles County, part of the National Highway Performance Program (NHPP). (Federal Project ID: X037234).","Road Restoration & Rehabilitation in Los Angeles County, part of the National Highway Performance Program (NHPP). (Federal Project ID: X037234)."

January Data

                                                                                                                                                                                               1635
fmis_transaction_date                                                                                                                                                           2025-03-27 00:00:00
project_number                                                                                                                                                                              X037234
implementing_agency                                                                                                                                                                      California
summary_recipient_defined_text_field_1_value                                                                                                                                              S    SCAG
funding_type_code                                                                                                                                                                            IIJA-F
program_code                                                                                                                                                                                   Y001
program_code_description                                                                                                                                National Highway Performance Program (NHPP)
recipient_project_number                                                                                                                                                                0718000046S
improvement_type                                                                                                                                                                            6|17|42
improvement_type_description                                                                                                    4R - Restoration & Rehabilitation|Construction Engineering|Training
old_project_title_desc                        IN THE CITIES OF LOS ANGELES, GLENDALE, AND BURBANK, FROM NORTH OF FLETCHER DRIVE TO ROUTE 170. CONSTRUCT STORM WATER BEST MANAGEMENT PRACTICES (BMPS
obligations_amount                                                                                                                                                                         14494800
total_cost_amount                                                                                                                                                                          16037600
congressional_district                                                                                                                                                                      |29|30|
district                                                                                                                                                                                       |07|
county_code                                                                                                                                                                                      37
county_name                                                                                                                                                                      Los Angeles County
county_name_abbrev                                                                                                                                                                             |LA|
implementing_agency_locode                                                                                                                                                                      nan
rtpa_name                                                                                                                                                                                      None
mpo_name                                                                                                                                                                                       None
new_project_title                                                                                                                           Road Restoration & Rehabilitation in Los Angeles County
new_description_col                                Road Restoration & Rehabilitation in Los Angeles County, part of the National Highway Performance Program (NHPP). (Federal Project ID: X037234).

,5086,5087,5088,5089,5090,5091
fmis_transaction_date,2025-03-27 00:00:00,2025-03-27 00:00:00,2025-03-27 00:00:00,2025-03-27 00:00:00,2025-03-27 00:00:00,2025-03-27 00:00:00
program_code,Y001,Y001,Y001,Y001,Y001,Y001
program_code_description,NATIONAL HIGHWAY PERF IIJA,NATIONAL HIGHWAY PERF IIJA,NATIONAL HIGHWAY PERF IIJA,NATIONAL HIGHWAY PERF IIJA,NATIONAL HIGHWAY PERF IIJA,NATIONAL HIGHWAY PERF IIJA
project_number,X037234,X037234,X037234,X037234,X037234,X037234
recipient_project_number,0718000046S,0718000046S,0718000046S,0718000046S,0718000046S,0718000046S
_10_id,0718000046,0718000046,0718000046,0718000046,0718000046,0718000046
project_title,"IN THE CITIES OF LOS ANGELES, GLENDALE, AND BURBANK, FROM NORTH OF FLETCHER DRIVE TO ROUTE 170. CONSTRUCT STORM WATER BEST MANAGEMENT PRACTICES (BMPS","IN THE CITIES OF LOS ANGELES, GLENDALE, AND BURBANK, FROM NORTH OF FLETCHER DRIVE TO ROUTE 170. CONSTRUCT STORM WATER BEST MANAGEMENT PRACTICES (BMPS","IN THE CITIES OF LOS ANGELES, GLENDALE, AND BURBANK, FROM NORTH OF FLETCHER DRIVE TO ROUTE 170. CONSTRUCT STORM WATER BEST MANAGEMENT PRACTICES (BMPS","IN THE CITIES OF LOS ANGELES, GLENDALE, AND BURBANK, FROM NORTH OF FLETCHER DRIVE TO ROUTE 170. CONSTRUCT STORM WATER BEST MANAGEMENT PRACTICES (BMPS","IN THE CITIES OF LOS ANGELES, GLENDALE, AND BURBANK, FROM NORTH OF FLETCHER DRIVE TO ROUTE 170. CONSTRUCT STORM WATER BEST MANAGEMENT PRACTICES (BMPS","IN THE CITIES OF LOS ANGELES, GLENDALE, AND BURBANK, FROM NORTH OF FLETCHER DRIVE TO ROUTE 170. CONSTRUCT STORM WATER BEST MANAGEMENT PRACTICES (BMPS"
county_code,37,37,37,37,37,37
congressional_district,Cong Dist 29,Cong Dist 29,Cong Dist 29,Cong Dist 30,Cong Dist 30,Cong Dist 30
project_status_description,Active,Active,Active,Active,Active,Active
project_description,"ON STATE ROUTE: 5. IN THE CITIES OF LOS ANGELES, GLENDALE, AND BURBANK, FROM NORTH OF FLETCHER DRIVE TO ROUTE 170. CONSTRUCT STORM WATER BEST MANAGEMENT PRACTICES (BMPS), THIS PROJECT PROPOSED 20 STORM WATER TREATMENT BEST MANAGEMENT PRACTICES (BMPS) AT VARIOUS STORM DRAIN OUTFALL/DISCHARGE AT 20 LOCATIONS ALONG NORTHBOUND AND SOUTHBOUND INTERSTATE 5, BETWEEN FLETCHER DRIVE AND STATE ROUTE 170, AS WELL AS ALONG ROUTE 710 AT ATLANTIC BOULEVARD AND BANDINI IN LOS ANGELES COUNTY. THE PROPOSED BMPS'S WILL MEET THE TUJUNGA WASH, BURBANK WESTERN CHANNEL, LOS ANGELES RIVER REACH 3, AND LOS ANGELES RIVER REACH 2 ESTUARY METAL TOTAL MAXIMUM DAILY LOAD (TMDL) REQUIREMENTS, THESE RECEIVING WATER BODIES ARE ALSO IMPAIRED FOR TRASH, BACTERIA, AND TOXIC POLLUTANTS. THE CORRIDOR STORM WATER MANAGEMENT STUDY (CORRIDOR STUDIES) RECOMMENDED BMPS TO TREAT THE IMPAIRMENT AND IMPROVE THE WATER QUALITY IN THE WATER BODIES.","ON STATE ROUTE: 5. IN THE CITIES OF LOS ANGELES, GLENDALE, AND BURBANK, FROM NORTH OF FLETCHER DRIVE TO ROUTE 170. CONSTRUCT STORM WATER BEST MANAGEMENT PRACTICES (BMPS), THIS PROJECT PROPOSED 20 STORM WATER TREATMENT BEST MANAGEMENT PRACTICES (BMPS) AT VARIOUS STORM DRAIN OUTFALL/DISCHARGE AT 20 LOCATIONS ALONG NORTHBOUND AND SOUTHBOUND INTERSTATE 5, BETWEEN FLETCHER DRIVE AND STATE ROUTE 170, AS WELL AS ALONG ROUTE 710 AT ATLANTIC BOULEVARD AND BANDINI IN LOS ANGELES COUNTY. THE PROPOSED BMPS'S WILL MEET THE TUJUNGA WASH, BURBANK WESTERN CHANNEL, LOS ANGELES RIVER REACH 3, AND LOS ANGELES RIVER REACH 2 ESTUARY METAL TOTAL MAXIMUM DAILY LOAD (TMDL) REQUIREMENTS, THESE RECEIVING WATER BODIES ARE ALSO IMPAIRED FOR TRASH, BACTERIA, AND TOXIC POLLUTANTS. THE CORRIDOR STORM WATER MANAGEMENT STUDY (CORRIDOR STUDIES) RECOMMENDED BMPS TO TREAT THE IMPAIRMENT AND IMPROVE THE WATER QUALITY IN THE WATER BODIES.","ON STATE ROUTE: 5. IN THE CITIES OF LOS ANGELES, GLENDALE, AND BURBANK, FROM NORTH OF FLETCHER DRIVE TO ROUTE 170. CONSTRUCT STORM WATER BEST MANAGEMENT PRACTICES (BMPS), THIS PROJECT PROPOSED 20 STORM WATER TREATMENT BEST MANAGEMENT PRACTICES (BMPS) AT VARIOUS STORM DRAIN OUTFALL/DISCHARGE AT 20 LOCATIONS ALONG NORTHBOUND AND SOUTHBOUND INTERSTATE 5, BETWEEN FLETCHER DRIVE AND STATE ROUTE 170, AS WELL AS ALONG ROUTE 710 AT ATLANTIC BOULEVARD AND BANDINI IN LOS ANGELES COUNTY. THE PROPOSED BMPS'S WILL MEET THE TUJUNGA WASH, BURBANK WESTERN CHANNEL, LOS ANGELES RIVER REACH 3, AND LOS ANGELES RIVER REACH 2 ESTUARY METAL TOTAL MAXIMUM DAILY LOAD (TMDL) REQUIREMENTS, THESE RECEIVING WATER BODIES ARE ALSO IMPAIRED FOR TRASH, BACTERIA, AND TOXIC POLLUTANTS. THE CORRIDOR STORM WATER MANAGEMENT STUDY (CORRIDOR STUDIES) RECOMMENDED BMPS TO TREAT THE IMPAIRMENT AND IMPROVE THE WATER QUALITY IN THE WATER BODIES.","ON STATE ROUTE: 5. IN THE CITIES OF LOS ANGELES, GLENDALE, AND BURBANK, FROM NORTH OF FLETCHER DRIVE TO ROUTE 170. CONSTRUCT STORM WATER BEST MANAGEMENT PRACTICES (BMPS), THIS PROJECT PROPOSED 20 STORM WATER TREATMENT BEST MANAGEMENT PRACTICES (BMPS) AT VARIOUS STORM DRAIN OUTFALL/DISCHARGE AT 20 LOCATIONS ALONG NORTHBOUND AND SOUTHBOUND INTERSTATE 5, BETWEEN FLETCHER DRIVE AND STATE ROUTE 170, AS WELL AS ALONG ROUTE 710 AT ATLANTIC BOULEVARD AND BANDINI IN LOS ANGELES COUNTY. THE PROPOSED BMPS'S WILL MEET THE TUJUNGA WASH, BURBANK WESTERN CHANNEL, LOS ANGELES RIVER REACH 3, AND LOS ANGELES RIVER REACH 2 ESTUARY METAL TOTAL MAXIMUM DAILY LOAD (TMDL) REQUIREMENTS, THESE RECEIVING WATER BODIES ARE ALSO IMPAIRED FOR TRASH, BACTERIA, AND TOXIC POLLUTANTS. THE CORRIDOR STORM WATER MANAGEMENT STUDY (CORRIDOR STUDIES) RECOMMENDED BMPS TO TREAT THE IMPAIRMENT AND IMPROVE THE WATER QUALITY IN THE WATER BODIES.","ON STATE ROUTE: 5. IN THE CITIES OF LOS ANGELES, GLENDALE, AND BURBANK, FROM NORTH OF FLETCHER DRIVE TO ROUTE 170. CONSTRUCT STORM WATER BEST MANAGEMENT PRACTICES (BMPS), THIS PROJECT PROPOSED 20 STORM WATER TREATMENT BEST MANAGEMENT PRACTICES (BMPS) AT VARIOUS STORM DRAIN OUTFALL/DISCHARGE AT 20 LOCATIONS ALONG NORTHBOUND AND SOUTHBOUND INTERSTATE 5, BETWEEN FLETCHER DRIVE AND STATE ROUTE 170, AS WELL AS ALONG ROUTE 710 AT ATLANTIC BOULEVARD AND BANDINI IN LOS ANGELES COUNTY. THE PROPOSED BMPS'S WILL MEET THE TUJUNGA WASH, BURBANK WESTERN CHANNEL, LOS ANGELES RIVER REACH 3, AND LOS ANGELES RIVER REACH 2 ESTUARY METAL TOTAL MAXIMUM DAILY LOAD (TMDL) REQUIREMENTS, THESE RECEIVING WATER BODIES ARE ALSO IMPAIRED FOR TRASH, BACTERIA, AND TOXIC POLLUTANTS. THE CORRIDOR STORM WATER MANAGEMENT STUDY (CORRIDOR STUDIES) RECOMMENDED BMPS TO TREAT THE IMPAIRMENT AND IMPROVE THE WATER QUALITY IN THE WATER BODIES.","ON STATE ROUTE: 5. IN THE CITIES OF LOS ANGELES, GLENDALE, AND BURBANK, FROM NORTH OF FLETCHER DRIVE TO ROUTE 170. CONSTRUCT STORM WATER BEST MANAGEMENT PRACTICES (BMPS), THIS PROJECT PROPOSED 20 STORM WATER TREATMENT BEST MANAGEMENT PRACTICES (BMPS) AT VARIOUS STORM DRAIN OUTFALL/DISCHARGE AT 20 LOCATIONS ALONG NORTHBOUND AND SOUTHBOUND INTERSTATE 5, BETWEEN FLETCHER DRIVE AND STATE ROUTE 170, AS WELL AS ALONG ROUTE 710 AT ATLANTIC BOULEVARD AND BANDINI IN LOS ANGELES COUNTY. THE PROPOSED BMPS'S WILL MEET THE TUJUNGA WASH, BURBANK WESTERN CHANNEL, LOS ANGELES RIVER REACH 3, AND LOS ANGELES RIVER REACH 2 ESTUARY METAL TOTAL MAXIMUM DAILY LOAD (TMDL) REQUIREMENTS, THESE RECEIVING WATER BODIES ARE ALSO IMPAIRED FOR TRASH, BACTERIA, AND TOXIC POLLUTANTS. THE CORRIDOR STORM WATER MANAGEMENT STUDY (CORRIDOR STUDIES) RECOMMENDED BMPS TO TREAT THE IMPAIRMENT AND IMPROVE THE WATER QUALITY IN THE WATER BODIES."
improvement_type,6,17,42,6,17,42
improvement_type_description,4R - Restoration & Rehabilitation,Construction Engineering,Training,4R - Restoration & Rehabilitation,Construction Engineering,Training
total_cost_amount,1825784.52,760878.0,838.96,3832415.48,1597122.0,1761.04
obligations_amount,1641115.11,696729.34,742.16,3444784.89,1462470.66,1557.84
summary_recipient_defined_text_field_1_value,S SCAG,S SCAG,S SCAG,S SCAG,S SCAG,S SCAG

## Export Data

In [ ]:
### rename the file for export to GCS
### use date to rename

In [ ]:
_script_utils.export_to_gcs(df, "01142026_agg")

## Comparing latest cleaned data with older version

In [ ]:
jan_2026 = "gs://calitp-analytics-data/data-analyses/dla/dla-iija/FMIS_Projects_Universe_IIJA_Reporting_01142026_agg.csv"

In [ ]:
jan_df = pd.read_csv(jan_2026)

In [ ]:
len(jan_df)

In [ ]:
jan_df.head(1)

In [ ]:
oct_2025 = "gs://calitp-analytics-data/data-analyses/dla/dla-iija/FMIS_Projects_Universe_IIJA_Reporting_10202025_agg.csv"

In [ ]:
oct_df = pd.read_csv(oct_2025)

In [ ]:
len(oct_df)

In [ ]:
oct_df.head(1)

## Removing S***ba
### `data_utils`

In [ ]:
def update_program_code_list2():
    updated_codes = to_snakecase(
        pd.read_excel(
            f"{GCS_FILE_PATH}/program_codes/FY21-22ProgramCodesAsOf5-25-2022.v2_expanded090823.xlsx"
        )
    )[["iija_program_code", "new_description"]]
    original_codes = to_snakecase(
        pd.read_excel(
            f"{GCS_FILE_PATH}/program_codes/Copy of lst_IIJA_Code_20230908.xlsx"
        )
    )[["iija_program_code", "description", "program_name"]]

    program_codes = pd.merge(
        updated_codes,
        original_codes,
        on="iija_program_code",
        how="outer",
        indicator=True,
    )
    program_codes["new_description"] = program_codes["new_description"].str.strip()

    program_codes.new_description.fillna(program_codes["description"], inplace=True)

    program_codes = program_codes.drop(columns={"description", "_merge"})

    def add_program_to_row(row):
        if "Program" not in row["program_name"]:
            return row["program_name"] + " Program"
        else:
            return row["program_name"]

    program_codes["program_name"] = program_codes.apply(add_program_to_row, axis=1)

    return program_codes

### `script_utils`

In [ ]:
def county_district_crosswalk() -> pd.DataFrame:
    """
    Aggregate locodes dataset to find which
    districts a county lies in.
    """
    # Load locodes
    locodes_df = _script_utils.load_locodes()

    # Load counties
    county_base = _script_utils.load_county()

    county_district = locodes_df[["district", "county_name"]].drop_duplicates()

    county_info = pd.merge(
        county_base,
        county_district,
        how="left",
        left_on="county_description",
        right_on="county_name",
    ).drop(columns=["county_name"])
    return county_info

In [ ]:
test1 = county_district_crosswalk()

In [ ]:
test1.head()